lmc-eu/spirit-design-system

.github/CODEOWNERS
* @see https://help.github.com/en/articles/about-code-owners
=> Chore: Define code owners as default reviewers for PRs

.github/workflows/deploy.yaml, .gitignore, CONTRIBUTING.md, Makefile, bin/ci/npm-auth.sh, commitlint.config.js, lerna.json
* after publish and tag is another run of CI skipped via [ci-skip]
* @see https://github.blog/changelog/
2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
=> DS-43 Chore: Automatic package deploy after merge to main branch

.storybook/assets/stylesheets/index.scss, packages/web-react/src/components/Tag/README.md, packages/web-react/src/components/Tag/Tag.stories.tsx, packages/web-react/src/components/Tag/Tag.tsx, packages/web-react/src/components/Tag/index.tsx, packages/web-react/src/types/main.d.ts
Add react implementation of component Tag and add into storybook examples
=> DS-56 Feat: Add react implementation of component Tag

examples/web-react/.gitignore, examples/web-react/src/demo.jsx, examples/web-react/webpack.config.js, package.json, packages/web-react/config/rollup.config.js, packages/web-react/config/tsconfig.json, packages/web-react/package.json, packages/web-react/scripts/entryPoints.js, packages/web-react/scripts/helpers.ts, packages/web-react/scripts/prepareDist.js, packages/web-react/scripts/resolveModuleIds.ts, packages/web-react/src/components/Button/index.tsx, packages/web-react/src/components/Tag/index.tsx, packages/web-react/src/components/index.tsx, packages/web-react/src/index.tsx, yarn.lock
* package is linked in node_modules as entire package directory
* src or dist are present
* so we can use build path or add support for typescript in src
=> Fix: Path to package in lerna workspace

.github/workflows/test.yaml
* run tests for all packages if exists
* try to build all packages
* try to build storybook
=> Chore(ci): Test packages

examples/web-react/src/demo.jsx, packages/web-react/src/components/Button/Button.stories.tsx, packages/web-react/src/components/Button/Button.tsx, packages/web/src/components/Button/README.md, packages/web/src/components/Button/_Button.scss
- Update React implementation
- Add css class `Button--block`
=> DS-65 Update Button implementation

LICENSE.md, README.md, packages/design-tokens/LICENSE.md, packages/design-tokens/README.md, packages/web-react/LICENSE.md, packages/web-react/README.md, packages/web/LICENSE.md, packages/web/README.md
Include MIT license file for every package.
=> Docs(license): Include license file

README.md
Provide badges with package versions in table in main readme.
=> Docs: Introduce column with package versions in root readme

packages/design-tokens/CHANGELOG.md, packages/web-react/CHANGELOG.md, packages/web/CHANGELOG.md
Must also fix https://github.com/lmc-eu/code-quality-tools/issues/48
=> Style: Reformat changelogs using Prettier

examples/web-react/index.html, examples/web/index.html, examples/web/jobs.html, packages/design-tokens/README.md, packages/web/CONTRIBUTING.md, packages/web/README.md
Live preview:
- [`spirit-design-tokens` README](https://github.com/lmc-eu/spirit-design-system/tree/docs/improve/packages/design-tokens#readme)
- [`spirit-web` README](https://github.com/lmc-eu/spirit-design-system/tree/docs/improve/packages/web#readme)
- [`spirit-web` CONTRIBUTING](https://github.com/lmc-eu/spirit-design-system/blob/docs/improve/packages/web/CONTRIBUTING.md)
(Some links in these files may not work properly until merged.)
=> Improve docs for both users and contributors

.stylelintrc.js, packages/design-tokens/package.json, packages/web/package.json
* configuration files should be in similar format
=> Chore: Prefer javascript for configuration if possible

.github/workflows/test.yaml
* solves missing status of Code Quality Checks badge in README
=> Chore: Schedule code quality checks to run every day even on main branch

.github/CODEOWNERS
Do not bother @adamkudrna and @crishpeen with React and add @janicekt as code owner.
=> Chore(web-react): Change codeowners for web-react package

.github/workflows/test.yaml, README.md
* and also display badge in readme
=> Chore: Publish code coverage report to coveralls.io

.storybook/assets/stylesheets/index.scss, packages/web-react/scripts/entryPoints.js, packages/web-react/src/components/TextField/README.md, packages/web-react/src/components/TextField/TextField.stories.tsx, packages/web-react/src/components/TextField/TextField.tsx, packages/web-react/src/components/TextField/__tests__/TextField.test.tsx, packages/web-react/src/components/TextField/__tests__/useTextFieldStyleProps.test.tsx, packages/web-react/src/components/TextField/index.tsx, packages/web-react/src/components/TextField/useTextFieldStyleProps.tsx, packages/web-react/src/components/index.tsx, packages/web-react/src/types/index.ts, packages/web-react/src/types/textField.ts
React component based on https://github.com/lmc-eu/spirit-design-system/pull/140
=> Feat(web-react): Introduce TextField component (refs #DS-120)

.storybook/assets/stylesheets/index.scss, examples/web-react/index.html, examples/web-react/package.json, examples/web-react/src/demo.jsx, examples/web/index.html, examples/web/jobs.html, examples/web/package.json, examples/web/src/jobs/jobs.scss, packages/web/package.json, packages/web/src/components/Container/_Container.scss, packages/web/src/components/TextField/_TextField.scss, packages/web/src/foundation/_box-sizing.scss, packages/web/src/foundation/_reset.scss, packages/web/src/foundation/_shared.scss, packages/web/src/foundation/index.scss, yarn.lock
Normalize.css: https://github.com/csstools/normalize.css/blob/main/normalize.css
=> Feat(web): Introduce foundation CSS layer #DS-173

examples/web/index.html, examples/web/jobs.html, examples/web/src/jobs/jobs.scss, packages/web/src/components/CheckboxField/README.md, packages/web/src/components/CheckboxField/_CheckboxField.scss, packages/web/src/components/CheckboxField/_theme.scss, packages/web/src/components/CheckboxField/index.scss, packages/web/src/components/TextField/README.md, packages/web/src/components/TextField/_TextField.scss, packages/web/src/components/index.scss, packages/web/src/tools/_accessibility.scss
=> Feat(web): Introduce CheckboxField component (refs #DS-136)

packages/web-react/config/jest/config.js
* it is not a test nor a fixture
=> Test(web-react): Ignore data providers in test directory

examples/web/index.html, packages/web/src/js/BaseComponent.ts, packages/web/src/js/Header.ts, packages/web/src/js/Password.ts, packages/web/src/js/__tests__/BaseComponent.test.ts, packages/web/src/js/__tests__/Password.test.ts, packages/web/src/js/dom/EventHandler.ts, packages/web/src/js/dom/InstanceMap.ts, packages/web/src/js/dom/__tests__/InstanceMap.test.ts, packages/web/src/js/index.esm.ts, packages/web/src/js/index.umd.ts
Introducing Password Field toggle JS handler to show and hide passwords.
=> Feat(web): Introduce JavaScript handler for Password toggle (refs

.github/workflows/test.yaml
Publish code coverage also for web package.
=> Chore(ci): Publish code coverage from multiple packages at once

packages/web/src/scss/helpers/_text.scss, packages/web/src/scss/helpers/index.scss
Demo: https://codepen.io/adamkudrna/pen/dyJxQBB
=> Feat(web): Introduce text helper for truncating single- and multiline texts #DS-209

packages/web/src/scss/components/Button/README.md, packages/web/src/scss/components/Button/_Button.scss, packages/web/src/scss/components/Header/_Header.scss, packages/web/src/scss/components/TextField/README.md, packages/web/src/scss/components/TextField/_TextField.scss
Supported interaction classes: `is-disabled`, `has-error`, `has-warning`, `has-success`.
Allow styling of validation messages via data attribute selector (`data-element="validator_message"`) so messages can be dynamically created by JavaScript.
=> Feat(web): Support JS interaction classes for `Button` and `TextField` components

packages/web/src/scss/helpers/_breakout.scss, packages/web/src/scss/helpers/index.html, packages/web/src/scss/helpers/index.scss, packages/web/src/scss/tools/_breakout.scss
=> Feat(web): Introduce breakout helper and mixin to expand content out of `Container`

.github/workflows/test.yaml
The test pipeline was canceled after 5 minutes.
=> Chore(ci): Set test pipeline timeout to 10 minutes

packages/web/src/scss/helpers/_list.scss, packages/web/src/scss/helpers/index.html, packages/web/src/scss/helpers/index.scss
=> Feat(web): Add `list-unstyled` helper class for unstyled lists

.github/workflows/deploy.yaml, packages/web/index.html, packages/web/package.json
* also need to setup base path for vite gh-pages build
=> Chore(web): Fix deploy to GH pages by making links relative to root

packages/web/src/js/BaseComponent.ts, packages/web/src/js/Tooltip.ts, packages/web/src/js/__tests__/BaseComponent.test.ts, packages/web/src/js/__tests__/Tooltip.test.ts, packages/web/src/js/global.d.ts, packages/web/src/js/index.esm.ts, packages/web/src/js/index.umd.ts, packages/web/src/js/utils/ComponentFunctions.ts, packages/web/src/scss/components/Tooltip/README.md, packages/web/src/scss/components/Tooltip/index.html, packages/web/tests/helpers/fixture.ts
Introducing JS plugin with dismiss and toggle functionality for Tooltip.
=> Feat(web): Introduce Tooltip component JS plugin

README.md
* not the php version required
=> Docs(web-twig): Display package version on main README file

packages/icons/package.json, packages/icons/scripts/build.js
Replace fill with currentColor and create SVG sprite.
=> Feat(icons): Add script to process SVGs in Icons package

packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tooltipDefaultPure.twig__1.html
=> Fix(web-twig): Tooltip raw id attribute

packages/web-twig/CHANGELOG.md, packages/web-twig/src/Resources/components/RadioField/README.md, packages/web-twig/src/Resources/components/RadioField/RadioField.twig, packages/web-twig/src/Resources/twig-components/radioField.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefault.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefaultPure.twig__1.html, packages/web-twig/tests/components-fixtures/radioFieldDefault.twig, packages/web-twig/tests/components-fixtures/radioFieldDefaultPure.twig
=> Feat(web-twig): Introduce RadioField component

.eslintignore
* one is placed in `packages/web-twig` directory
=> Style(repo): Ignore `vendor` directory

packages/web-twig/src/Resources/components/Link/Link.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set linkDefault.twig__1.html
twig implementation is different compared to react and html.. that's why I unify.
=> Fix(web-twig): Unifying Link implementation

packages/web-react/src/components/Tag/Tag.stories.tsx, packages/web-react/src/components/Tag/Tag.tsx, packages/web-react/src/components/Tag/index.ts, packages/web-react/src/types/index.ts, packages/web-react/src/types/tag.ts
- Created SpiritTagProps for Tag component in shared folder
- Added StyleProps interface into SpiritTagProps
- ~~Added `UNSAFE_*` properties to Storybook~~
=> Fix(web-react): Added StyleProps to Tag component #DS-325

packages/web-react/src/components/Container/Container.tsx, packages/web-react/src/components/Stack/Stack.tsx, packages/web-react/src/components/Tabs/TabContent.tsx, packages/web-react/src/components/Tabs/TabItem.tsx, packages/web-react/src/components/Tabs/TabLink.tsx, packages/web-react/src/components/Tabs/TabList.tsx, packages/web-react/src/components/Tabs/TabPane.tsx, packages/web-react/src/components/Tabs/Tabs.tsx, packages/web-react/src/types/alert.ts, packages/web-react/src/types/breadcrumbs.ts, packages/web-react/src/types/button.ts, packages/web-react/src/types/checkboxField.ts, packages/web-react/src/types/grid.ts, packages/web-react/src/types/header.ts, packages/web-react/src/types/heading.ts, packages/web-react/src/types/icon.ts, packages/web-react/src/types/link.ts, packages/web-react/src/types/pill.ts, packages/web-react/src/types/radioField.ts, packages/web-react/src/types/shared/index.ts, packages/web-react/src/types/shared/rest.ts, packages/web-react/src/types/tag.ts, packages/web-react/src/types/text.ts, packages/web-react/src/types/textField.ts
1. Created `shared/rest.ts` with RestProps
2. Added to each React component interface
3. Update necessary properties for 'Link' and 'TextField'
=> Fix(web-react): Create RestProps and added to all RC #DS-332

packages/web/partials/layout/base.hbs, packages/web/src/scss/components/Grid/README.md, packages/web/src/scss/components/Grid/_Grid.scss, packages/web/src/scss/components/Grid/_theme.scss, packages/web/src/scss/components/Grid/_tools.scss, packages/web/src/scss/components/Grid/index.html
=> Web: Introduce Grid Span

packages/web-twig/package.json
Updated `composer.json` was not included when the bump was done.
=> Chore(web-twig): Add changes done by version script to VCS

packages/web/src/scss/components/CheckboxField/_CheckboxField.scss, packages/web/src/scss/components/Header/_Header.scss, packages/web/src/scss/components/RadioField/_RadioField.scss, packages/web/src/scss/components/Stack/_Stack.scss, packages/web/src/scss/components/Tabs/_Tabs.scss, packages/web/src/scss/components/Tabs/_TabsPane.scss, packages/web/src/scss/components/Tabs/index.scss, packages/web/src/scss/components/TextField/_TextField.scss, packages/web/src/scss/components/Tooltip/_Tooltip.scss, packages/web/src/scss/foundation/_box-sizing.scss, packages/web/src/scss/helpers/_text.scss
=> Refactor(web): Improve SCSS coding style and add a comment anytime Stylelint needs to be disabled

.storybook/assets/stylesheets/index.scss, packages/web-react/src/components/Collapse/Collapse.stories.tsx, packages/web-react/src/components/Collapse/Collapse.tsx, packages/web-react/src/components/Collapse/README.md, packages/web-react/src/components/Collapse/__tests__/Collapse.test.tsx, packages/web-react/src/components/Collapse/__tests__/useCollapse.test.ts, packages/web-react/src/components/Collapse/__tests__/useCollapseAriaProps.test.ts, packages/web-react/src/components/Collapse/__tests__/useCollapseStyleProps.test.ts, packages/web-react/src/components/Collapse/__tests__/useResizeHeight.test.ts, packages/web-react/src/components/Collapse/index.ts, packages/web-react/src/components/Collapse/useCollapse.ts, packages/web-react/src/components/Collapse/useCollapseAriaProps.ts, packages/web-react/src/components/Collapse/useCollapseStyleProps.ts, packages/web-react/src/components/Collapse/useResizeHeight.ts, packages/web-react/src/components/index.ts, packages/web-react/src/types/collapse.ts, packages/web-react/src/types/index.ts, packages/web-react/src/types/shared/index.ts
Implementation of Modal component for REACT
1. Component & documentation
=> Feat(web-react): Collapse react implementation #DS-275

packages/web/src/scss/components/Collapse/_Collapse.scss
Fixes for web Collapse linter
- order
- ignored necessary important rule
=> Fix(web): Collapse style linter fix #DS-275

packages/web/src/scss/settings/_utilities.scss
=> Feat(web): Add utility classes for border radius using radii tokens

.github/workflows/test.yaml, .husky/pre-commit, package.json, yarn.lock
* uses pretty-quick library
* @see: https://github.com/azz/pretty-quick
* @see: https://prettier.io/docs/en/precommit.html
=> Chore(repo): Run code formatting as a pre-commit hook (refs #451)

packages/web-twig/.gitattributes
* of the php archive which is downloaded from packagist.org
* @see: https://php.watch/articles/composer-gitattributes
Copied from https://github.com/lmc-eu/twigx-bundle/pull/16
=> Chore(web-twig): Introduce `.gitattributes` to lower download size

.storybook/main.js
* enable lazy loading
* enable code splitting
* enable file system cache
=> Chore(web-react): Speed up Storybook run and build

packages/web-twig/src/Resources/components/Collapse/Collapse.twig, packages/web-twig/src/Resources/components/Collapse/README.md, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseDefault.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseOpened.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseWithParentProp.twig__1.html, packages/web-twig/tests/components-fixtures/collapseDefault.twig, packages/web-twig/tests/components-fixtures/collapseOpened.twig, packages/web-twig/tests/components-fixtures/collapseWithParentProp.twig, packages/web/src/scss/components/Collapse/README.md
- Adding property `data-parent` for Twig implementation of Collapse component, editing documentation.
- Added additional information about switching classes during opening/closing to Web component documentation.
=> Feat(web-twig): Collapse Twig properties updates, tests, documentation

packages/web-react/docs/stories/examples/LoginForm.stories.tsx, packages/web-react/src/components/Accordion/__tests__/Accordion.test.tsx, packages/web-react/src/components/Accordion/__tests__/AccordionItem.test.tsx
Just fixing warnings in eslint :)
=> Chore(web-react): Remove unused variables

packages/icons/scripts/prepareSvgReact.js
=> Fix(icons): Ignore sprite.svg while generating React icon components

packages/web/package.json
This reverts commit 67d900c7df45c601f9a54f0a3a6b1f1342978582.
=> Revert(web): Mark package as side-effect free

packages/web-react/src/components/Collapse/Collapse.tsx, packages/web-react/src/components/Collapse/README.md, packages/web-twig/src/Resources/components/Collapse/Collapse.twig, packages/web-twig/src/Resources/components/Collapse/README.md
* Fixed props for React component, also add in docs
* Fixed props for Twig component, also add in docs
=> Collapse content element props for React and Twig

packages/web-twig/CONTRIBUTING.md, packages/web-twig/src/Resources/components/Icon/Icon.twig
* @see: https://github.com/twigphp/Twig/issues/769
* @see: https://twig.symfony.com/doc/2.x/filters/default.html
* last paragraph tell us that there is unexpected behavior
=> Fix(web-twig): Default filter is not working as expected for false value

packages/web/src/js/dom/index.ts, packages/web/src/js/index.esm.ts, packages/web/src/js/index.umd.ts, packages/web/src/js/utils/index.ts
=> Feat(web): Make `BaseComponent` available for building product design

packages/web-react/README.md
See https://bundlephobia.com/package/@lmc-eu/spirit-web-react
=> Docs(web-react): Introduce Bundlephobia badges about size and deps

.github/workflows/build.yaml, .github/workflows/test.yaml
* building take a long time and we should fail fast with code quality checks
=> Chore(ci): Separate test builds from code quality checks

packages/web-twig/src/Resources/components/Button/Button.twig, packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig, packages/web-twig/src/Resources/partials/inputProps.twig, packages/web-twig/src/Resources/partials/mainProps.twig, packages/web-twig/src/Twig/PropsExtension.php, packages/web-twig/tests/Twig/PropsExtensionTest.php, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonWithMainProps.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldBaseDefault.twig__1.html, packages/web-twig/tests/components-fixtures/buttonWithMainProps.twig, packages/web-twig/tests/components-fixtures/textFieldBaseDefault.twig
Fixing only Button and name attribute - https://jira.lmc.cz/browse/DS-569. But it was not enough.
=> Transferring props through allowed attributes DS-569

packages/web-react/src/components/Button/ButtonLink.tsx, packages/web-react/src/components/Button/__tests__/useButtonStyleProps.test.ts, packages/web-react/src/components/Button/useButtonStyleProps.ts, packages/web-react/src/types/button.ts
=> Special type for React ButtonLink component

packages/web-twig/src/Resources/components/Modal/Modal.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
* these data attributes should not be part of the component
=> Fix(web-twig): Remove `data-component` attribute from Modal

packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx, packages/web-react/src/components/TextFieldBase/__tests__/TextFieldBase.test.tsx
=> Fix(web-react): Add missing id prop for TextFieldBase input element

packages/web/src/scss/components/Collapse/_Collapse.scss, packages/web/src/scss/components/Collapse/_theme.scss, packages/web/src/scss/components/Header/_Header.scss, packages/web/src/scss/components/Header/_theme.scss, packages/web/src/scss/components/Header/_tools.scss, packages/web/src/scss/components/Modal/README.md, packages/web/src/scss/components/Modal/_Modal.scss, packages/web/src/scss/components/Modal/_ModalBody.scss, packages/web/src/scss/components/Modal/_ModalDialog.scss, packages/web/src/scss/components/Modal/_ModalFooter.scss, packages/web/src/scss/components/Modal/_ModalHeader.scss, packages/web/src/scss/components/Modal/_theme.scss, packages/web/src/scss/components/Modal/index.html, packages/web/src/scss/components/Modal/index.scss, packages/web/src/scss/components/RadioField/_RadioField.scss, packages/web/src/scss/components/RadioField/_theme.scss, packages/web/src/scss/components/Tooltip/_Tooltip.scss, packages/web/src/scss/components/Tooltip/_theme.scss, packages/web/src/scss/components/Tooltip/_tools.scss, packages/web/src/scss/foundation/_typography.scss, packages/web/src/scss/settings/_transitions.scss, packages/web/vite.config.ts
- Introduce `Modal` subcomponents #DS-505
- Disable automatic changes of text size in mobile Safari
- Run PostCSS and Autoprefixer also in development mode
---
---
⚠️ Originally the changes have been made against the branch `integration/modal-offcanvas`.
👉🏻 Check the original PR for code review comments: https://github.com/lmc-eu/spirit-design-system/pull/657
=> Introduce `Modal` with subcomponents

packages/web/src/js/BaseComponent.ts, packages/web/src/js/Dropdown.ts, packages/web/src/js/Header.ts, packages/web/src/js/Modal.ts, packages/web/src/js/Tabs.ts, packages/web/src/js/__tests__/Modal.test.ts, packages/web/src/js/dom/SelectorEngine.ts, packages/web/src/js/utils/ComponentFunctions.ts, packages/web/src/js/utils/Elements.ts, packages/web/src/js/utils/__tests__/ComponentFunctions.test.ts, packages/web/src/js/utils/__tests__/index.test.ts, packages/web/src/scss/components/Modal/_Modal.scss
=> Modal JS plugin controls dialog element

packages/web-react/scripts/entryPoints.js, packages/web-react/src/components/Modal/Modal.tsx, packages/web-react/src/components/ModalComposed/ModalComposed.stories.tsx, packages/web-react/src/components/ModalComposed/ModalComposed.tsx, packages/web-react/src/components/ModalComposed/ModalComposedBody.tsx, packages/web-react/src/components/ModalComposed/ModalComposedContext.ts, packages/web-react/src/components/ModalComposed/ModalComposedDialog.tsx, packages/web-react/src/components/ModalComposed/ModalComposedFooter.tsx, packages/web-react/src/components/ModalComposed/ModalComposedHeader.tsx, packages/web-react/src/components/ModalComposed/README.md, packages/web-react/src/components/ModalComposed/__tests__/ModalComposed.test.tsx, packages/web-react/src/components/ModalComposed/__tests__/ModalComposedBody.test.tsx, packages/web-react/src/components/ModalComposed/__tests__/ModalComposedDialog.test.tsx, packages/web-react/src/components/ModalComposed/__tests__/ModalComposedFooter.test.tsx, packages/web-react/src/components/ModalComposed/__tests__/ModalComposedHeader.test.tsx, packages/web-react/src/components/ModalComposed/__tests__/useModalComposedStyleProps.test.ts, packages/web-react/src/components/ModalComposed/index.ts, packages/web-react/src/components/ModalComposed/stories/ModalComposed.tsx, packages/web-react/src/components/ModalComposed/stories/ModalComposedHtml.tsx, packages/web-react/src/components/ModalComposed/stories/ModalComposedProps.tsx, packages/web-react/src/components/ModalComposed/stories/ModalComposedWithLongText.tsx, packages/web-react/src/components/ModalComposed/useModalComposedStyleProps.ts, packages/web-react/src/components/index.ts, packages/web-react/src/hooks/useDeprecatedMessage.ts, packages/web-react/src/types/index.ts, packages/web-react/src/types/modalComposed.ts, packages/web-react/src/types/shared/element.ts, packages/web-react/src/types/shared/index.ts, packages/web-react/src/types/shared/style.ts
* new Modal structure
* Modal
* ModalDialog
* ModalHeader
* ModalBody
* ModalFooter
* ModalContext
* deprecated message with Modal usage
* stories
* tests
* ~~`utility/common` function for random ID, it can be used anywhere (Dropdown, ...)~~
=> Feat(web-react): Introduction ModalComposed component #DS-506

packages/web/src/js/Password.ts
Fixed missing target in event handler
=> Fix(web): Component event handler missing target

packages/web-react/src/components/Icon/README.md
* the link no longer exists
* it was removed in 3b5fd9998318571d0211e210f78edb7ce00e7b9a
=> Docs(web-react): Remove link to detailed information about Icons

packages/web-react/config/webpack.js, packages/web-react/package.json, yarn.lock
* optimization of build and removing unncessary files
* @see: https://unpkg.com/browse/@lmc-eu/spirit-web-react@0.40.0/bundles/
=> Chore(web-react): Remove license file from builded package

docs/DICTIONARIES.md, packages/web-react/src/components/ModalComposed/ModalComposedFooter.tsx, packages/web-react/src/components/ModalComposed/README.md, packages/web-react/src/components/ModalComposed/useModalComposedStyleProps.ts, packages/web-react/src/constants/dictionaries.ts, packages/web-react/src/types/modalComposed.ts, packages/web-react/src/types/shared/dictionaries.ts, packages/web-twig/src/Resources/components/Modal/ModalFooter.twig, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html, packages/web-twig/tests/components-fixtures/modalComposedDefault.twig, packages/web/src/scss/components/Modal/README.md
* dictionaries docs update
* React
* added new value in `types/shared/dictionaries.ts`
* `modalComposed.ts` `align` props
* `ModalComposed/README.md` update
* Twig
* Modal docs update
* Web
* Modal docs update
=> Align dictionaries #DS-628

packages/web-react/src/components/Dropdown/stories/Dropdown.tsx, packages/web-react/src/components/Tooltip/README.md, packages/web-react/src/components/Tooltip/stories/Tooltip.tsx, packages/web-react/src/components/Tooltip/stories/TooltipClickable.tsx, packages/web-react/src/components/Tooltip/stories/TooltipDismissible.tsx, packages/web-react/src/components/Tooltip/stories/TooltipDismissibleFloatingUi.tsx, packages/web-react/src/components/Tooltip/stories/TooltipDismissibleUncontrolled.tsx, packages/web-react/src/components/Tooltip/stories/TooltipFloatingUi.tsx, packages/web-react/src/components/Tooltip/stories/TooltipUncontrolled.tsx
* React
* Replacing `<button>` with `<Button>` in docs and examples
=> Feat(web-react): Button component in docs #DS-598

packages/web-react/src/components/Collapse/Collapse.stories.ts, packages/web-react/src/components/Collapse/stories/CollapseHideOnClose.tsx, packages/web-react/src/components/Collapse/stories/CollapseShowMore.tsx, packages/web-react/src/components/Collapse/stories/CollapseUncontrolledShowMore.tsx
Added example for Controlled Collapse HideOnClose in Storybook
=> Docs(web-react): Collapse example hideOnClose for Storybook

packages/web/src/js/Header.ts, packages/web/src/js/Modal.ts, packages/web/src/js/Offcanvas.ts, packages/web/src/js/utils/ScrollControl.ts, packages/web/src/js/utils/index.ts, packages/web/src/scss/components/Modal/index.html, packages/web/src/scss/helpers/_scroll-control.scss, packages/web/src/scss/helpers/index.scss
* Create a helper class with two functions to save the scrolled position, offset the scrollbar, and check other open dialogs. It has been applied to these components:
* `packages/web/src/js/Header.ts`
* `packages/web/src/js/Modal.ts`
* `packages/web/src/js/Offcanvas.ts`
* Creating an example for a composite Modal in Modal
=> Feat(web): Prevent scrolling while the dialog is open #DS-191

packages/web/assets/demo.css, packages/web/src/scss/components/Header/_Header.deprecated.scss, packages/web/src/scss/components/Header/_tools.scss, packages/web/src/scss/components/Pagination/_Pagination.scss, packages/web/src/scss/components/Tabs/_Tabs.scss, packages/web/src/scss/components/TextArea/index.html, packages/web/src/scss/components/TextField/index.html, packages/web/src/scss/foundation/_links.scss, packages/web/src/scss/helpers/_links.scss, packages/web/src/scss/helpers/index.html
=> Feat(web): Add feature class to make links correctly underlined #DS-516

packages/web-twig/composer.json, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textAreaDefault.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textAreaWithHelperText.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldBaseMultiline.twig__1.html, packages/web-twig/tests/components-fixtures/buttonWithDisabledFalseDefault.twig, packages/web-twig/tests/components-fixtures/buttonWithDisabledFalsePropDefault.twig, packages/web-twig/tests/components-fixtures/modalComposedDefault.twig
=> Deps(web-twig): Freeze TwigX version until we fix the parsing regexp

packages/web-twig/src/Resources/components/Button/Button.stories.twig, packages/web-twig/src/Resources/components/Button/stories/ButtonColorsSizes.twig, packages/web-twig/src/Resources/components/Button/stories/ButtonDisabled.twig
=> Docs(web-twig): Introduce Button story

packages/web/src/scss/components/FileUploader/README.md, packages/web/src/scss/components/FileUploader/_FileUploader.scss, packages/web/src/scss/components/FileUploader/_FileUploaderAttachment.scss, packages/web/src/scss/components/FileUploader/_FileUploaderInput.scss, packages/web/src/scss/components/FileUploader/_FileUploaderList.scss, packages/web/src/scss/components/FileUploader/_theme.scss, packages/web/src/scss/components/FileUploader/index.html, packages/web/src/scss/components/FileUploader/index.scss, packages/web/src/scss/components/index.scss, packages/web/src/scss/foundation/_links.scss, packages/web/src/scss/helpers/_links.scss, packages/web/src/scss/settings/_links.scss, packages/web/src/scss/tools/_form-fields.scss
=> Feat(web): Introduce `FileUploader` component #DS-664

packages/web-twig/src/Resources/components/Button/Button.twig, packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig, packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig, packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig, packages/web-twig/src/Resources/components/Link/Link.twig
* condition should not be same as `error` value
* removed doubled deprecations
=> Fix(web-twig): Condition for onClick deprecation

package.json
Affects https://github.com/lmc-eu/spirit-design-system/actions/runs/4725682946/jobs/8384491838#step:6:428
Just going around 🤷
=> Chore(ci): Ignore demo package from CI builds

.github/workflows/test.yaml, apps/web-twig-demo/assets/app.js, apps/web-twig-demo/package.json, yarn.lock
* ignore unresolved import
* will be fixed in https://github.com/lmc-eu/spirit-design-system/pull/811
=> Deps(demo): Upgrade @lmc-eu/spirit-web to 0.45.0

packages/web/src/js/FileUploader.ts, packages/web/src/js/__tests__/FileUploader.test.ts, packages/web/src/js/index.esm.ts, packages/web/src/js/index.umd.ts, packages/web/src/scss/components/FileUploader/README.md, packages/web/src/scss/components/FileUploader/index.html
* Prepared basic file upload functionality
* Prepared API callback for displaying the list of the queue and deleting it as well
* Updated examples
* Updated documentation
* Add tests
* ~~What will happen to the list if it is not inserted? Wouldn't it be better to insert it automatically?~~
* ~~How will it be with validation messages? If I upload a file, I might get a notification that the file has exceeded the maximum size or does not match the allowed types.~~
* ~~So how about validation?~~
* onDrop Validation https://jira.lmc.cz/browse/DS-724
=> Feat(web): Introduction of JS for FileUploader component #DS-682

Makefile, apps/web-twig-demo/.gitignore, apps/web-twig-demo/assets/app.js, apps/web-twig-demo/assets/app.ts, apps/web-twig-demo/assets/styles/app.scss, apps/web-twig-demo/docker/docker-compose.override.yml, apps/web-twig-demo/docker/docker-compose.prod.yml, apps/web-twig-demo/docker/docker-compose.yml, apps/web-twig-demo/package.json, apps/web-twig-demo/tsconfig.json, apps/web-twig-demo/webpack.config.js, apps/web-twig-demo/yarn.lock, lerna.json, package.json, packages/web-twig/Makefile, yarn.lock
Rebuild your images using `make build` and then using `make start` you should make the whole dev environment up and running. This also solves the problem with the `core-js` polyfills (@adamkudrna).
Into the Node container are mounted the demo app and the web package.
Into the PHP container are mounted the demo app and the web-twig package.
Please let me know if all works fine.
=> Local development Node image for web-twig-demo

packages/web-react/src/components/FileUploader/FileUploader.stories.ts, packages/web-react/src/components/FileUploader/FileUploaderInput.tsx, packages/web-react/src/components/FileUploader/README.md, packages/web-react/src/components/FileUploader/UncontrolledFileUploader.stories.tsx, packages/web-react/src/components/FileUploader/UncontrolledFileUploader.tsx, packages/web-react/src/components/FileUploader/__tests__/useFileUploaderStyleProps.test.ts, packages/web-react/src/components/FileUploader/stories/FileUploaderDismissible.tsx, packages/web-react/src/components/FileUploader/stories/FileUploaderUncontrolledDismissible.tsx, packages/web-react/src/components/FileUploader/stories/FormWithFileUploader.tsx, packages/web-react/src/components/FileUploader/stories/FormWithUncontrolledFileUploader.tsx, packages/web-react/src/components/FileUploader/stories/argTypesUncontrolled.ts, packages/web-react/src/components/FileUploader/useFileUploaderInput.ts, packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts, packages/web-react/src/types/fileUploader.ts, packages/web-twig/src/Resources/components/FileUploader/FileUploaderInput.twig, packages/web-twig/src/Resources/components/FileUploader/README.md, packages/web-twig/src/Resources/components/FileUploader/stories/FileUploaderWithControlledQueue.twig, packages/web/src/js/FileUploader.ts, packages/web/src/js/__tests__/FileUploader.test.ts, packages/web/src/scss/components/FileUploader/README.md, packages/web/src/scss/components/FileUploader/index.html
The branch is based on main, but there are two branches rebased with modifications #817 and #825 
* Web package ✅
* Twig package ✅
* React package ✅
=> Hiding input when the queue is full #DS-730

.storybook/assets/stylesheets/index.scss, packages/web-react/scripts/entryPoints.js, packages/web-react/src/components/ScrollView/README.md, packages/web-react/src/components/ScrollView/ScrollView.stories.ts, packages/web-react/src/components/ScrollView/ScrollView.tsx, packages/web-react/src/components/ScrollView/__tests__/ScrollView.test.tsx, packages/web-react/src/components/ScrollView/__tests__/useScrollViewStyleProps.test.ts, packages/web-react/src/components/ScrollView/constants.ts, packages/web-react/src/components/ScrollView/index.ts, packages/web-react/src/components/ScrollView/stories/ScrollView.tsx, packages/web-react/src/components/ScrollView/stories/ScrollViewHorizontal.tsx, packages/web-react/src/components/ScrollView/stories/ScrollViewScrollbarDisabled.tsx, packages/web-react/src/components/ScrollView/stories/argTypes.ts, packages/web-react/src/components/ScrollView/useScrollPosition.ts, packages/web-react/src/components/ScrollView/useScrollViewStyleProps.ts, packages/web-react/src/components/index.ts, packages/web-react/src/constants/alignment.ts, packages/web-react/src/constants/direction.ts, packages/web-react/src/constants/index.ts, packages/web-react/src/types/index.ts, packages/web-react/src/types/scrollView.ts, packages/web-react/src/types/shared/alignments.ts, packages/web-react/src/types/shared/dictionaries.ts, packages/web-react/src/types/shared/directions.ts, packages/web-react/src/types/shared/index.ts, packages/web-react/src/utils/debounce.ts, packages/web-react/src/utils/index.ts
=> Feat(web-react): Introduce ScrollView component #DS-464

packages/web-react/src/components/CheckboxField/CheckboxField.tsx, packages/web-react/src/components/CheckboxField/README.md, packages/web-react/src/components/RadioField/README.md, packages/web-react/src/components/RadioField/RadioField.tsx, packages/web-react/src/types/checkboxField.ts, packages/web-react/src/types/radioField.ts, packages/web-react/src/types/shared/element.ts, packages/web-react/src/types/textArea.ts, packages/web-react/src/types/textField.ts
* Added option for Checkbox and Radio to pass React reference to input element
* Created types for Input and TextArea with Reference
=> Feat(web-react): CheckboxField and RadioField reference element feature

packages/web-react/src/components/Link/Link.tsx, packages/web-react/src/components/Link/README.md, packages/web-react/src/components/Link/useLinkStyleProps.ts, packages/web-react/src/components/Tag/README.md, packages/web-react/src/components/Tag/Tag.tsx, packages/web-react/src/types/link.ts, packages/web-react/src/types/tag.ts
* Added option for Link and Tag to pass React reference to their element
=> Feat(web-react): Link and Tag reference polymorph element feature

packages/web-twig/src/Resources/components/Select/README.md, packages/web-twig/src/Resources/components/Select/Select.stories.twig, packages/web-twig/src/Resources/components/Select/Select.twig, packages/web-twig/src/Resources/components/Select/stories/Select.twig, packages/web-twig/src/Resources/components/Select/stories/SelectDisabled.twig, packages/web-twig/src/Resources/components/Select/stories/SelectFluid.twig, packages/web-twig/src/Resources/components/Select/stories/SelectHelperText.twig, packages/web-twig/src/Resources/components/Select/stories/SelectLabelHidden.twig, packages/web-twig/src/Resources/components/Select/stories/SelectValidationState.twig, packages/web-twig/src/Resources/twig-components/select.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectDefault.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectDisabled.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectFluid.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectHelperText.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectLabelHidden.twig__1.html, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectValidationState.twig__1.html, packages/web-twig/tests/components-fixtures/selectDefault.twig, packages/web-twig/tests/components-fixtures/selectDisabled.twig, packages/web-twig/tests/components-fixtures/selectFluid.twig, packages/web-twig/tests/components-fixtures/selectHelperText.twig, packages/web-twig/tests/components-fixtures/selectLabelHidden.twig, packages/web-twig/tests/components-fixtures/selectValidationState.twig
=> Feat(web-twig): Introduce Select component #DS-790

packages/web-react/docs/stories/examples/ModalComposedWithScrollView.stories.tsx, packages/web-twig/src/Resources/components/Modal/stories/ModalBasic.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalStacked.twig, packages/web/src/scss/components/Modal/README.md, packages/web/src/scss/components/Modal/_ModalBody.scss, packages/web/src/scss/components/Modal/_ModalDialog.scss, packages/web/src/scss/components/Modal/_theme.scss, packages/web/src/scss/components/Modal/index.html, packages/web/src/scss/components/ScrollView/_ScrollView.scss
- Demonstrate the composition of `Modal` and `ScrollView`
- web
- Twig
- React
- Twig: Remove unnecessary structural comments from `Modal` demos
=> Demonstrate composition of `Modal` with `ScrollView`

packages/web-twig/src/Resources/components/Modal/Modal.stories.twig, packages/web-twig/src/Resources/components/Modal/ModalDialog.twig, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/src/Resources/components/Modal/stories/ModalBasic.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalStacking.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html, packages/web-twig/tests/components-fixtures/modalComposedDefault.twig
New API options:
- `maxHeightFromTabletUp`
- `preferredHeightOnMobile`
- `preferredHeightFromTabletUp`
=> Feat(web-twig): Make the preferred height and max height of `Modal` customizable #DS-723

package.json, yarn.lock
* needed by storybook-addon-html for syntax highlighting
=> Chore(repo): Add missing dependency `react-syntax-higlighter`

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
* @see: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
refs #DS-473, #383
Creating a PR template to help us write a better description for our PRs. :-)
=> Chore(repo): Introduce pull request template

packages/web-react/docs/stories/examples/ModalComposedWithScrollView.stories.tsx, packages/web-react/src/components/ScrollView/README.md, packages/web-react/src/components/ScrollView/ScrollView.tsx, packages/web-react/src/components/ScrollView/__tests__/useScrollViewStyleProps.test.ts, packages/web-react/src/components/ScrollView/constants.ts, packages/web-react/src/components/ScrollView/stories/argTypes.ts, packages/web-react/src/components/ScrollView/useScrollViewStyleProps.ts, packages/web-react/src/types/scrollView.ts, packages/web-twig/src/Resources/components/ScrollView/README.md, packages/web-twig/src/Resources/components/ScrollView/ScrollView.stories.twig, packages/web-twig/src/Resources/components/ScrollView/ScrollView.twig, packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewOverflowDecorators.twig, packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set scrollViewDefault.twig__1.html, packages/web-twig/tests/components-fixtures/scrollViewDefault.twig, packages/web/src/scss/components/Modal/README.md, packages/web/src/scss/components/Modal/index.html, packages/web/src/scss/components/ScrollView/README.md, packages/web/src/scss/components/ScrollView/_ScrollView.scss, packages/web/src/scss/components/ScrollView/index.html
Please see also commit messages. I tried to introduce some BC commit message template with a migration guide.
=> BREAKING CHANGE: Rename ScrollView `indicators` to `overflowDecorators` #DS-825

packages/web-react/docs/stories/examples/ModalComposedStacked.stories.tsx, packages/web-react/src/components/ModalComposed/README.md, packages/web-react/src/hooks/useClickOutside.ts
* Sample of composite modals
* useClickOutside checks clickable element
=> Fix(web-react): Stacked Modal Composed closes both dialog #DS-740

.github/CODEOWNERS
=> Chore(repo): Remove Tomas Sychra and add Pavel Klibani to codeowners

packages/web/src/scss/components/FileUploader/_FileUploaderAttachment.scss, packages/web/src/scss/components/FileUploader/_theme.scss
Add padding to FileUploaderInput and FileUploaderAttachment
#DS-859
---
=> Feat(web): Unify FileUploaderInput and Attachment paddings with design 

apps/web-twig-demo/assets/app.ts, packages/web-twig/src/Resources/components/FileUploader/stories/FileUploaderExampleOfJSControlledForm.twig
* the script is now available through webpack build of demo app
refs #DS-831
---
=> Refactor(web-twig): Move FileUploader form demo script to Demo App

.github/PULL_REQUEST_TEMPLATE.md
Fixed typo in link based on https://github.com/lmc-eu/spirit-design-system/actions/runs/5621244920/job/15231692222
---
=> Chore(ci): Fix typo in PR template links to contributing documentation

README.md
Add missing package to the table with provided packages in main readme.
---
=> Docs(repo): Introduce form validations package in main README file

packages/web-twig/src/Resources/components/Select/Select.stories.twig, packages/web-twig/src/Resources/components/Select/stories/SelectFluid.twig, packages/web/src/scss/components/FieldGroup/README.md, packages/web/src/scss/components/FieldGroup/_FieldGroup.scss, packages/web/src/scss/components/FieldGroup/_theme.scss, packages/web/src/scss/components/FieldGroup/index.html, packages/web/src/scss/components/FieldGroup/index.scss, packages/web/src/scss/components/Select/index.html, packages/web/src/scss/components/index.scss
- **Introduce FieldGroup component**
- Showcase the fluid variant of `Select` in `web` and `web-twig` docs
---
---
📋  https://jira.lmc.cz/browse/DS-855
=> Feat(web): Introduce `FieldGroup` component #DS-855

.github/workflows/test-web-twig.yaml
* and use builded icons for testing
---
=> Chore(ci): Build icons before testing web-twig package

lerna.json
* @see https://github.com/lerna/lerna/tree/main/libs/commands/version #--create-release-type
---
=> Chore(repo): Automatically create GitHub release when creating version

packages/web-react/docs/stories/examples/FileUploaderWithImagePreview.stories.tsx
Update storybook composition demo for uploading image with modal image preview.
---
=> Docs(web-react): FileUploader Storybook composition demo

packages/web-react/docs/stories/examples/LoginForm.stories.tsx, packages/web-react/docs/stories/examples/ModalStacked.stories.tsx
* forgotten to aplied changes after removing version 1 deprecations
---
=> Docs(web-react): Rename components in example compositions

packages/web-twig/src/Resources/components/Accordion/README.md, packages/web-twig/src/Resources/components/Collapse/README.md, packages/web-twig/src/Resources/components/Dropdown/README.md, packages/web-twig/src/Resources/components/FileUploader/README.md, packages/web-twig/src/Resources/components/Header/README.md, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/src/Resources/components/ScrollView/README.md, packages/web-twig/src/Resources/components/Tabs/README.md, packages/web-twig/src/Resources/components/TextArea/README.md, packages/web-twig/src/Resources/components/TextField/README.md, packages/web-twig/src/Resources/components/Tooltip/README.md, packages/web/src/scss/components/TextField/README.md
=> Docs(web-twig): Highlight and unify links to Web package JS plugin documentations 

packages/web-twig/CONTRIBUTING.md
Adding web-twig demo app showcase localhost URL to the contributing document.
It was missing while @pavelklibani try to run the app.
---
=> Docs(web-twig): Introduce showcase app localhost url

packages/web-twig/CONTRIBUTING.md
https://jira.lmc.cz/browse/DS-636
---
=> Docs(web-twig): Introduce section about snapshot tests

packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig, packages/web-twig/src/Resources/components/Header/_abstracts/Element.twig, packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
[I walked around](https://github.com/lmc-eu/spirit-design-system/pull/990/files#diff-c3ca80c4a6e6d51e987124ce945d2fcb8ad6523f1521ae65babf9a68504e763e). 🚶‍♀️
=>  Fix(web-twig): Deprecate `class` prop in the `Header` abstract components

packages/web-react/scripts/entryPoints.js, packages/web-react/src/components/VisuallyHidden/README.md, packages/web-react/src/components/VisuallyHidden/VisuallyHidden.tsx, packages/web-react/src/components/VisuallyHidden/__tests__/VisuallyHidden.test.tsx, packages/web-react/src/components/VisuallyHidden/index.ts, packages/web-react/src/components/VisuallyHidden/useVisuallyHiddenProps.ts, packages/web-react/src/components/index.ts, packages/web-react/src/types/index.ts, packages/web-react/src/types/visuallyHidden.ts, packages/web-twig/src/Resources/components/VisuallyHidden/README.md, packages/web-twig/src/Resources/components/VisuallyHidden/VisuallyHidden.twig, packages/web-twig/src/Resources/components/VisuallyHidden/__tests__/VisuallyHiddenSnapshotTest.php, packages/web-twig/src/Resources/components/VisuallyHidden/__tests__/__fixtures__/visuallyHiddenDefault.twig, packages/web-twig/src/Resources/components/VisuallyHidden/__tests__/__snapshots__/visuallyHiddenDefault.twig.snap.html, packages/web-twig/src/Resources/twig-components/visuallyHidden.twig
Introduce new `VisuallyHidden` component in react and twig.
[Visually Hidden komponenta](https://jira.lmc.cz/browse/DS-867)
=> Feat(web-react, web-twig): VisuallyHidden component #DS-867

packages/web-react/docs/DocsBox.tsx, packages/web-react/src/components/Container/demo/ContainerDefault.tsx, packages/web-react/src/components/Container/demo/index.tsx
Container demo in web-react is now same as demo in web and web-twig
[Demo: Container má ve všech technologiích stejná dema](https://jira.lmc.cz/browse/DS-894)
=> Docs(web-react): Add Container demo #DS-894

packages/web/src/js/FileUploader.ts
Drag and drop was not working in web and web-twig
[Drag and Drop in web&web-twig](https://jira.lmc.cz/browse/DS-938)
=> Fix(web): FileUploader drag and drop fix #DS-938

packages/web-react/docs/stories/examples/ModalWithScrollView.stories.tsx, packages/web-react/src/components/Modal/README.md, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
https://jira.lmc.cz/browse/DS-876
=> Docs(web-twig, web-react): Improve `Modal` documentation regarding `ScrollView` and optional title

packages/web-react/src/components/Header/demo/HeaderExperimentalRTL.tsx, packages/web-react/src/components/Header/demo/HeaderInvertedWithActions.tsx, packages/web-react/src/components/Header/demo/HeaderInvertedWithActionsAndDialog.tsx, packages/web-react/src/components/Header/demo/HeaderMinimalInverted.tsx, packages/web-react/src/components/Header/demo/HeaderSimpleInverted.tsx, packages/web-react/src/components/Header/demo/HeaderSimpleTransparent.tsx, packages/web-react/src/components/Header/demo/index.tsx, packages/web/src/scss/components/Header/index.html
Header demo in web-react is now same as demo in web and web-twig
[Demo: Header má ve všech technologiích stejná dema](https://jira.lmc.cz/browse/DS-898)
=> Docs(web-react): Add Header demo #DS-898

packages/web-react/src/components/Modal/ModalCloseButton.tsx, packages/web-react/src/components/Modal/ModalHeader.tsx, packages/web-react/src/types/modal.ts
=> Refactor(web-react): Introduce `ModalCloseButton` component

packages/web-react/.eslintignore
* running ESLint took so long on local machine
---
=> Style(web-react): Ignore `build` directory from linting

packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/web-react/src/components/Breadcrumbs/BreadcrumbsItem.tsx, packages/web-react/src/components/Breadcrumbs/README.md, packages/web-react/src/components/Breadcrumbs/__tests__/BreadcrumbsItem.test.tsx, packages/web-react/src/components/Breadcrumbs/demo/BreadcrumbsCurrentWithoutLink.tsx, packages/web-react/src/components/Breadcrumbs/demo/index.tsx, packages/web-react/src/types/breadcrumbs.ts, packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.stories.twig, packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.twig, packages/web-twig/src/Resources/components/Breadcrumbs/BreadcrumbsItem.twig, packages/web-twig/src/Resources/components/Breadcrumbs/README.md, packages/web-twig/src/Resources/components/Breadcrumbs/stories/BreadcrumbsCurrentWithoutLink.twig, packages/web/src/scss/components/Breadcrumbs/index.html
=> Feat: Make BreadcrumbsItem href optional #DS-957

packages/web-twig/docs/components/DocsSection/DocsSection.twig, packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDisabledBackdropClick.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalDisabledBackdropClick.twig
=> Fix(web-twig): Use embed in DocsSection to fix falling tests with unclosed block

package.json, yarn.lock
* Could not find 'nx' module in this workspace.
* Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
---
=> Chore: Add @nrwl/cli to fix running tasks on local environment

packages/web-react/config/jest/config.js
=> Test(web-react): Ignore demo files from code coverage reports

packages/web-react/src/components/FileUploader/useFileUploaderAttachment.ts
=> Fix(web-react): FileUploader hidden input were not added without meta

packages/web/src/scss/foundation/_tokens.scss, packages/web/src/scss/foundation/index.scss
=> Feat(web): Add breakpoint tokens to root CSS variables

.github/workflows/supernova.yaml
Publish our documentation in Supernovat on every push to main branch 🎉 
https://github.com/Supernova-Studio/cli
---
=> Chore(ci): Introduce Supernova documentation publishing

.github/workflows/supernova.yaml
=> Chore(ci): Remove condition for refs/tags on Supernova workflow

.github/workflows/component-analysis.yaml
* cause exceeding of component analysis limit
---
=> Chore(ci): Disable component analysis on every push to main

yarn.lock
=> Chore(repo): Update lockfile

nx.json, package.json, yarn.lock
* we have reached free plan, which ends on 300 executions and we are on more than 500 executions per month
---
=> Chore(ci): Disable Nx cloud cache for CI runs

.omletrc.js
https://docs.omlet.dev/cli/config-file
---
=> Chore(repo): Introduce Omlet analysis config file

packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
=> Fix(web-react): Mock window.scrollTo  in test of useScrollControl hook

.eslintrc.js, exporters/js/package.json, exporters/scss/package.json, packages/analytics/package.json, packages/design-tokens/package.json, packages/form-validations/package.json, packages/web/package.json, yarn.lock
Updating dependencies partialy.
https://github.com/lmc-eu/spirit-design-system/pull/1181
---
=> Deps: Update all non-major dependencies

Makefile, bin/make/e2e.sh
refs #DS-1094
Added additional commands to Makefile for updating snapshots and running end-to-end tests.
https://jira.lmc.cz/browse/DS-1094
---
=> Test(repo): Introduce commands for updating E2E tests

yarn.lock
=> Deps: Update browserslist database

packages/web-react/config/rollup.config.js, packages/web-react/src/components/Dropdown/Dropdown.tsx, packages/web-react/src/hooks/useIsomorphicLayoutEffect.ts, packages/web-react/src/types/header.ts, packages/web-react/src/types/item.ts, packages/web-react/src/types/shared/element.ts, packages/web-react/src/types/tabs.ts, packages/web-react/src/utils/string.ts, packages/web/.eslintignore, packages/web/src/js/utils/__tests__/Config.test.ts, packages/web/tests/scss.test.ts
=> Upgrade CQT and fix some lint errors

packages/web/CONTRIBUTING.md
=> Docs(web): Record our convention for CSS and JS selectors to avoid confusion

docs/DICTIONARIES.md, packages/web-react/src/components/Tooltip/demo/TooltipPlacements.tsx, packages/web-react/src/components/Tooltip/useTooltipStyleProps.ts, packages/web-react/src/constants/dictionaries.ts
=> Feat(web-react): Deprecate non-flow-relative Tooltip placements #DS-1085

apps/web-twig-demo/docker/docker-compose.override.yml, packages/web-twig/Makefile
* fixing `cannot find module error`
---
=> Chore(demo): Add missing links for missing modules

packages/web-twig/README.md, packages/web-twig/src/Resources/components/Button/stories/ButtonColorsSizes.twig, packages/web-twig/src/Resources/components/Button/stories/ButtonDisabled.twig, packages/web-twig/src/Resources/components/Button/stories/ButtonLoading.twig, packages/web-twig/src/Resources/components/ButtonLink/stories/ButtonLinkColorsSizes.twig, packages/web-twig/src/Resources/components/ButtonLink/stories/ButtonLinkDisabled.twig, packages/web-twig/src/Resources/components/Dropdown/stories/DropdownPlacements.twig, packages/web-twig/src/Resources/components/Header/stories/HeaderSimpleTransparent.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig, packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewHorizontalBreakout.twig, packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewOverflowDecorators.twig, packages/web-twig/src/Resources/components/Tooltip/stories/TooltipOnHover.twig, packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig, packages/web-twig/src/Resources/icons/Icons.stories.twig, packages/web-twig/src/Twig/PropsExtension.php, packages/web-twig/tests/Twig/PropsExtensionTest.php
=> Feat(web-twig): Introduce spacing style props to all components #DS-1109

.github/workflows/build.yaml
Test builds also on Node.js v20.
https://jira.lmc.cz/browse/DS-809
---
=> Chore(ci): Test builds also on Node.js v20

.gitignore
Based on this https://github.com/lmc-eu/spirit-design-system/pull/1237/commits/dec2162391706548335fa94aa7d4bcdd89a4a31c
---
=> Chore(repo): Ignore Nx cache files by Git

packages/web/src/scss/components/Accordion/_Accordion.scss, packages/web/src/scss/components/Accordion/_theme.scss, packages/web/src/scss/components/Checkbox/_Checkbox.scss, packages/web/src/scss/components/Item/_Item.scss, packages/web/src/scss/components/Item/_theme.scss, packages/web/src/scss/components/Radio/_Radio.scss, packages/web/src/scss/theme/_form-fields.scss, packages/web/src/scss/tools/_form-fields.scss
…ffset #DS-782
Only where it makes sense.
---
=> Feat(web): Unify naming in SCSS, use padding or gap #DS-782

packages/web-react/docs/stories/examples/ModalStacked.stories.tsx, packages/web-react/docs/stories/examples/ModalWithAccordion.stories.tsx, packages/web-react/docs/stories/examples/ModalWithCollapse.stories.tsx, packages/web-react/docs/stories/examples/ModalWithDropdown.stories.tsx, packages/web-react/docs/stories/examples/ModalWithForm.stories.tsx, packages/web-react/docs/stories/examples/ModalWithScrollView.stories.tsx, packages/web-react/src/components/Modal/README.md, packages/web-react/src/components/Modal/demo/ModalStacked.tsx, packages/web-twig/src/Resources/components/Modal/README.md, packages/web/src/scss/components/Item/README.md, packages/web/src/scss/components/Modal/_Modal.scss
Fix minor documentation issues introduced in #1260.
=> Docs(web): Fix Sass implementation notes

.github/PULL_REQUEST_TEMPLATE.md
* as we agreed in our meeting this information is targetting the external contributtors
* since we are developping the desing system ourselves now and there is no contributtor
outside of the company the information is useless for us
* but we should keep in mind that the rules are same for both us and contributors
I have just commented this in the place where it is. I was expecting that we would not want to skip all the text in the header of the PR template and scroll down to begin writing the description.
=> Docs(repo): Comment info for contributors in PR template

README.md
=> Docs(readme): Add `codemods` to package table in root readme

packages/web-twig/DEPRECATIONS-v3.md
=> Docs(web-twig): List Deprecations in the web twig package #DS-1148

packages/web/src/scss/foundation/_tokens.scss
=> Feat(web): Print all design tokens as CSS root variables #DS-1200

.github/workflows/e2e.yml, apps/demo/netlify.toml
=> Chore(ci): Fix usage of env variables in e2e pipeline

.gitignore, apps/storybook/package.json, yarn.lock
=> Update lockfile after Storybook move

.github/workflows/test-web-twig.yaml, apps/web-twig-demo/composer.json, apps/web-twig-demo/composer.lock, apps/web-twig-demo/docker/Dockerfile
Partial upgrade of the PHP in the web-twig-demo app. Jobs are now using PHP v8 so we can go up as well.
Only the PHP version updated. With the Symfony version, we can go up separately.
Also, renamed the package from a skeleton in `composer.json`.
https://jira.almacareer.tech/browse/DS-1212
=> web-twig-demo: Update PHP version to v8

LICENSE.md, README.md, exporters/js/LICENSE.md, exporters/js/README.md, exporters/scss/LICENSE.md, exporters/scss/README.md, exporters/svg/LICENSE.md, packages/analytics/LICENSE.md, packages/common/LICENSE.md, packages/design-tokens/LICENSE.md, packages/form-validations/LICENSE.md, packages/icons/LICENSE.md, packages/web-react/LICENSE.md, packages/web-react/README.md, packages/web-twig/README.md, packages/web/LICENSE.md
Starting 2024 our company is now known as Alma Career and LMC is a history.
---
=> Docs(repo): Rebrand to Alma Career

packages/web/src/scss/components/Modal/README.md, packages/web/src/scss/components/Modal/_ModalBody.scss, packages/web/src/scss/components/Modal/_ModalDialog.scss, packages/web/src/scss/components/Modal/index.html
https://jira.almacareer.tech/browse/DS-939
=> Fix(web): `Dropdown` can be placed in non-scrollable `Modal` #DS-939

packages/web-react/src/components/Modal/README.md, packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
Follows PR #1332 
https://jira.almacareer.tech/browse/DS-939
=> Fix(web-react): `Dropdown` can now be placed inside a non-scrollable `Modal` #DS-939

CONTRIBUTING.md
* @see: https://gist.github.com/adamkudrna/694f3048c1338f07375b9b8af24afe2f
* Many thanks to @adamkudrna
https://jira.lmc.cz/browse/DS-611
---
=> Docs(ci): Introduce manual testing section with Netlify links tweak

.prettierignore, nx.json, package.json, packages/form-validations/package.json, packages/web-react/package.json, packages/web/package.json, yarn.lock
* modified configurations were outdated
---
=> Repair Lerna/Nx configuration

packages/web-react/DEPRECATIONS-v2.md, packages/web-react/src/components/Alert/Alert.tsx, packages/web-react/src/components/Alert/README.md, packages/web-react/src/components/Alert/__tests__/useAlertIcon.test.ts, packages/web-react/src/hooks/useIcon.ts
[Odstranit deprekaci danger ikonky v Alertu](https://jira.almacareer.tech/browse/DS-1194)
=> BREAKING CHANGE(web-react): Remove `Alert` danger icon deprecation

.github/CODEOWNERS
=> Chore(repo): Introduce Jakub Curda to the codeowners

packages/web/DEPRECATIONS-v2.md, packages/web/src/scss/components/Dropdown/README.md, packages/web/src/scss/components/Dropdown/_Dropdown.scss
See the Dropdown: Combined Placements section in the web package Migration Guide to version 2.
=> BREAKING CHANGE(web): Remove Dropdown combined placement classes #DS-1139

packages/form-validations/README.md
=> Docs(form-validations): Fix typo in a destroy function

apps/demo/partials/header.hbs, apps/demo/partials/layout/base.hbs
=> Chore(repo): Fix title package name check

apps/web-twig-demo/composer.lock, packages/web-twig/README.md, packages/web-twig/composer.json
=> BREAKING CHANGE: Remove dependency twig/twig for v1

packages/web-react/DEPRECATIONS-v2.md, packages/web-react/src/components/Dropdown/demo/DropdownFullwidthAll.tsx, packages/web-react/src/components/Dropdown/demo/DropdownFullwidthMobileOnly.tsx, packages/web-react/src/components/Dropdown/demo/UncontrolledDropdown.tsx, packages/web-react/src/components/Dropdown/stories/UncontolledDropdown.stories.tsx, packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts, packages/web-react/src/components/Tooltip/useTooltipStyleProps.ts, packages/web-react/src/components/TooltipModern/demo/TooltipPlacements.tsx, packages/web-react/src/constants/dictionaries.ts, packages/web-twig/DEPRECATIONS-v3.md, packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig, packages/web-twig/src/Resources/components/Dropdown/README.md, packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig, packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig, packages/web/DEPRECATIONS-v2.md, packages/web/src/scss/components/Dropdown/README.md, packages/web/src/scss/components/Tooltip/README.md, packages/web/src/scss/settings/_dictionaries.scss, packages/web/src/scss/tools/__tests__/_dictionaries.test.scss, packages/web/src/scss/tools/__tests__/_placement.test.scss, packages/web/src/scss/tools/__tests__/_string.test.scss, packages/web/src/scss/tools/_dictionaries.scss, packages/web/src/scss/tools/_placement.scss, packages/web/src/scss/tools/_string.scss
=> BREAKING CHANGE: Remove Dropdown and Tooltip non-flow-relative placements #DS-1138

apps/web-twig-demo/assets/scripts/toast-dynamic.ts, apps/web-twig-demo/yarn.lock, packages/web-twig/src/Resources/components/Toast/stories/ToastDynamicToastQueue.twig, packages/web/src/js/Toast.ts, packages/web/src/js/__tests__/Toast.test.ts, packages/web/src/scss/components/Toast/_Toast.scss, packages/web/src/scss/components/Toast/dynamic-toast.mjs, packages/web/src/scss/components/Toast/index.html
=> Feat: Introduce bulk `Toast` queue clearing #DS-1222

.commitlintrc.js
The commitlint is raising warning about this.
=> Style(repo): Introduce missing `codemods` commit scope

packages/web/src/scss/tools/__tests__/_accessibility.test.scss, packages/web/src/scss/tools/__tests__/_breakpoint.test.scss, packages/web/src/scss/tools/__tests__/_dictionaries.test.scss, packages/web/src/scss/tools/__tests__/_form-fields.test.scss, packages/web/src/scss/tools/__tests__/_links.test.scss, packages/web/src/scss/tools/__tests__/_list.test.scss, packages/web/src/scss/tools/__tests__/_placement.test.scss, packages/web/src/scss/tools/__tests__/_reset.test.scss, packages/web/src/scss/tools/__tests__/_string.test.scss, packages/web/src/scss/tools/__tests__/_svg.test.scss, packages/web/src/scss/tools/__tests__/_typography.test.scss, packages/web/src/scss/tools/__tests__/_utilities.test.scss
=> Test(web): Remove unnecessary stylelint disable and rename sass-true module

packages/codemods/README.md, packages/codemods/src/transforms/v2/web-react/README.md
=> Docs(codemods): Add list of all current codemods we have #DS-1214

apps/web-twig-demo/templates/validations.html.twig, packages/form-validations/index.html
=> Fix(form-validations): Use GridItem instead of GridSpan in demo #DS-1279

docs/migrations/web-twig/MIGRATION-v3.md, packages/web-twig/DEPRECATIONS-v3.md, packages/web-twig/src/Resources/components/Modal/Modal.stories.twig, packages/web-twig/src/Resources/components/Modal/ModalDialog.twig, packages/web-twig/src/Resources/components/Modal/README.md, packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig, packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html, packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig, packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig, packages/web/src/scss/components/Modal/index.html
=> BREAKING CHANGE(web-twig): Turn off scrolling inside ModalDialog by default #DS-1184

.lintstagedrc.mjs, .prettierignore, packages/web-twig/Makefile
Not all dependencies in web-twig docker environment was correctly linked to shared volume.
Adding Makefile and ignore files out of the lint scope of prettier formatting.
=> Chore(web-twig): Fix dependency link paths for Docker development

packages/web-react/src/components/Dropdown/DropdownTrigger.tsx, packages/web-react/src/components/Modal/demo/ModalDefault.tsx, packages/web-react/src/types/dropdown.ts
=> Fix(web-react): Fix types in Dropdown #DS-1221

packages/web-react/docs/stories/examples/ModalWithDropdown.stories.tsx, packages/web-react/src/components/Dropdown/README.md, packages/web-react/src/types/dropdown.ts
The Dropdown was using an old structure with the render prop.
It is not working here: https://spirit-design-system-storybook.netlify.app/?path=/story/examples-compositions-modals--modal-with-dropdown
=> Docs: Fix Modal with Dropdown composition

packages/web-react/docs/stories/examples/ModalWithDropdown.stories.tsx, packages/web-react/src/components/Dropdown/DropdownTrigger.tsx
Fixes visual representation of the Modal and Dropdown composition.
=> Fix composition of Dropdown in Modal

docs/migrations/web-react/MIGRATION-v2.md, docs/migrations/web-twig/MIGRATION-v3.md, docs/migrations/web/MIGRATION-v2.md
=> Docs(web,web-twig,web-react): Migration Guides cleanup #DS-1250

packages/web-react/src/components/Toast/UncontrolledToast.tsx
* causing "Module not found"
* UncontrolledToast.js contains a reference to the file "."
Thanks @dlouhak
=> Fix(web-react): Import components from file intead of the index

.github/workflows/build.yaml, .github/workflows/test.yaml
=> Chore(ci): Disable NX cloud caching

packages/web-react/src/components/UNSTABLE_Slider/useSlider.ts
=> Refactor(web-react): Remove unused type from Slider component

.github/workflows/test-web-twig.yaml, .github/workflows/test.yaml, packages/web-twig/Makefile, packages/web-twig/composer.json
Make sure composer.json is normalized to proper format.
=> Chore(web-twig): Add lint scripts to check composer.json format

packages/web-react/scripts/entryPoints.js, packages/web-react/src/components/UNSTABLE_Avatar/README.md, packages/web-react/src/components/UNSTABLE_Avatar/UNSTABLE_Avatar.tsx, packages/web-react/src/components/UNSTABLE_Avatar/__tests__/UNSTABLE_Avatar.test.tsx, packages/web-react/src/components/UNSTABLE_Avatar/__tests__/useAvatarStyleProps.test.ts, packages/web-react/src/components/UNSTABLE_Avatar/constants.ts, packages/web-react/src/components/UNSTABLE_Avatar/demo/AvatarIcon.tsx, packages/web-react/src/components/UNSTABLE_Avatar/demo/AvatarImage.tsx, packages/web-react/src/components/UNSTABLE_Avatar/demo/AvatarText.tsx, packages/web-react/src/components/UNSTABLE_Avatar/demo/index.tsx, packages/web-react/src/components/UNSTABLE_Avatar/index.html, packages/web-react/src/components/UNSTABLE_Avatar/index.ts, packages/web-react/src/components/UNSTABLE_Avatar/stories/UNSTABLE_Avatar.stories.tsx, packages/web-react/src/components/UNSTABLE_Avatar/useAvatarStyleProps.ts, packages/web-react/src/components/index.ts, packages/web-react/src/types/avatar.ts, packages/web-react/src/types/index.ts, packages/web/src/scss/components/UNSTABLE_Avatar/README.md
=> Feat(web-react): Introduce UNSTABLE_Avatar component #DS-1324

yarn.lock
=> Chore(repo): Update lockfile due to dependency conflicts

packages/web-react/README.md, packages/web-react/src/components/UNSTABLE_Avatar/README.md, packages/web-react/src/components/UNSTABLE_Divider/README.md, packages/web-react/src/components/UNSTABLE_Slider/README.md, packages/web-twig/src/Resources/components/UNSTABLE_Divider/README.md, packages/web/src/scss/components/FieldGroup/README.md, packages/web/src/scss/components/FileUploader/README.md, packages/web/src/scss/components/Select/README.md, packages/web/src/scss/components/TextArea/README.md, packages/web/src/scss/components/TextField/README.md, packages/web/src/scss/components/UNSTABLE_Avatar/README.md, packages/web/src/scss/components/UNSTABLE_Divider/README.md, packages/web/src/scss/components/UNSTABLE_Slider/README.md, packages/web/src/scss/components/UNSTABLE_Slider/_UNSTABLE_Slider.scss, packages/web/src/scss/components/UNSTABLE_Slider/_theme.scss, packages/web/src/scss/components/UNSTABLE_Slider/_tools.scss, packages/web/src/scss/components/UNSTABLE_Slider/index.html
This is a follow-up of #1471.
https://jira.almacareer.tech/browse/DS-1330
=> Feat(web): Adjust the `UNSTABLE_Slider` component according to the design 

Makefile, yarn.lock
It helps to resolve some installation issues here on GitHub Actions.
=> Unlock dependencies and install them again

.github/workflows/build.yaml
=> Chore(ci): Build temporarily only on Node.js v18

package.json, yarn.lock
=> Deps: Upgrade Nx to 19.5.1

packages/web-twig/composer.json
=> Fix(web-twig): Add unintentionally removed content of the composer.json

packages/web/src/scss/helpers/breakout/_breakout.scss, packages/web/src/scss/helpers/breakout/index.html
=> Feat(web): Add responsive variants to breakout-container helper #DS-1386

packages/design-tokens/src/js/generated/colors.ts, packages/design-tokens/src/js/generated/gradients.ts, packages/design-tokens/src/js/generated/shadows.ts, packages/design-tokens/src/js/generated/typography.ts
=> Feat(design-tokens): Update JS Design Tokens manually #DS-1394

packages/web/src/scss/components/Accordion/_Accordion.scss
[Komponenta Accordion | úpravy chování na mobilu](https://jira.almacareer.tech/browse/DS-1365)
=> Feat(web): Remove `Accordion` Header active background change

packages/web-react/src/components/Grid/useGridStyleProps.ts, packages/web-react/src/constants/direction.ts, packages/web-react/src/hooks/__tests__/useSpacingStyles.test.ts, packages/web-react/src/hooks/useSpacingStyle.ts
=> Refactor(web-react): Use Spacing hook in Grid component #DS-1425

.github/CODEOWNERS, .prettierignore
Assign deveolpers to `configs` and `exporters` directories so they will be automatically assign to the PRs.
=> Chore(repo): Assign codeowners to configs and exporters

packages/web/src/scss/foundation/_typography.scss
=> BREAKING CHANGE(web): Set default color to body and each theme selector

packages/web/src/scss/components/Flex/_theme.scss, packages/web/src/scss/components/Flex/index.html, packages/web/src/scss/components/index.scss, tests/e2e/demo-components-compare.spec.ts
=> Feat(web): Switch Flex component to v3 design tokens #DS-1444

package.json, yarn.lock
=> Deps(repo): Upgrade nx to 19.6.5

exporters/variables-scss/package.json
* this package is not published anywhere
* it is used directly from the repository
=> Chore(exporter-variables-scss): Make package private

examples/next-with-pages-router/src/pages/index.tsx, packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
=> Fix(web-react): FileUploader document object not found for SSR #DS-1470

packages/form-validations/index.html
The form validation demo was not validating
=> Fix(form-validations): Fix form IDs in form-validations demo

Makefile
=> Chore(ci): Use `dist-tag` only if it is present in command

Makefile
=> Chore(ci): Introduce new `preversion` and `graduate` targets for creating a prerelease version

Makefile
=> Chore(ci): Fix indentation in Makefile

configs/jest-config-spirit/node/index.js, packages/web-react/src/icons/index.tsx
=> Omit barrel and demo files from code coverage report

exporters/tokens/README.md
=> Feat(exporter-tokens): Document Themes naming rules #DS-1497

packages/design-tokens/src/scss/@themes.scss, packages/design-tokens/src/scss/themes/theme-light-default/_colors.scss, packages/design-tokens/src/scss/themes/theme-light-on-brand/_colors.scss, packages/web/src/scss/tools/__tests__/_themes.test.scss, packages/web/src/scss/tools/_themes.scss
=> Feat(design-tokens): Use CSS variables in themes directly

apps/demo/config/vite/app.ts
=> Chore: Disable SASS deprecation warnings #DS-1514

packages/web-react/src/components/Heading/Heading.tsx, packages/web-react/src/components/Heading/useHeadingStyleProps.ts, packages/web-react/src/components/Link/useLinkStyleProps.ts
=> Fix(web-react): Unwanted props in DOM #DS-1553

playwright.config.ts
https://playwright.dev/docs/test-reporters#html-reporter
=> Test(e2e): Do not open reporter in Playwright after test

packages/web-react/src/components/Pagination/PaginationLink.tsx, packages/web-react/src/components/Pagination/UncontrolledPagination.tsx, packages/web-react/src/components/Pagination/usePagination.tsx
=> Fix(web-react): Failing type in PaginationLink #DS-1586

apps/demo/partials/layout/base.hbs
=> Chore(demo): Hide elements in Supernova component preview - change allowed URLs DS-1577

docs/decisions/010-deprecations.md, packages/web-react/README.md, packages/web-twig/README.md, packages/web/README.md
Introduction of the decision about usage of the Deprecations.
https://jira.almacareer.tech/browse/DS-1215
=> Docs(repo): Introduce deprecations decision

packages/web-react/MIGRATIONS.md, packages/web-twig/MIGRATIONS.md, packages/web/MIGRATIONS.md
=> Docs: Add missing migration links to packages

.prettierignore, docs/contribution/release-schedule.md, static/release-schedule.svg
Introducing a document with the description of our release schedule and some notes on what this means for users/developers.
Some other questions for consideration:
- Do we want to include a link to our quarterly goals or somehow describe what big changes are we planning in the next major release?
- How to communicate that the `web-twig` will be abandoned in the next major release? Should it be part of this document (applies to the first question also)?
https://jira.almacareer.tech/browse/DS-1552
=> Docs(repo): Introduce Spirit release schedule document

packages/web/src/scss/components/Card/index.html
=> Fix(web): Wrap `Card` demos in Containers

packages/web-react/src/components/Box/__tests__/Box.test.tsx, packages/web-react/src/components/UNSTABLE_Slider/__tests__/UNSTABLE_UncontrolledSlider.tsx
=> Refactor(web-react): Use `@local/tests` path alias in tests

.github/workflows/e2e.yml
=> Chore: Add E2E workflow Slack message @channel tag

packages/web/src/scss/helpers/buttons/_buttons.scss, packages/web/src/scss/helpers/buttons/index.html, packages/web/src/scss/helpers/buttons/index.scss, packages/web/src/scss/helpers/index.scss
=> Feat(web): Introduce `button-unstyled` helper

packages/web-react/src/components/Tabs/TabItem.tsx, packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx, packages/web-twig/src/Resources/components/Tabs/TabItem.twig, packages/web-twig/src/Resources/components/Tabs/TabLink.twig, packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsDefault.twig.snap.html, packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacing.twig.snap.html, packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacingForEachBreakpoint.twig.snap.html, packages/web/src/scss/components/Tabs/README.md, packages/web/src/scss/components/Tabs/index.html
=> Fix: Add missing presentation role to Tabs Item #DS-1653

scripts/lts-schedule/README.md
=> Style(scripts): Use `repository` instead of just `repo`

scripts/lts-schedule/package.json, scripts/post-changelog/package.json
* they are not meant to be published
=> Chore(scripts): Make the scripts packages private

README.md
=> Docs(repo): Add corepack steps to quick setup of the repository

.github/workflows/pr-meta.yaml
* the old one is not maintained any more
https://github.com/alma-oss/cookie-consent-manager/pull/414
=> Chore(ci): Replace auto assign GitHub action

.github/workflows/publish.yaml
* in shallow clones all tags may not be discovered
=> Chore(ci): Fetch full history on publish workflow

.github/workflows/e2e.yml, package.json, yarn.lock
🤦‍♂️ 
https://github.com/lmc-eu/spirit-design-system/pull/1888
=> Revert: Deps: Update Playwright from 1.49.1 to 1.50.1

docs/contribution/release-schedule.md
Removing duplicated heading and bullet point.
=> Docs(repo): Remove duplicated Next Major Release Plans in release schedule

apps/demo/config/vite/app.ts
* @see: https://github.com/vitejs/vite/commit/bd896fb5f312fc0ff1730166d1d142fc0d34ba6d
=> Chore(demo): Setup allowed hosts for demo app

packages/web-react/src/components/Divider/stories/Divider.stories.tsx
=> Fix(demo): Move Divider from `Experimental` to `Components` in Storybook

packages/web/src/scss/components/UNSTABLE_EmptyState/index.html
=> Docs(web): Use correct Flex reversed class in Empty State

.github/workflows/publish.yaml
=> Fix(ci): Use correct env for changelog posting

packages/web-twig/src/Resources/components/Container/Container.stories.twig, packages/web-twig/src/Resources/components/Container/Container.twig, packages/web-twig/src/Resources/components/Container/README.md, packages/web-twig/src/Resources/components/Container/__tests__/__fixtures__/containerDefault.twig, packages/web-twig/src/Resources/components/Container/__tests__/__snapshots__/containerDefault.twig.snap.html, packages/web-twig/src/Resources/components/Container/stories/ContainerSizes.twig
- new sizes in twig
https://jira.almacareer.tech/browse/DS-1674
=> Feat(web-twig): Introduce container sizes #DS-1674

packages/web-react/DEPRECATIONS.md, packages/web-react/src/components/Header/Header.tsx, packages/web-react/src/components/Header/README.md, packages/web/DEPRECATIONS.md, packages/web/src/scss/components/Header/README.md, packages/web/src/scss/components/Header/_Header.scss
=> Feat: Deprecate Header component #DS-1598

packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/__tests__/__fixtures__/UNSTABLE_EmptyState.twig, packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/__tests__/__snapshots__/UNSTABLE_EmptyState.twig.snap.html, packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/stories/EmptyStateDefault.twig
Already fixed in web, but forgotten in twig
Fix for visual tests
https://github.com/lmc-eu/spirit-design-system/commit/4f4ea632df2973ad22cae70f5db9c4021f37a0f3
=> Docs(web-twig): Use correct Flex reversed class in Empty State

packages/design-tokens/src/js/global-tokens/other.ts, packages/design-tokens/src/scss/global-tokens/_other.scss
- sizes for container
https://jira.almacareer.tech/browse/DS-1674
=> Feat(design-tokens):  Introduce Container size tokens #DS-1674

apps/storybook/decorators/IconGlobalDecorator.tsx, apps/storybook/main.ts
=> Refactor(demo): Use path aliases for packages in Storybook

.github/CODEOWNERS
Adding new team members @vmilersky and @dlouhak
=> Chore(repo): Introduce @dlouhak and @vmilersky between Spirit Design System code owners

packages/web-react/config/tsconfig.prod.json
* @see: 55ad54c40bff4ec9932187d6706820975b063dd7
* the output distribution code was in CJS format instead of ESM
Sorry, this was my mistake while migratting to the Typescript v5
=> Chore(web-react): Partial revert of `Chore(web-react): Building with TypeScript v5`

examples/next-with-app-router/next.config.ts, examples/next-with-app-router/package.json, examples/next-with-app-router/src/app/globals.scss, examples/next-with-app-router/tsconfig.json, yarn.lock
I have just copied my working code from the live coding presentation to the example.
=> Examples: Update Next.js example with App router to Next v15 and React v19

packages/web-react/src/components/Navigation/__tests__/useNavigationActionProps.test.ts, packages/web-react/src/components/Navigation/useNavigationActionProps.ts
=> Fix(web-react): Pass href to Nextjs Link in NavigationAction #DS-1714

packages/web-react/src/components/Button/__tests__/Button.test.tsx, packages/web-react/src/components/ButtonLink/__tests__/ButtonLink.test.tsx, packages/web-react/src/components/Drawer/DrawerCloseButton.tsx, packages/web-react/src/components/Drawer/README.md, packages/web-react/src/components/Drawer/__tests__/DrawerCloseButton.test.tsx, packages/web-react/src/components/Drawer/stories/DrawerCloseButton.stories.tsx, packages/web-react/src/types/drawer.ts, packages/web-react/tests/providerTests/dictionaryPropsTest.tsx
=> Feat(web-react): Allow color prop in DrawerCloseButton #DS-1755

package.json, yarn.lock
=> Deps: Update monorepo tools non-major

examples/next-with-app-router/package.json, examples/next-with-pages-router/package.json, packages/web-react/package.json, yarn.lock
=> Deps: Upgrade dependency @types/react-dom to 18.3.5

examples/next-with-app-router/package.json, examples/next-with-pages-router/package.json, packages/analytics/package.json, packages/codemods/package.json, packages/common/package.json, packages/web-react/package.json, packages/web/package.json, yarn.lock
=> Deps: Upgrade dependency @types/node to 20.17.24

scripts/post-changelog/README.md, scripts/post-changelog/package.json, scripts/post-changelog/post-changelog.ts, scripts/post-changelog/tsconfig.json, yarn.lock
Alignment of our code to ESM-only code using TypeScript.
=> Refactor(scripts): Migrate post-changelog script to TypeScript

packages/web/src/scss/components/SegmentedControl/index.html
=> Style(web): Change indentation of SegmentedControl demo to spaces

packages/web/src/scss/components/Box/README.md
[DS-1799](https://jira.almacareer.tech/browse/DS-1799)
=> Docs(web): Warn when `border-style` is set without border color and width #DS-1799

.github/actions/has-tags/action.yaml, .github/workflows/publish.yaml, .github/workflows/supernova.yaml
refs #DS-1801
https://jira.almacareer.tech/browse/DS-1801
=> Chore(ci): Publish Supernova.io docs only if tags were created

.github/actions/has-tags/action.yaml
=> Chore(ci): Add required missing property `shell` to composite action

packages/web/src/js/SegmentedControl.ts, packages/web/src/js/__tests__/SegmentedControl.test.ts, packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
=> Fix(web): SegmentedControl isn't occasionally initialised #DS-1822

.github/workflows/version.yaml
=> Chore(ci): Fetch tags when running version workflow

.github/workflows/version.yaml
=> Chore(ci): Version dry run also on private packages

.github/workflows/version.yaml
=> Chore(ci): Confirm version push manually

.github/workflows/version.yaml
=> Chore(ci): Use PAT token for version push

apps/demo/partials/header.hbs, apps/web-twig-demo/templates/partials/header.html.twig
Previous state:
Current state:
=> Docs(form-validations,web,web-react,web-twig): Drawer opening button set as symmetrical

packages/web-react/src/components/ScrollView/ScrollView.tsx, packages/web-react/src/components/ScrollView/__tests__/ScrollView.test.tsx, packages/web-twig/src/Resources/components/ScrollView/README.md, packages/web-twig/src/Resources/components/ScrollView/ScrollView.twig, packages/web-twig/src/Resources/components/ScrollView/__tests__/__snapshots__/scrollViewDefault.twig.snap.html, packages/web/src/scss/components/ScrollView/README.md, packages/web/src/scss/components/ScrollView/index.html
To make it keyboard accessible
=> Feat(web,web-react,web-twig): Add tabindex to ScrollView #DS-1851

packages/web/src/scss/components/SegmentedControl/README.md, packages/web/src/scss/components/SegmentedControl/index.html
=> Feat(web): Set correct aria in SegmentedControl with Tooltip #DS-1851

apps/demo/partials/cover.hbs, apps/demo/partials/web-react/layout/default.hbs, apps/demo/partials/web-react/tabs.hbs, apps/demo/partials/web/layout/default.hbs, apps/demo/partials/web/tabs.hbs, apps/web-twig-demo/templates/layout/default.html.twig, apps/web-twig-demo/templates/partials/cover.html.twig, packages/web-react/src/components/Button/demo/ButtonDemoFactory.tsx, packages/web-react/src/components/ButtonLink/demo/ButtonLinkDemoFactory.tsx, packages/web-react/src/components/FileUploader/demo/FileUploaderAttachment.tsx, packages/web-react/src/components/FileUploader/demo/FileUploaderFluidWidth.tsx, packages/web-react/src/components/FileUploader/demo/FileUploaderInputWithAttachment.tsx, packages/web/src/scss/components/Avatar/index.html, packages/web/src/scss/components/Card/index.html, packages/web/src/scss/components/FileUploader/index.html, packages/web/src/scss/components/Footer/index.html
- Move Cover to `<main>` as it was not in a landmark
- Add correct aria and roles to tabs in demos
- Avatar(web): Remove aria-label from non-focusable element
- Card(web): Remove focusable link with aria-hidden
- FileUploader & Footer(web): Fix form for/id mismatch
- Button & ButtonLink(web-react): Add hidden label to icon only buttons
- FileUploader(web-react): Use correct HTML elements in demos
=> Chore(web,web-react): Improve demos to be accessibility compatible #DS-1851

packages/web-react/src/components/Checkbox/Checkbox.tsx, packages/web-react/src/components/Field/HelperText.tsx, packages/web-react/src/components/FieldGroup/FieldGroup.tsx, packages/web-react/src/components/FileUploader/FileUploaderInput.tsx, packages/web-react/src/components/Radio/Radio.tsx, packages/web-react/src/components/Select/Select.tsx, packages/web-react/src/components/Slider/Slider.tsx, packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx, packages/web-react/src/components/Toggle/Toggle.tsx, packages/web-react/src/hooks/__tests__/useAriaDescribedBy.test.ts, packages/web-react/src/hooks/index.ts, packages/web-react/src/hooks/useAriaDescribedBy.ts
=> Feat(web-react): Remove aria-describedby from form elements if no helper or validation #DS-1851

.github/workflows/version.yaml, CONTRIBUTING.md
I have documented the actual release workflow which is automated a little bit more.
Please, also check the `version.yaml` file a little bit more. Since it was hard to test it locally I had to test it by running on GitHub Actions. So do not hesitate to ask or suggest changes about why the hell does it work :-)
I will gladly add more comments or describe it more in the contribution file.
=> Docs(ci): Automated and manual release workflow

packages/web/src/scss/settings/_utilities.scss, packages/web/src/scss/tools/__tests__/_utilities.test.scss, packages/web/src/scss/tools/_utilities.scss
This pull request introduces a utility function for generating token maps in SCSS and integrates it into the existing utilities for background color, border color, and text color. Additionally, it includes tests to validate the functionality of the new utility function. Below is a summary of the most important changes:
* Added a new `generate-token-map` function in `packages/web/src/scss/tools/_utilities.scss`. This function dynamically generates token maps by filtering tokens based on a specified scope and constructing keys with a customizable prefix.
* Updated the `$utilities` map in `packages/web/src/scss/settings/_utilities.scss` to use the `generate-token-map` function for background color, border color, and text color utilities with accent colors. This allows for dynamic token …
=> Feat(web): Introduce utility classes for new accent colors #DS-1773

packages/web/README.md
[DS-1883](https://jira.almacareer.tech/browse/DS-1883)
=> Docs(web): Custom Sass functions and mixins are for internal usage only #DS-1883

packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx, packages/web-react/src/components/Section/useSectionSizeProps.ts, packages/web-react/src/types/shared/tokens.ts
=> Refactor(web-react): Refactor breakpoint types #DS-1701

.github/markdown-link-check-config.json, .github/workflows/docs-review.yaml, .remarkignore, CONTRIBUTING.md, docs/contribution/feature-flags.md, docs/migrations/README.md, docs/migrations/web-react/migration-v2.md, docs/migrations/web-react/migration-v3.md, docs/migrations/web-twig/migration-v3.md, docs/migrations/web-twig/migration-v4.md, packages/form-validations/MIGRATIONS.md, packages/web-react/MIGRATIONS.md, packages/web-twig/CONTRIBUTING.md, packages/web-twig/MIGRATIONS.md, packages/web-twig/README.md, packages/web-twig/src/Resources/components/Icon/README.md, packages/web/MIGRATIONS.md, packages/web/src/scss/components/EmptyState/README.md
🚶‍♂️ around and found some bad links.
=> Chore: Change markdown link check action to maintained one

packages/web-react/src/components/Drawer/DrawerCloseButton.tsx, packages/web-react/src/components/Drawer/README.md, packages/web-react/src/components/Drawer/__tests__/DrawerCloseButton.test.tsx, packages/web-react/src/components/Drawer/stories/DrawerCloseButton.stories.tsx, packages/web-react/src/types/drawer.ts
[DS-1870](https://jira.almacareer.tech/browse/DS-1870)
=> Feat(web-react): Introduce `size` and `iconBoxSize` property on `DrawerCloseButton` #DS-1870

packages/web/src/scss/components/UNSTABLE_Header/_theme.scss
[DS-1734](https://jira.almacareer.tech/browse/DS-1734)
- Read the [Contributing Guidelines](https://github.com/lmc-eu/spirit-design-system/blob/main/CONTRIBUTING.md).
- Follow the [PR Title/Commit Message Convention](https://github.com/lmc-eu/spirit-design-system/blob/main/CONTRIBUTING.md#commit-conventions).
- Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- Ideally, include relevant tests that fail without this PR but pass with it.
-->
=> Feat(web): Change color of the Header's border #DS-1734

configs/eslint-config-spirit/package.json, packages/web-react/package.json, yarn.lock
* there has been a phishing attack
* @see: https://github.com/advisories/GHSA-f29h-pxvx-f335
=> Chore(eslint-config): Upgrade `eslint-config-prettier` to 9.1.2

exporters/tokens/README.md
Update documentation for https://github.com/lmc-eu/spirit-design-system/pull/2141
https://jira.almacareer.tech/browse/DS-2103
=> Docs(exporter-tokens):  Devices Tokens section and clarify Theme Tokens #DS-2103

packages/icons/jest.config.ts, packages/icons/package.json, packages/icons/scripts/__tests__/buildConstants.test.ts, packages/icons/scripts/__tests__/buildSvg.test.ts, packages/icons/scripts/__tests__/prepareSvgReact.test.ts, packages/icons/scripts/__tests__/shared.test.ts, packages/icons/scripts/buildConstants.js, packages/icons/scripts/buildSvg.js, packages/icons/scripts/prepareSvgReact.js, yarn.lock
[Add unit tests for design-icons/scripts](https://jira.almacareer.tech/browse/DS-1750)
=> Test(icons): Add unit tests for icon scripts #DS-1750

.yarnrc.yml
* addressing supply chain attack security issues
https://pnpm.io/supply-chain-security
=> Chore(repo): Disable running postinstall scripts from 3rd party packages

SECURITY.md
=> Chore(repo): Introduce security policy document

exporters/tokens/.eslintrc.cjs, exporters/tokens/package.json, yarn.lock
=> Style(exporter-tokens): Use eslint-config-spirit intead of relative path to root ESLint config
