lmc-eu/spirit-design-system

README.md
examples/web-react/package.json
examples/web/package.json
packages/design-tokens/README.md
packages/design-tokens/package.json
packages/web-react/README.md
packages/web-react/package.json
packages/web/README.md
packages/web/package.json

- Refactor: Keep source for publishing in `dist` directory in all packages
- Refactor: Prefer `mkdir` system command over a cross-platform dependency in examples
- Chore: Cross-link monorepo packages with `*` and simplify cross-package paths in npm scripts
- Docs: Update main `README` to be in sync with code

Refactor monorepo paths

---

.github/workflows/deploy.yaml

* because lerna does not work with npm automation tokens
* @see https://github.com/lerna/lerna/issues/2788

Chore: Pass option `--no-verify-access` to lerna publish

---

packages/design-tokens/package.json
packages/web-react/package.json
packages/web/package.json

Not only link to the repo is now not shown in [package listing on npmjs.com](https://www.npmjs.com/package/@lmc-eu/spirit-design-tokens), also dependabot uses it to assemble URLs when opening issues like https://github.com/lmc-eu/cookie-consent-manager/pull/43 (where the link is now missing),

Chore: Declare path to repository in package.json

---

packages/design-tokens/src/scss/_typography.scss

Otherwise browser's default font would be applied.
`sans-serif` is now applied when:
1. Inter font is linked correctly, but has not yet been downloaded,
2. Inter font is not available at all.

Fix: Render text with `sans-serif` when Inter font is not available

---

examples/web-react/package.json
examples/web/index.html
examples/web/jobs.html
examples/web/package.json
examples/web/postcss.config.js
packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/Tag/Tag.tsx
packages/web/src/components/Button/_Button.scss
packages/web/src/components/Button/_tools.scss
packages/web/src/components/Tag/_Tag.scss
packages/web/src/components/Tag/_tools.scss

- New class names are like `.Button`, `.Button--primary`, `.Tag`, etc. (the `lmc-*` prefix has been removed).
- Jobs example shows how to prefix class names on project level using a PostCSS plugin.
- `examples/web-react` starts working once `web-react` v0.3.0 is released.
- Docs is to be updated in a standalone PR, along with major docs rewrite.

BREAKING CHANGES: Remove default prefix from CSS class names to make it opt-in

---

.gitignore

* created and updated by ./bin/ci/npm-auth.sh
* prevents publishing new package because of uncommited updatess

Chore: Ignore .npmrc created by CI pipeline

---

packages/web-react/src/components/Button/Button.tsx

* solves problem when using button in <Link> component of react-router
* "Function components cannot be given refs. Attempts to access this
ref will fail. Did you mean to use React.forwardRef()?"
Read more:
- https://reactjs.org/docs/refs-and-the-dom.html

Feat(web-react): Pass down an access to button dom via ref prop

---

.stylelintrc
examples/web/index.html
examples/web/jobs.html
examples/web/src/jobs/@tokens.scss
examples/web/src/jobs/jobs.scss
packages/design-tokens/README.md
packages/design-tokens/src/scss/_breakpoints.scss
packages/design-tokens/src/scss/_layout.scss
packages/design-tokens/src/scss/index.scss
packages/web/package.json
packages/web/src/components/Container/README.md
packages/web/src/components/Container/_Container.scss
packages/web/src/components/Container/_theme.scss
packages/web/src/components/Container/_tools.scss
packages/web/src/components/Container/index.scss
packages/web/src/components/Tag/README.md
packages/web/src/components/index.scss
packages/web/src/tools/_breakpoint.scss
yarn.lock

…web and showcase them in demo

DS-80 Feat: Implement Container component

---

package.json
yarn.lock

* switches generating unordered list from asterisk to hyphen which is
valid for this repo

Deps: Bump @lmc-eu/conventional-changelog-lmc-github to 2.0.0

---

packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/Button/ButtonLink.tsx
packages/web-react/src/components/Button/__tests__/Button.test.tsx
packages/web-react/src/components/Button/__tests__/ButtonLink.test.tsx

By refactoring buttons to use hooks we accidentally omit children props.

Fix(web-react): Add missing children prop in buttons

---

packages/web-react/src/components/Button/ButtonLink.tsx
packages/web-react/src/components/Button/__tests__/ButtonLink.test.tsx
packages/web-react/src/components/Button/useButtonAriaProps.tsx
packages/web/src/components/Button/_Button.scss

Fix bad props in ButtonLink and define text-decoration none to prevent default styles...

ButtonLink component fix props and styles

---

package.json

* lerna is adding some extra new lines after version changes in
CHANGELOG.md
* running prettier on `version` lifecycle fixes this

Chore(repo): Format changelog when releasing new version

---

examples/web/index.html
examples/web/jobs.html
packages/web-react/docs/stories/examples/LoginForm.stories.tsx
packages/web-react/src/components/TextField/PasswordField.stories.tsx
packages/web-react/src/components/TextField/TextField.stories.tsx
packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
packages/web-react/src/components/TextField/__tests__/useTextFieldStyleProps.test.tsx
packages/web-react/src/components/TextField/useTextFieldStyleProps.tsx
packages/web-react/src/types/textField.ts
packages/web/src/components/PasswordField/_theme.scss
packages/web/src/components/TextField/README.md
packages/web/src/components/TextField/_theme.scss
packages/web/src/tools/_forms.scss

Stretching input to entire container space using `width` instead of `max-width`.

Fix(web): Stretch input to entire container

---

packages/web-react/src/components/Alert/__tests__/Alert.test.tsx
packages/web-react/src/components/Button/__tests__/Button.test.tsx
packages/web-react/src/components/Button/__tests__/ButtonLink.test.tsx
packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
packages/web-react/src/components/Container/__tests__/Container.test.tsx
packages/web-react/src/components/Grid/__tests__/Grid.test.tsx
packages/web-react/src/components/Link/__tests__/Link.test.tsx
packages/web-react/src/components/Stack/__tests__/Stack.test.tsx
packages/web-react/src/components/Tag/__tests__/Tag.test.tsx
packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
packages/web-react/tests/providerTests/classNamePrefixProviderTest.tsx

Removing repeating prefix text and refactoring them into a more general one which is included as a single test function.

Test(web-react): Refactor prefix testing into more general provider test

---

packages/web-react/src/components/Heading/Heading.tsx
packages/web-react/src/components/Heading/__tests__/Heading.test.tsx
packages/web-react/src/components/Heading/stories/Heading.tsx

Disscused on Slack (private): https://lmccz.slack.com/archives/DHNJX3A2F/p1649858291902679
https://github.com/lmc-eu/spirit-design-system/tree/main/packages/web-react/src/components/Heading
have not optional type size and have no default.

Fix(web-react): Add missing default prop size for Heading component

---

packages/web/README.md

Discussed on https://lmccz.slack.com/archives/C0250JQT0PK/p1650881484450739 (private)
Missunderstanding of 
> Plugins can be included individually (using js/*.js), or all at once
@adamkudrna was thinking that individual files are missing in package.

Docs(web): Better way to describe how to use JS plugins individually

---

examples/web/index.html

* causes not proper loading of the bundle in safari
* DOMContentLoaded event is sometimes trigger earlier then script is
ready

Fix(web): Load script using defer instead of async in examples

---

packages/web/src/js/Header.ts

Fixed desktop dialog which was not opening.

Fix(web): Find related header nav element base on data target attribute

---

packages/web/src/js/Header.ts
packages/web/src/js/Modal.ts
packages/web/src/js/utils/__tests__/index.test.ts
packages/web/src/js/utils/index.ts

Using this quick fix https://www.charistheo.io/blog/2021/02/restart-a-css-animation-with-javascript/#restarting-a-css-animation to restart animation when backdrop is injected.

Fix(web): Trick to start animation when inject backdrop (refs #DS-218)

---

packages/web-react/config/tsconfig.eslint.json
packages/web-react/config/tsconfig.prod.json
packages/web-react/package.json
packages/web-react/scripts/resolveModuleIds.ts
packages/web-react/tsconfig.json
packages/web/config/rollup.config.js
packages/web/config/tsconfig.eslint.json
packages/web/package.json
packages/web/tsconfig.json

* IDEs try to search for tsconfig.json in package root to enable
language support
* changed paths in extended tsconfigs for linting
* moved some build options to appropriate tsconfigs

Chore: Move tsconfigs to package root

---

packages/web-react/src/components/CheckboxField/README.md

Typo in example props `messsage` -> `message`

Docs(web-react): Typo in CheckboxField README

---

packages/web-twig/src/DependencyInjection/CompilerPass/OverrideServiceCompilerPass.php

To preserve the original functionality of [extending](https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web-twig/docs/extendComponents.md) components, it is necessary that ../Resources/twig-components be registered in the spirit alias

Fix(web-twig): Default components path in spirit alias

---

.renovaterc.json

* instead of weekly basis
* match better with our two weeks scrum sprints

Chore(repo): Schedule dependency updates on every two weeks

---

packages/web-twig/src/Resources/components/Alert/Alert.twig
packages/web-twig/src/Resources/components/Breadcrumbs/index.twig
packages/web-twig/src/Resources/components/Button/Button.twig
packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.twig
packages/web-twig/src/Resources/components/Container/Container.twig
packages/web-twig/src/Resources/components/Grid/Grid.twig
packages/web-twig/src/Resources/components/Heading/Heading.twig
packages/web-twig/src/Resources/components/Icon/Icon.twig
packages/web-twig/src/Resources/components/Link/Link.twig
packages/web-twig/src/Resources/components/Modal/Modal.twig
packages/web-twig/src/Resources/components/Pill/Pill.twig
packages/web-twig/src/Resources/components/Stack/Stack.twig
packages/web-twig/src/Resources/components/Tabs/TabItem.twig
packages/web-twig/src/Resources/components/Tabs/TabLink.twig
packages/web-twig/src/Resources/components/Tabs/TabList.twig
packages/web-twig/src/Resources/components/Tabs/TabPane.twig
packages/web-twig/src/Resources/components/Tabs/TabsItem.twig
packages/web-twig/src/Resources/components/Tabs/TabsLink.twig
packages/web-twig/src/Resources/components/Tabs/TabsPane.twig
packages/web-twig/src/Resources/components/Tag/Tag.twig
packages/web-twig/src/Resources/components/Text/Text.twig
packages/web-twig/src/Resources/components/TextField/TextField.twig
packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
packages/web-twig/src/Resources/components/Tooltip/TooltipWrapper.twig
packages/web-twig/src/Twig/PropsExtension.php
packages/web-twig/tests/Twig/PropsExtensionTest.php

If anyone use vanilla twig implementation without definition with { props: {...} } in embed or include
for example:
```
{% embed "@seduo-design-system/stack.twig" %}
{% block content %}
<div>Block 1</div>
<div>Block 2</div>
<div>Block 3</div>
{% endblock %}
{% endembed %} 
```
an error occurs
because macro which use props generate Runtime Error  (for example `mainProps`)

Fix(web-twig): Variable props does not exist

---

packages/web/src/scss/helpers/_links.scss

Now looks Link component with `text-decoration: underline` same as in Figma! 🎉 
Figma
Web
- before:
- after:
Unfortunately, I still don't know what causes the difference in rendered text styles between Figma and web. 😞

Fix(web): Fix underlined Link

---

packages/web-react/docs/stories/Installation.stories.mdx
packages/web-react/docs/stories/examples/LoginForm.stories.tsx
packages/web-react/src/components/Grid/Grid.stories.tsx
packages/web-react/src/components/Grid/README.md
packages/web-react/src/components/Grid/__tests__/Grid.test.tsx
packages/web-react/src/components/Grid/__tests__/useGridStyleProps.test.tsx
packages/web-react/src/components/Grid/useGridStyleProps.tsx
packages/web-react/src/types/grid.ts
packages/web-twig/src/Resources/components/Grid/Grid.twig
packages/web-twig/src/Resources/components/Grid/README.md
packages/web/src/scss/components/Grid/README.md
packages/web/src/scss/components/Grid/_Grid.scss
packages/web/src/scss/components/Grid/index.html

For now, let's keep special layouts in products. We may promote them to Spirit anytime later once they are mature enough.
**Migration:** Use new `Grid Span` component to achieve any possible layout inside our `Grid` component (#503).
```html
<div class="Grid">
<div class="Grid__span Grid__span--over-12 Grid__span--tablet--over-10 Grid__span--desktop--over-6">
…
</div>
</div>
```
---
~~Recommended~~ Alternative migration:
```html
<div class="Grid Grid--cols-1 Grid--tablet--cols-12">
<div class="MyContent">…</div>
</div>
```
```css
@media (min-width: 768px) {
.MyContent {
grid-column: 2/-2;
}
}
@media (min-width: 1280px) {
.MyContent {
grid-column: 4/-4;
}
}
```
Live example: https://codepen.io/adamkudrna/pen/oNdzMZG

BREAKING CHANGES: Remove `narrow` preset of `Grid` in favour of product-specific layouts

---

lerna.json

* @see: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
* although not mentioned in documentation, the `ci-skip` string in the commit message skips the GitHub Actions pipeline run
Due to this skip publishing was not working.

Chore(ci): Remove `ci-skip` from publish message

---

packages/web-react/src/components/Tabs/TabContent.tsx
packages/web-react/src/components/Tabs/__tests__/TabContent.test.tsx
packages/web-react/src/components/Tabs/__tests__/useTabsStyleProps.test.tsx
packages/web-react/src/components/Tabs/useTabsStyleProps.tsx

Migration: Delete `content` class name provided by the `useTabsStyleProps` hook. There is no styling applied to it.

BREAKING CHANGES(web-react): Do not provide non-existing CSS class `Tabs-content` in `Tabs` hook

---

.github/CODEOWNERS

I have an update to `CODEOWNERS` file and have a few topics to discuss:
- should I create the team and all of us should be on the review list of every PR?
- do @vmilersky and @dlouhak want to review some packages as owners of jobs-design-system?
- do @janicekt be still the owner of `web-twig`?
The idea is that as I and @tomassychra are the full-time reviewers we should be on the review list of every package. What do you think?

Chore(repo): Introduce @tomassychra into codeowners

---

packages/web-twig/src/Twig/SvgExtension.php
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set gridLayoutDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tabsDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldBaseMultiline.twig__1.html
packages/web-twig/tests/fixtures/test_reusable.svg

Reused viewBox in reused icon SVG wrapper caused scaling error when original SVG didn't have the same size as viewBox size values. Because it scaled the SVG twice. As we generate the ID hash from all the params, even the size, we can omit the viewBox from wrapper as it is already defined in the shadow dom in the use tag.

Fix(web-twig): Omit viewBox in reused SVGs to avoid scaling bug #JALL-7

---

packages/web/src/js/Header.ts
packages/web/src/js/Modal.ts
packages/web/src/js/Tabs.ts
packages/web/src/js/utils/ComponentFunctions.ts
packages/web/src/js/utils/__tests__/ComponentFunctions.test.ts
packages/web/src/js/utils/__tests__/index.test.ts
packages/web/src/js/utils/index.ts

The goal is to pass the main component element to the component instance, eg. in the `this.element` of the BaseComponent should be the element targeted by `data-target` and not the toggle element as it was until now. If the `data-target` do not exist, still the toggle element will be passed as it is now.

Feat(web): Component triggers can find target element by target dataset

---

packages/web-twig/src/Resources/components/Collapse/README.md

* `html` syntax cause that prettier formatter lowercase the Button component, eg. `Button` -> `button`

Docs(web-twig): Documenting Collapse examples in twig syntax

---

packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
packages/web/src/scss/components/CheckboxField/_theme.scss
packages/web/src/scss/components/RadioField/_RadioField.scss
packages/web/src/scss/components/RadioField/_theme.scss
packages/web/src/scss/components/TextArea/README.md
packages/web/src/scss/components/TextArea/_TextArea.scss
packages/web/src/scss/components/TextArea/_theme.scss
packages/web/src/scss/components/TextArea/index.html
packages/web/src/scss/components/TextArea/index.scss
packages/web/src/scss/components/TextField/README.md
packages/web/src/scss/components/TextField/_TextField.scss
packages/web/src/scss/components/TextField/_theme.scss
packages/web/src/scss/components/TextField/index.html
packages/web/src/scss/components/index.scss
packages/web/src/scss/theme/_form-fields.scss
packages/web/src/scss/tools/_form-fields.scss

Introducing new component is great opportunity to unify form field theme and create mixins to reduce code duplicity between form components. 🙂 
I suppose there could be a better solution. Code switching according component name in mixins and sharing all variables no matter which component uses them doesn't look like easily scalable solution. 
I'll appreciate better ideas from @adamkudrna and @crishpeen. 🙏🏻

Feat(web): TextArea (#DS-319)

---

packages/web/src/js/Collapse.ts
packages/web/src/js/__tests__/Collapse.test.ts
packages/web/src/js/constants.ts
packages/web/src/js/utils/ComponentFunctions.ts
packages/web/src/js/utils/index.ts
packages/web/src/scss/components/Accordion/README.md
packages/web/src/scss/components/Accordion/_Accordion.scss
packages/web/src/scss/components/Accordion/_theme.scss
packages/web/src/scss/components/Accordion/index.html
packages/web/src/scss/components/Accordion/index.scss
packages/web/src/scss/components/Collapse/README.md
packages/web/src/scss/components/Collapse/_Collapse.scss
packages/web/src/scss/components/Collapse/index.html
packages/web/src/scss/components/index.scss

This is CSS and JavaScript of Accordion component. 
This branch was created to merge [#580](https://github.com/lmc-eu/spirit-design-system/pull/580) and [#581](https://github.com/lmc-eu/spirit-design-system/pull/581) because there were duplicates and it was difficult to test.
1) Collapse updates and fixes
- Utility class for open state
- Accessibility fix for collapsed content
- Aria attribute on initialization was not properly set for value
- Removed class `is-expanded` for trigger, only `aria-expanded` attribute will be used
- The `data-parent` attribute to control the opening of only one item at a time
- Tests updates
- Removed 'resize' handler
- `setTimeout` replaced with async methods
- Updated handling for finished transitions
2) Accordion component styles
3) Accordion component …

Feat(web): Introduction of Accordion CSS+JS

---

packages/web/src/scss/components/Pagination/_Pagination.scss
packages/web/src/scss/components/Pagination/index.html

Change value of the display property to `inline-flex` will enable horizontally center the Pagination using the utility class `text-center`.
This behavior is currently required from the Jobs UI team.

Make `Pagination` component inline to enable horizontal alignment #JALL-37

---

.storybook/assets/stylesheets/index.scss
.storybook/decorators/IconGlobalDecorator.js
.storybook/preview.js
packages/web-react/src/components/Accordion/Accordion.stories.tsx
packages/web-react/src/components/Accordion/Accordion.tsx
packages/web-react/src/components/Accordion/AccordionContent.tsx
packages/web-react/src/components/Accordion/AccordionContext.ts
packages/web-react/src/components/Accordion/AccordionHeader.tsx
packages/web-react/src/components/Accordion/AccordionItem.tsx
packages/web-react/src/components/Accordion/AccordionItemContext.ts
packages/web-react/src/components/Accordion/README.md
packages/web-react/src/components/Accordion/__tests__/Accordion.test.tsx
packages/web-react/src/components/Accordion/__tests__/AccordionContent.test.tsx
packages/web-react/src/components/Accordion/__tests__/AccordionHeader.test.tsx
packages/web-react/src/components/Accordion/__tests__/AccordionItem.test.tsx
packages/web-react/src/components/Accordion/__tests__/useAccordionAriaProps.test.ts
packages/web-react/src/components/Accordion/__tests__/useAccordionStyleProps.test.ts
packages/web-react/src/components/Accordion/index.ts
packages/web-react/src/components/Accordion/stories/Accordion.tsx
packages/web-react/src/components/Accordion/stories/AccordionStayOpen.tsx
packages/web-react/src/components/Accordion/stories/toggleValueByType.ts
packages/web-react/src/components/Accordion/useAccordionAriaProps.ts
packages/web-react/src/components/Accordion/useAccordionStyleProps.ts
packages/web-react/src/components/Accordion/useOpenItem.ts
packages/web-react/src/components/index.ts
packages/web-react/src/types/accordion.ts
packages/web-react/src/types/index.ts

1) **React Accordion**
- Accordion
- AccordionContext
- AccordionItem
- AccordionItemContext
- AccordionHeader
- AccordionContent
- useAccordionAriaProps
- useAccordionStyleProps
- useOpenItem
2) **Accordion stories**
- Accordion (default)
- AccordionStayOpen
- common toggle function
3) Storybook global Icon provider
- `IconGlobalDecorator` - No longer need to define an IconProvider every time icons are used
4) Accordion tests
- Accordion.test
- AccordionItem.test
- AccordionHeader.test
- AccordionContent.test
- useAccordionAriaProps.test  
- useAccordionStyleProps.test

Feat(web-react): Introduce React Accordion component #DS-447

---

packages/web-react/src/components/Collapse/Collapse.tsx

* fixing Webpack error: Module build failed: Module not found: @lmc-eu/spirit-web-react/components/Collapse/Collapse.js" contains a reference to the file "react-transition-group/Transition".
```
> jobs-cz@1.0.0 build:prod
> encore production
Running webpack ...
ERROR  Failed to compile with 1 errors9:36:56 AM
Module build failed: Module not found:
"./node_modules/@lmc-eu/spirit-web-react/components/Collapse/Collapse.js" contains a reference to the file "react-transition-group/Transition".
This file can not be found, please check it for typos or update it if the file got moved.
```
https://reactcommunity.org/react-transition-group/transition

Fix(web-react): Module `Transition` was not found while using Collapse

---

packages/web-react/src/components/Dropdown/Dropdown.tsx
packages/web-react/src/components/Dropdown/README.md
packages/web-react/src/components/Dropdown/useDropdown.ts
packages/web-react/src/types/dropdown.ts

* new prop `onAutoClose` that enables running callback when Dropdown is closed using click outside of the component

Feat(web-react): Introduce on auto close callback prop for Dropdown

---

packages/web/src/scss/components/Dropdown/_Dropdown.scss

Fix(web): Prevent from dropdown content overflow outside its container

---

packages/web/src/scss/components/Accordion/_Accordion.scss
packages/web/src/scss/components/Accordion/_theme.scss
packages/web/src/scss/components/Accordion/index.html

Fix issues for Accordion styles [[DS-494](https://jira.lmc.cz/browse/DS-494), [DS-499](https://jira.lmc.cz/browse/DS-499), [DS-500](https://jira.lmc.cz/browse/DS-500)]
* Preview example content
* Border on heading below opened item
* Preview example "open" text has been deleted
* Text color of heading
* (iOS) Blinking rectangle when click on heading
* (iOS) After click on heading, `:hover` state remains

Fix(web): Fix Accordion styles

---

packages/web/src/scss/tools/_form-fields.scss

This is to prevent "sticky" interactions on touch devices.
https://user-images.githubusercontent.com/5614085/210080543-d67f6afe-e293-4693-9490-542548b8c784.mp4
https://user-images.githubusercontent.com/5614085/210080621-d06a6756-d095-47f5-adc7-a14d9f4456da.mp4

Fix(web): Only show `Item` background during interactions on hover-enabled devices

---

packages/web-twig/src/Resources/components/Collapse/Collapse.twig
packages/web-twig/src/Resources/components/Collapse/README.md

#DS-275
Event if the Collapse component didn't use `breakpoint` and `parent` properties along next in its logic and is using them as optional, it haven't had default value so it was still required. Otherways it blowes up with server error.

Fix(web-twig): Make Collapse components props optional according to its readme

---

packages/web/src/scss/components/Accordion/_Accordion.scss

Accordion in open state has a rotated arrow, where transformation creates a new stacking context and therefore overlays the toggle button preventing it from closing the Accordion.

Fix(web): Fix Accordion arrow stacking context #DS-527

---

packages/web-react/src/components/Accordion/README.md
packages/web-react/src/components/Modal/README.md

I found out it wasn't possible to just copy-paste the code from docs and make it work. Here I fix few small errors I encountered.

Docs(web-react): Fix Accordion and Modal code examples

---

packages/web/src/scss/components/Collapse/_Collapse.scss
packages/web/src/scss/components/Collapse/index.html
packages/web/src/scss/helpers/_accessibility.scss
packages/web/src/scss/helpers/index.html

* Added helper class for toggle content, which depends on `aria-expanded`
* Added example for Collapse use case, also with anchor element
* ~~Created test for Collapse~~
* Fixed implementation for `data-more` option

Feat(web): Collapse toggle with variable content #DS-501

---

packages/web-react/package.json
packages/web/package.json

Helping Webpack with tree-shaking and thus removing unused parts of code.
For more information, please read https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
We are already using this in https://github.com/lmc-eu/spirit-design-system/blob/main/packages/web-react/scripts/prepareDist.js#L56. So this marks only main `package.json`.

Mark package as side-effect free

---

packages/web-twig/src/Twig/BoolpropExtension.php

because this is deprecation in symfony

Fix(web-twig): Define native return type to "Twig\Extension\ExtensionInterface::getFilters()"

---

packages/web/src/js/Collapse.ts
packages/web/src/scss/components/Collapse/README.md
packages/web/src/scss/components/Collapse/_Collapse.scss
packages/web/src/scss/components/Collapse/index.html

It did two things. One of them was the animation and the second problem was that the flickering was caused by setting the class and css attribute after loading the script.
* `Collapse.ts`: Added `state.init` for prevent animation before content is shown
* Updated examples for both components

Fix(web): Accordion(Collapse) content flashing #DS-538

---

packages/web-twig/src/Resources/components/Icon/Icon.twig
packages/web-twig/src/Resources/components/Icon/README.md

* SVG icons are reused by default using `use`
* through this prop can be reusage simply disabled

Feat(web-twig): Enable reusability of SVG icons

---

packages/web-react/src/components/Collapse/README.md

The example with undefined property renderToggle not work so its typo

Docs(web-react): Fix renderToggle to renderTrigger

---

docs/DICTIONARIES.md
packages/web-react/src/components/Text/Text.tsx
packages/web-react/src/components/Text/stories/Text.tsx
packages/web-react/src/components/Text/useTextStyleProps.ts
packages/web-react/src/types/shared/dictionaries.ts
packages/web-react/src/types/text.ts

Allow extension of a type via generic.
```jsx
const CustomText = <T extends ElementType = 'span', S ='xxlarge' | xxsmall>(args: SpiritTextProps<T, S>) => (
<Text {...args} />
);
```
Consider creating a `SizeExtended` dictionary by really extending it. So the developer can use `SizeExtended` with all those values.

Feat(web-react): Allow extension of size prop of Text component

---

packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabContent.tsx
packages/web-react/src/components/Tabs/TabContext.tsx
packages/web-react/src/components/Tabs/TabItem.tsx
packages/web-react/src/components/Tabs/TabLink.tsx
packages/web-react/src/components/Tabs/TabList.tsx
packages/web-react/src/components/Tabs/Tabs.tsx
packages/web-react/src/components/Tabs/UncontrolledTabs.tsx

* Allows `restProps` for:
* TabContent
* TabLink
* TabList
* Created `onSelectionChange` for trigger custom callback when panel changed. Applied for **Tabs** and **UncontrolledTabs**. Also add mention in docs

Fix(web-react): Tabs transfer properties #DS-401

---

packages/web-react/src/components/CheckboxField/__tests__/useCheckboxFieldStyleProps.test.ts
packages/web-react/src/components/Heading/__tests__/Heading.test.tsx
packages/web-react/src/components/Link/__tests__/Link.test.tsx
packages/web-react/src/components/RadioField/__tests__/useRadioFieldStyleProps.test.ts
packages/web-react/src/components/Text/__tests__/Text.test.tsx
packages/web-react/src/constants/dictionaries.ts
packages/web-react/src/constants/index.ts
packages/web-react/src/index.ts
packages/web-react/src/types/alert.ts
packages/web-react/src/types/button.ts
packages/web-react/src/types/heading.ts
packages/web-react/src/types/link.ts
packages/web-react/src/types/pill.ts
packages/web-react/src/types/shared/dictionaries.ts
packages/web-react/src/types/shared/inputs.ts
packages/web-react/src/types/tag.ts
packages/web-react/src/types/text.ts
packages/web-react/tests/providerTests/dictionaryPropsTest.tsx

When editing one task, I thought if these constants were somewhere separately, for better maintenance of the structure and not to mix it with types.
* splitting existing constants from dictionaries and moving them to a separate folder with constants
* editing dictionary extensible types as an optional attribute
* renaming dictionary keys and types
* updated dictionaries test
* fixed bug in **Button** component props `export type ButtonSize<S> = Size<void> | EmotionColor<void> | S;`

React dictionaries constants

---

packages/web-react/src/components/ModalComposed/README.md

Docs(web-react): Remove `jsx static` example format from ModalComposed

---

packages/web-react/src/components/Button/Button.stories.ts
packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/Button/ButtonLink.stories.tsx
packages/web-react/src/components/Button/ButtonLink.tsx
packages/web-react/src/components/Button/README.md
packages/web-react/src/components/Button/stories/argTypes.ts
packages/web-react/src/types/button.ts

* **Button** wrapped with `React.forwardRef`
* **ButtonLink** wrapped with `React.forwardRef`
~~Adding `ref` properties for these components caused type whispering in the Typescript IDE to find no values ​​other than `ref` and `children`. So does Storybook.~~

Feat(web-react): ForwardRef for Button and ButtonLink #DS-445

---

packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
packages/web-react/src/types/checkboxField.ts
packages/web-react/src/types/radioField.ts
packages/web-react/src/types/shared/element.ts
packages/web-react/src/types/shared/index.ts
packages/web-react/src/types/shared/inputs.ts
packages/web-react/src/types/shared/style.ts
packages/web-react/src/types/textArea.ts
packages/web-react/src/types/textField.ts
packages/web-react/src/types/textFieldBase.ts

Extension of components props from proper element type.
* Updating props for:
*`types/checkbox.ts`  - uses `HTMLInputElement` as base props and then expand further
*`types/radio.ts`  - uses `HTMLInputElement` as base props and then expand further
*`types/textField.ts`  - uses `HTMLInputElement` as base props and then expand further
*`types/textArea.ts`  - uses `HTMLTextAreaElement` as base props and then expand further
* Simplification of `types/textFieldBase.ts` and `types/shared/inputs.ts`

Extension of React components props

---

packages/web-react/src/components/Button/Button.stories.ts
packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/Button/ButtonLink.tsx
packages/web-react/src/components/Button/README.md
packages/web-react/src/components/Button/stories/Button.tsx
packages/web-react/src/components/Button/stories/ButtonLink.tsx
packages/web-react/src/components/Button/stories/ButtonLinkHtml.tsx
packages/web-react/src/components/Button/stories/ButtonLinkProps.tsx
packages/web-react/src/components/Button/stories/ButtonProps.tsx
packages/web-react/src/components/Button/stories/argTypes.ts
packages/web-react/src/components/Button/useButtonAriaProps.ts
packages/web-react/src/components/Button/useButtonStyleProps.ts
packages/web-react/src/types/button.ts
packages/web-react/src/types/shared/element.ts

* Thorough redesign and simplification of types for **Button** and **ButtonLink**
* Retaining `forwardRef` and tested with the **Tooltip** component
* **Button** and **ButtonLink** now contain more detailed props from the given element type. This resulted in the `useButtonAriaProps` modification. Because `HTMLAttributes` are already part of `ComponentPropsWithRef`
* Documentation mention of `elementType` and added one example
* Fixed HTML stories for **ButtonLink**

Feat(web-react): Extension and modification of Button and ButtonLink

---

packages/web-twig/CONTRIBUTING.md
packages/web-twig/README.md

Also, make the documentation a little bit maintainable.

Unescaped props in Twig docs

---

packages/web/README.md

Previous plugin had problems with `:is()` selectors.

Docs(web): Update recommended way to prefix CSS classes #DS-627

---

packages/web/src/js/FileUploader.ts

* I suppose that working with template tags adds additional whitespace in place of <template> when parsing
* from the array of document fragments we are using only the element type that return `children` property using `item` method

Fix(web): Remove additional whitespace added by template tag

---

packages/web/src/js/ScrollView.ts
packages/web/src/js/index.esm.ts
packages/web/src/js/index.umd.ts
packages/web/src/js/utils/Debounce.ts
packages/web/src/js/utils/__tests__/Debounce.test.ts
packages/web/src/js/utils/index.ts
packages/web/src/scss/components/ScrollView/README.md
packages/web/src/scss/components/ScrollView/_ScrollView.scss
packages/web/src/scss/components/ScrollView/_theme.scss
packages/web/src/scss/components/ScrollView/index.html
packages/web/src/scss/components/ScrollView/index.scss
packages/web/src/scss/components/index.scss

Offloaded to standalone issue:
- `ScrollView` test, see the comment at the top of the file
- Borders instead of shadows

Feat(web): Introduce `ScrollView` component #DS-449

---

packages/web/src/scss/components/ScrollView/README.md
packages/web/src/scss/components/ScrollView/_ScrollView.scss
packages/web/src/scss/components/ScrollView/_theme.scss
packages/web/src/scss/components/ScrollView/index.html

Previously:
```html
<div class="ScrollView__scrollingShadows" aria-hidden="true"></div>
```
Now:
```html
<div class="ScrollView__indicators ScrollView__indicators--shadows" aria-hidden="true"></div>
<div class="ScrollView__indicators ScrollView__indicators--borders" aria-hidden="true"></div>
<div
class="ScrollView__indicators ScrollView__indicators--borders ScrollView__indicators--shadows"
aria-hidden="true"
></div>
```

Feat(web): Enhance `ScrollView` scrolling indicators to be shadows, borders, or both #DS-796

---

.github/workflows/build.yaml

Fails on installing eslint-config-jsdoc.

Revert: Chore(ci): Test builds also on Node.js v20

---

packages/web/src/scss/components/ScrollView/README.md
packages/web/src/scss/components/ScrollView/_ScrollView.scss
packages/web/src/scss/components/ScrollView/index.html

New custom properties:
- `--scroll-view-start-shadow-background`
- `--scroll-view-end-shadow-background`

Feat(web): Enable customization of `ScrollView` shadows via custom properties

---

packages/web-react/netlify.toml

* problem during Netlify builds
* fatal: ambiguous argument './packages/web-react/src/'
* unknown revision or path not in the working tree.
Netlify is building web-react package while the change is only in the web-twig. Thus the web-react package should not be built.
We want to build only packages according to the changes in the file structure.
```
3:26:10 PM: Custom publish path detected. Proceeding with the specified path: 'packages/web-react/build'
3:26:10 PM: Custom build command detected. Proceeding with the specified command: 'cd ../../ && yarn lerna run --scope @lmc-eu/spirit-icons build && yarn lerna run --scope @lmc-eu/spirit-web-react examples:build'
3:26:10 PM: Custom ignore command detected. Proceeding with the specified command: 'git diff --quiet $CACHED_COMMIT_REF …
```

Chore(web-react): Set correct path according to the base directory

---

packages/web/src/js/dom/EventHandler.ts

For testing purposes on mobile devices only.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
---

Docs(web): Why is the event listener not passive by default

---

packages/web-twig/src/Resources/components/Heading/Heading.twig
packages/web-twig/src/Resources/components/Text/Text.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headingDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textDefault.twig__1.html
packages/web-twig/tests/components-fixtures/headingDefault.twig
packages/web-twig/tests/components-fixtures/textDefault.twig

Allow pass `translate` attribute to the `Heading` and `Text` components.
For product purposes we would like to be able use text components as well as set them attribute `translate` to prevent text translation.
Upcoming issue that will set global attributes across all components: https://jira.lmc.cz/browse/DS-836.

Feat(web-twig): Allow pass `translate` attribute to the `Heading` and `Text` components

---

packages/web-react/src/components/TextArea/stories/argTypes.ts
packages/web-react/src/types/textArea.ts

* the type is defined using DetailedHTMProps
* the `maxLength` prop was not used anywhere
Base on this comment (https://github.com/lmc-eu/spirit-design-system/pull/894/files#r1234453108) about the usage of `maxLenght` in web-twig I have checked it in web-react as well and noticed that it is not used anywhere thus I can removed it and replace with native `maxlength`.
https://github.com/lmc-eu/spirit-design-system/pull/894/files#r1234453108
No issue referenced.
---

Fix(web-react): TextArea is using native maxlength attribute

---

packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig

`TextArea` and `TextField` components, which comes from an abstract component `TextFieldBase`, contains unwanted blank space after `label` element.
Only Twig related and the other components look fine. :)
#DS-842

Fix(web-twig): Do not render space after label #DS-842

---

packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Modal/_Modal.scss
packages/web/src/scss/components/Modal/_theme.scss
packages/web/src/scss/components/Modal/index.html

Instead of combining both `Modal Modal--composed` classes, only `Modal` is now used.
The original `Modal__content`, `Modal__dialog` and `Modal__header` classes no longer exist, and so does the original structure.
Only Web related.
#DS-592
---

BREAKING CHANGE(web): Remove Modal deprecations #DS-592

---

apps/web-twig-demo/src/Controller/DefaultController.php

In web-twig demo app list only components which have stories inside.
---

Chore(demo): Display only web-twig dirs where stories exists

---

packages/web/src/js/FileUploader.ts

refs #DS-830
FileUploader cannot remove files with the same names
* generate simple uuid for every instance of FileUploader and use it as a prefix for file id
* this avoids having the same file ids on elements that we are querying when removing files from queue
[](https://jira.lmc.cz/browse/DS-830)
---

Fix(web): FileUploader cannot remove files with same names

---

packages/form-validations/src/FormValidations.ts
packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/_FileUploaderInput.scss
packages/web/src/scss/components/Select/README.md
packages/web/src/scss/components/Select/_Select.scss
packages/web/src/scss/components/TextArea/README.md
packages/web/src/scss/components/TextArea/_TextArea.scss
packages/web/src/scss/components/TextField/README.md
packages/web/src/scss/components/TextField/_TextField.scss
packages/web/src/scss/tools/_form-fields.scss

Instead of the `validator_message` value of the `data-spirit-element` attribute, use
`validation_text`.
- `<div data-spirit-element="validator_message">…</div>` →
`<div data-spirit-element="validation_text">…</div>`
Please refer back to these instructions or reach out to our team
if you encounter any issues during migration.
https://jira.lmc.cz/browse/DS-838

BREAKING CHANGE: Rename `validator_message` to `validation_text` #DS-838

---

packages/web-react/src/components/Tag/README.md
packages/web-react/src/components/Tag/Tag.tsx
packages/web-react/src/components/Tag/__tests__/Tag.test.tsx
packages/web-react/src/components/Tag/__tests__/useTagStyleProps.test.ts
packages/web-react/src/components/Tag/stories/argTypes.ts
packages/web-react/src/components/Tag/useTagStyleProps.ts
packages/web-react/src/types/tag.ts
packages/web-twig/src/Resources/components/Tag/README.md
packages/web-twig/src/Resources/components/Tag/Tag.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tagDefault.twig__1.html
packages/web-twig/tests/components-fixtures/tagDefault.twig
packages/web/src/scss/components/Tag/README.md
packages/web/src/scss/components/Tag/_Tag.scss
packages/web/src/scss/components/Tag/_theme.scss

Remove `light` and `default` modifiers in the `web` package. Use `subtle` and `neutral` instead.
Remove the `theme` prop in the `twig` package, use `isSubtle` instead. Remove color `default`, use `neutral instead.
Remove the `theme` prop in the `react` package, use `isSubtle` instead. Remove color `default`, use `neutral instead. Remove the `tag` prop, use `elementType` instead.
All removed props were deprecated. See each commit message for the migration guide.
#DS-648
---

BREAKING CHANGE: Remove Tag deprecation #DS-648

---

packages/web/src/js/FileUploader.ts

There is a XSS when file names like
```
<u>test</u>.txt
<iframe src="test"></iframe>.txt
```
are used and picked by FileUploader.
https://developer.mozilla.org/en-US/docs/Web/API/Document/createTextNode
---

Fix(web): Escape attachment file name in FileUploader

---

packages/web/src/js/FileUploader.ts
packages/web/src/js/__tests__/FileUploader.test.ts
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/index.html

* FileUploader displayes validation text when error happen
---

Feat(web): Display validation text on FileUploader

---

packages/web-twig/src/Resources/components/Tabs/README.md
packages/web-twig/src/Resources/components/Tabs/TabLink.twig
packages/web-twig/src/Resources/components/Tabs/stories/TabsDefault.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tabsDefault.twig__1.html
packages/web-twig/tests/components-fixtures/tabsDefault.twig

Removing the data-toggle attribute which is automatically placed when the href attribute is missing. This causes an unwanted auto initialization of Tabs when a developer needs to do this yourself.
https://jira.lmc.cz/browse/DS-840
---

web-twig: Remove data-toggle attribute from TabLink

---

.storybook/assets/stylesheets/index.scss
apps/web-twig-demo/templates/validations.html.twig
packages/web-twig/src/Resources/helpers/animations/animations.stories.twig

There is no checkboxfield anymore.
DS-862
---

Fix(demo): Use Checkbox instead of CheckboxField #DS-862

---

packages/web/src/js/FileUploader.ts
packages/web/src/js/__tests__/FileUploader.test.ts

- It is not possible to drag and drop new files when input is disabled.
- If input is not disabled and you keep drag and drop files over limit, validation messages are not duplicated anymore.
[Fixes #DS-848](https://jira.lmc.cz/browse/DS-848)
---

Fix(web): Fix FileUploader Drag and Drop and duplicated validation messages

---

packages/web-react/MIGRATION-v1.md
packages/web-twig/MIGRATION-v2.md
packages/web/MIGRATION-v1.md

Just a small typo fixes in the migration guides. 🧹

Docs(web, web-react, web-twig): Minor typo fix

---

apps/web-twig-demo/docker/docker-compose.override.yml
packages/web-twig/Makefile

Use built SVG icons for the web-twig demo app because they have `currentColor` and accept color from upper styling.
All icons were black before this change.
https://jira.lmc.cz/browse/DS-748
---

Fix(demo): Use builded icons for web-twig demo refs #DS-748

---

.github/workflows/build.yaml
.github/workflows/commitlint.yaml
.github/workflows/component-analysis.yaml
.github/workflows/deploy.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml

* the issue with cache miss was resolved and workaround should not be used anymore
The version must be exactly picked because there is a disconnection between the repository of npm-install and GitHub Marketplace
* @see https://github.com/bahmutov/npm-install/pull/188#issuecomment-1661750171
* @see https://github.com/bahmutov/npm-install/issues/175
---

Chore(ci): Revert back npm-install action to v1

---

packages/web-react/src/components/Modal/demo/index.tsx
packages/web-react/src/components/Modal/stories/ModalStacked.tsx
packages/web-react/src/components/Modal/stories/ModalWithCheckbox.tsx
packages/web-react/src/hooks/useClickOutside.ts

refs #DS-879
`event.preventDefault` in the `useClickOutside` hook prevents the default click on the label in the checkbox being applied and thus the input is checked.
https://jira.lmc.cz/browse/DS-879
---

Fix(web-react): Click outside hook prevents click on input label

---

packages/web/src/scss/components/Modal/_ModalDialog.scss

All:unset did reset box-sizing too, but we didn't set it again, so the inherited value was wrong.
https://jira.lmc.cz/browse/DS-878
---

Fix(web): Fix ModalDialog unset box-sizing #DS-878

---

packages/web/src/scss/components/Stack/README.md
packages/web/src/scss/components/Stack/_Stack.scss
packages/web/src/scss/components/Stack/_theme.scss

We don't need to use padding if there are no dividers. Revert to use the gap in default hasSpacing Stack.
https://jira.lmc.cz/browse/DS-880
Fixes #963 
---

Fix(web): Use gap in Stack with spacing and without dividers #DS-880

---

packages/web/src/js/FileUploader.ts
packages/web/src/js/__tests__/FileUploader.test.ts
packages/web/src/js/utils/Image2Base64Preview.ts
packages/web/src/js/utils/index.ts
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/index.html

Add an example for FileUploader with a modal for cropping images. 
Add the imagePreview option to FileUploaderList for displaying image previews in the file list.
Add `data-spirit-imagePreview="true"` for image previews in file list
```
<ul class="FileUploaderList" aria-labelledby="attachments-customImagePreview" data-spirit-element="list" data-spirit-imagePreview="true"></ul>
```
New demo **Attachment with Image Preview**
[web: JS FileUploader s fotkou](https://jira.lmc.cz/browse/DS-850)
---

Feat(web): FileUploader Image attachment preview #DS-850

---

packages/web-twig/src/Resources/components/Modal/Modal.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html

Currently the `aria-labelledby` attribute is rendered based on `id` not `titleId`. The render condition had to be changed.
There is a slight difference between React and Twig implementation. Twig implementation allowed the developer to set the `titleId` while in the [React implementation](https://github.com/lmc-eu/spirit-design-system/blob/59c4fbf8d7ce658bcab7dae7d5f5d9f55f498956/packages/web-react/src/components/Modal/Modal.tsx#L31) the suffix `__title` is appended to the `id`.

Fix(web-twig): Fix condition to render `aria-labelledby` attribute in the Modal component

---

packages/web-react/docs/stories/examples/FileUploaderWithImagePreview.stories.tsx
packages/web-react/src/components/FileUploader/AttachmentActionButton.tsx
packages/web-react/src/components/FileUploader/AttachmentImagePreview.tsx
packages/web-react/src/components/FileUploader/FileUploader.stories.ts
packages/web-react/src/components/FileUploader/FileUploader.tsx
packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
packages/web-react/src/components/FileUploader/FileUploaderContext.ts
packages/web-react/src/components/FileUploader/FileUploaderList.tsx
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/components/FileUploader/UncontrolledFileUploader.tsx
packages/web-react/src/components/FileUploader/__tests__/FileUploaderList.test.tsx
packages/web-react/src/components/FileUploader/__tests__/useFileQueue.test.ts
packages/web-react/src/components/FileUploader/__tests__/useFileUploaderStyleProps.test.ts
packages/web-react/src/components/FileUploader/constants.ts
packages/web-react/src/components/FileUploader/index.ts
packages/web-react/src/components/FileUploader/stories/FileUploaderWithImagePreview.tsx
packages/web-react/src/components/FileUploader/stories/FormWithFileUploader.tsx
packages/web-react/src/components/FileUploader/useFileQueue.ts
packages/web-react/src/components/FileUploader/useFileUploaderInput.ts
packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
packages/web-react/src/components/FileUploader/utils.ts
packages/web-react/src/types/fileUploader.ts

Add image preview for images in FileUploader and new param for turning this functionality on and off.
Add example for FileUploader with modal for crop image.
[DS-852](https://jira.lmc.cz/browse/DS-852)

Feat(web-react): FileUploader Image attachment preview #DS-852

---

packages/web-twig/src/Resources/components/Button/Button.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonWithMainProps.twig__1.html
packages/web-twig/tests/components-fixtures/buttonWithMainProps.twig

For the purpose of the modernized CV, where we would like to display PDF preview in a new browser window after successful form submit, we need to extend Button's API to be able to pass [`formtarget` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formtarget:~:text=type%3D%22submit%22%3E%20elements.-,formtarget,-If%20the%20button).
- It's necessary to extend React implementation as well.
- I would like open the discussion about extending (and [mention](https://github.com/lmc-eu/spirit-design-system/pull/957#pullrequestreview-1566810299)) API with HTML global attributes. Currently the components have strict list of the allowed attributes so every unsupported attribute has to be allow on the demand. What if we defined an extended list of allowed HTML …

Feat(web-twig): Enable pass `formtarget` attribute to the `Button`

---

packages/web-twig/src/Resources/components/Accordion/Accordion.twig
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionDefault.twig__1.html
packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionStayOpen.twig__1.html
packages/web/src/js/__tests__/Collapse.test.ts
packages/web/src/scss/components/Accordion/README.md
packages/web/src/scss/components/Accordion/index.html

It is not used anywhere in the JS. It was probably replaced by data-spirit-parent and someone forgot to remove this.
DS-883
---

Fix(web): Remove unused data attribute in Accordion #DS-883

---

packages/web/src/scss/components/Button/_Button.scss
packages/web/src/scss/components/Pagination/_Pagination.scss
packages/web/src/scss/foundation/_links.scss
packages/web/src/scss/helpers/links/_links.scss

Currently, hover state overrode active on click, because you were still hovering. So active has to be set after hover as mentioned in [w3schools](https://www.w3schools.com/cssref/sel_active.php#:~:text=Note%3A%20%3Aactive%20MUST%20come%20after%20%3Ahover%20(if%20present)%20in%20the%20CSS%20definition%20in%20order%20to%20be%20effective). We also decided to keep the order hover, focus and active. So I fixed this everywhere. 
---

Fix(web): Set correct order of hover, focus and active states in CSS

---

packages/web-twig/src/Resources/components/Accordion/README.md
packages/web-twig/src/Resources/components/Button/README.md
packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
packages/web-twig/src/Resources/components/ButtonLink/README.md
packages/web-twig/src/Resources/components/Collapse/README.md
packages/web-twig/src/Resources/components/FieldGroup/README.md
packages/web-twig/src/Resources/components/FileUploader/README.md
packages/web-twig/src/Resources/components/Header/README.md
packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
packages/web-twig/src/Resources/components/Heading/README.md
packages/web-twig/src/Resources/components/Link/Link.twig
packages/web-twig/src/Resources/components/Link/README.md
packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Pagination/README.md
packages/web-twig/src/Resources/components/Tabs/README.md
packages/web-twig/src/Resources/components/Tag/README.md
packages/web-twig/src/Resources/components/Text/README.md
packages/web-twig/src/Resources/components/Text/Text.twig
packages/web-twig/src/Resources/components/TextArea/README.md
packages/web-twig/src/Resources/components/TextField/README.md
packages/web-twig/src/Resources/components/TextFieldBase/README.md

- Document all allowed HTML attributes in all components
- Unify the syntax of boolean props
Partially relates to #957.

Docs: Twig allowed attributes

---

packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/types/fileUploader.ts

Add deprecations to `FileUploaderAttachment` button label props.
Deprecate prop `buttonLabel`, use `removeText` instead. 
Deprecate prop `editButtonLabel`, use `editText` instead.
Changing props from `buttonLabel` -> `removeText` and `editButtonLabel` -> `editText` for better match with other text props across project.
[DS-881 FileUploader má rozdílně pojmenované API](https://jira.lmc.cz/browse/DS-881)

Feat(web-react): Deprecate props in FileUploaderAttachment DS-881

---

packages/web/src/scss/components/Radio/_Radio.scss

The edges of selected `Radio` input should now be smooth and not pixelated.
It seems we can have either printer-friendly, or Windows-HCM-friendly inputs, not both.
🙏🏻 Test on a non-high-dpi display is necessary (I don't have one).

Fix(web): Drop support of Windows high contrast mode in `Radio` to fix antialiasing issues

---

packages/web-react/src/components/FieldGroup/FieldGroup.tsx

* causing `UNSAFE_style` be placed on DOM element during test
---

Fix(web-react): The rest props were transfered twice on FieldGroup

---

packages/web-react/src/components/FileUploader/__tests__/useFileQueue.test.ts

Replacing Date.now with static value.
https://jira.lmc.cz/browse/DS-766
---

Test(web-react): Unnecessary use of `Date.now` refs #DS-766

---

apps/web-twig-demo/config/packages/spirit_web_twig.yaml
apps/web-twig-demo/public/css/demo.css
packages/web-twig/docs/components/DocsBox/DocsBox.twig
packages/web-twig/docs/components/DocsBox/__tests__/DocsBoxSnapshotTest.php
packages/web-twig/docs/components/DocsBox/__tests__/__fixtures__/docsBoxDefault.twig
packages/web-twig/docs/components/DocsBox/__tests__/__snapshots__/docsBoxDefault.twig.snap.html
packages/web-twig/docs/components/DocsSection/DocsSection.twig
packages/web-twig/docs/components/DocsSection/__tests__/DocsSectionSnapshotTest.php
packages/web-twig/docs/components/DocsSection/__tests__/__fixtures__/docsSectionDefault.twig
packages/web-twig/docs/components/DocsSection/__tests__/__snapshots__/docsSectionDefault.twig.snap.html
packages/web-twig/docs/twig-components/docsBox.twig
packages/web-twig/docs/twig-components/docsSection.twig
packages/web-twig/phpunit.xml.dist
packages/web-twig/src/Resources/components/Pill/__tests__/PillSnapshotTest.php
packages/web-twig/tests/Helper/TwigHelper.php

- New components: `DocsSection`, `DocsBox`.
- CSS class `docs-FormFieldGrid` has been dropped.
`DocsSection` displays title and automatically provides proper spacing to its content.
Before:
```html
<section class="docs-Section">
<h2 class="docs-Heading">
Basic Usage
<span class="Tag Tag--warning Tag--medium Tag--subtle">Visual demo only</span>
</h2>
<div class="docs-FormFieldGrid">
<div class="docs-Box">…</div>
</div>
</section>
```
After:
```twig
<DocsSection title="Basic Usage" tag="Visual demo only">
<DocsBox>…</DocsBox>
</DocsSection>
```
https://jira.lmc.cz/browse/DS-837

Docs(web-twig): Introduce `DocsSection` and `DocsBox` components

---

packages/web-react/src/components/Dialog/Dialog.tsx
packages/web-react/src/components/Modal/ModalHeader.tsx
packages/web-react/src/components/Modal/demo/ModalStacked.tsx
packages/web-react/src/hooks/__tests__/useClickOutside.test.ts
packages/web-react/src/hooks/useClickOutside.ts

refs #DS-937
When using a form inside the Modal the click and submit of the form should work.
The click to form, checkbox, and submit was prevented from defaulting due to the cooperation of nesting modals.
https://jira.lmc.cz/browse/DS-937
---

Fix(web-react): Handle event capturing correctly in Dialog

---

packages/web-react/config/jest/config.js

* fixing:
```
jest-haste-map: Haste module naming collision: @lmc-eu/spirit-web-react The following files share their name; please adjust your hasteImpl:
* <rootDir>/dist/package.json
* <rootDir>/package.json
```
This message was displayed in the console when running tests and when there were build files in the `dist` directory.
---

Test(web-react): Ignore module pattern for `dist` directory

---

packages/web-react/src/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/README.md
packages/web/src/scss/components/Modal/README.md

I suppose there still may be some inconsistencies, please let me know if you find anything!
https://jira.lmc.cz/browse/DS-876

Docs(web, web-react, web-twig): Unify `Modal` READMEs

---

packages/web-react/src/components/Pagination/demo/PaginationCurrentFirst.tsx
packages/web-react/src/components/Pagination/demo/PaginationCurrentFirstCentered.tsx
packages/web-react/src/components/Pagination/demo/PaginationCurrentLast.tsx
packages/web-react/src/components/Pagination/demo/PaginationCurrentMiddle.tsx
packages/web-react/src/components/Pagination/demo/index.tsx
packages/web/src/scss/components/Pagination/index.html

Pagination demo is now same in all packages
[Demo: Pagination má ve všech technologiích stejná dema](https://jira.lmc.cz/browse/DS-903)

Docs(web-react, web): Add Pagination demo #DS-903

---

packages/web-twig/.gitattributes

Fixing configuration of the web-twig-bundle package which includes tests and stories and this should not happen.
Thanks @janicekt for this notice.
You can reproduce the package archive by running `git archive --format=tar.gz -o web-twig-test.tar.gz HEAD` in `packages/web-twig`.
https://jira.lmc.cz/browse/DS-969
---

Chore(web-twig): Ignore tests and stories from exported package

---

packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/Button/ButtonLink.tsx

While investigating problems with types and polymorphism of Button and ButtonLink components I have fixed some ESlint issues.
- reordering of imports
- restructuring of props
---

Fix some code styl problem on Button components

---

packages/web/src/scss/components/Stack/_Stack.scss

Fix(web): Prevent from removing spacing from Stack first child element

---

packages/web-react/src/components/Modal/ModalCloseButton.tsx
packages/web-react/src/components/Modal/ModalHeader.tsx
packages/web-react/src/components/Modal/__tests__/ModalCloseButton.test.tsx
packages/web-react/src/components/Modal/index.ts
packages/web-react/src/types/modal.ts

This contribution has been, somehow, lost.
https://github.com/lmc-eu/spirit-design-system/pull/1046
---

Refactor(web-react): Introduce `ModalCloseButton` component

---

packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/web-react/src/components/Breadcrumbs/BreadcrumbsItem.tsx
packages/web-react/src/components/Breadcrumbs/README.md
packages/web-react/src/components/Breadcrumbs/__tests__/BreadcrumbsItem.test.tsx
packages/web-react/src/components/Breadcrumbs/__tests__/useBreadcrumbsStyleProps.test.ts
packages/web-react/src/components/Breadcrumbs/demo/BreadcrumbsCustom.tsx
packages/web-react/src/components/Breadcrumbs/demo/BreadcrumbsDefault.tsx
packages/web-react/src/components/Breadcrumbs/index.ts
packages/web-react/src/components/Breadcrumbs/stories/BreadcrumbsItem.stories.tsx
packages/web-react/src/components/Breadcrumbs/useBreadcrumbsStyleProps.ts
packages/web-react/src/types/breadcrumbs.ts
packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.twig
packages/web-twig/src/Resources/components/Breadcrumbs/BreadcrumbsItem.twig
packages/web-twig/src/Resources/components/Breadcrumbs/README.md
packages/web-twig/src/Resources/components/Breadcrumbs/__tests__/__fixtures__/breadcrumbsDefault.twig
packages/web-twig/src/Resources/components/Breadcrumbs/__tests__/__snapshots__/breadcrumbsDefault.twig.snap.html
packages/web-twig/src/Resources/components/Breadcrumbs/stories/BreadcrumbsCustom.twig
packages/web-twig/src/Resources/components/Breadcrumbs/stories/BreadcrumbsDefault.twig
packages/web-twig/src/Resources/twig-components/breadcrumbsItem.twig
packages/web/src/scss/components/Breadcrumbs/index.html

* and refactor Breadcrumbs to use it
refs #DS-835
Refactoring of Breadcrumbs to simplify the usage of the component by adding the new `BreadcrumbsItem` subcomponent to render items more easily.
There was a concept of the two slots for icons - `iconStart` and `iconEnd`. Now we agreed that props for icon names would be just enough - `iconNameStart` and `iconNameEnd`.
Also, the arrows were switched from the original implementation. Now the default arrow is on the end for better manipulation in coditions.
https://jira.lmc.cz/browse/DS-835
---

Feat(web-react): Introduce BreadcrumbsItem component

---

packages/web/README.md

Docs(web): Add CDN links for quick usage of the `spirit-web` package

---

docs/DICTIONARIES.md
packages/web/src/scss/components/Dropdown/README.md
packages/web/src/scss/components/Dropdown/_Dropdown.scss
packages/web/src/scss/components/Dropdown/_DropdownWrapper.scss
packages/web/src/scss/components/Dropdown/_theme.scss
packages/web/src/scss/components/Dropdown/index.html
packages/web/src/scss/components/Tooltip/README.md
packages/web/src/scss/components/Tooltip/_Tooltip.scss
packages/web/src/scss/components/Tooltip/_TooltipWrapper.scss
packages/web/src/scss/components/Tooltip/_theme.scss
packages/web/src/scss/components/Tooltip/_tools.scss
packages/web/src/scss/components/Tooltip/index.html
packages/web/src/scss/settings/_dictionaries.scss
packages/web/src/scss/tools/_dictionaries.scss
packages/web/src/scss/tools/_list.scss
packages/web/src/scss/tools/_placement.scss
packages/web/src/scss/tools/_string.scss

- Introduce Placement dictionary
- Use it in `Dropdown` and `Tooltip` components
https://jira.lmc.cz/browse/DS-923

Feat(web): Introduce Placement dictionary and use it in `Dropdown` and `Tooltip` #DS-923

---

apps/web-twig-demo/assets/scripts/file-uploader-meta-data.ts
apps/web-twig-demo/webpack.config.js
packages/web-react/src/components/FileUploader/AttachmentImagePreview.tsx
packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
packages/web-react/src/components/FileUploader/FileUploaderList.tsx
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/components/FileUploader/__tests__/FileUploaderList.test.tsx
packages/web-react/src/components/FileUploader/__tests__/useFileQueue.test.ts
packages/web-react/src/components/FileUploader/__tests__/useFileUploaderStyleProps.test.ts
packages/web-react/src/components/FileUploader/demo/FileUploaderMetaData.tsx
packages/web-react/src/components/FileUploader/demo/index.tsx
packages/web-react/src/components/FileUploader/useFileQueue.ts
packages/web-react/src/components/FileUploader/useFileUploaderAttachment.ts
packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
packages/web-react/src/components/FileUploader/utils.ts
packages/web-react/src/constants/dictionaries.ts
packages/web-react/src/types/fileUploader.ts
packages/web-twig/src/Resources/components/FileUploader/FileUploader.stories.twig
packages/web-twig/src/Resources/components/FileUploader/stories/FileUploaderMetaData.twig
packages/web/src/js/FileUploader.ts
packages/web/src/js/__tests__/FileUploader.test.ts
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/_FileUploaderAttachment.scss
packages/web/src/scss/components/FileUploader/index.html

Feat(web, web-react): FileUploader: show cropped image #DS-954

---

netlify.toml
packages/web-react/netlify.toml

* caused build fails by rejecting the local cache during Netlify builds
* @see: https://answers.netlify.com/t/ support-guide-nx-monorepo-site-does-not-reflect-changes-after-build/73657
* @see: https://nx.dev/recipes/troubleshooting/unknown-local-cache
@pavelklibani This is the root of the problem of why your Netlify builds failed. IMHO
---

Chore(ci): Skip Nx cache on Netlify builds

---

packages/web-react/src/components/Dialog/Dialog.tsx
packages/web-react/src/hooks/useClickOutside.ts

- Moved logic for modal to modal callback from useClickOutside hook
[web-react: useClickOutside nefunguje v Dropdownu](https://jira.lmc.cz/browse/DS-945)

Fix(web-react): ClickOutside working with Dialog and Dropdown #DS-945

---

packages/web-react/src/components/Pagination/README.md
packages/web-react/src/components/Pagination/UncontrolledPagination.tsx
packages/web-react/src/components/Pagination/__tests__/UncontrolledPagination.test.tsx
packages/web-react/src/components/Pagination/index.ts
packages/web-react/src/components/Pagination/stories/UncontrolledPagination.stories.tsx
packages/web-react/src/components/Pagination/usePagination.tsx
packages/web-react/src/types/pagination.ts

I am introducing a new Pagination component.
Based on https://github.com/lmc-eu/spirit-design-system/pull/738
---

Feat(web-react): Uncontrolled Pagination component

---

packages/web-react/src/components/Dropdown/Dropdown.tsx
packages/web-react/src/components/Dropdown/README.md
packages/web-react/src/components/Dropdown/__tests__/useDropdownStyleProps.test.ts
packages/web-react/src/components/Dropdown/stories/Dropdown.stories.tsx
packages/web-react/src/components/Dropdown/useDropdownStyleProps.ts
packages/web-react/src/components/Tooltip/README.md
packages/web-react/src/components/Tooltip/__tests__/useTooltipStyleProps.test.ts
packages/web-react/src/components/Tooltip/demo/TooltipOnHover.tsx
packages/web-react/src/components/Tooltip/demo/TooltipPlacements.tsx
packages/web-react/src/components/Tooltip/demo/index.tsx
packages/web-react/src/components/Tooltip/stories/Tooltip.stories.tsx
packages/web-react/src/components/Tooltip/stories/UncontrolledTooltip.stories.tsx
packages/web-react/src/components/Tooltip/useTooltipStyleProps.ts
packages/web-react/src/constants/dictionaries.ts
packages/web-react/src/types/dropdown.ts
packages/web-react/src/types/shared/dictionaries.ts
packages/web-react/src/types/tooltip.ts
packages/web-react/src/utils/__tests__/string.test.ts
packages/web-react/src/utils/index.ts
packages/web-react/src/utils/string.ts

https://jira.lmc.cz/browse/DS-923

Use the new Placement dictionary in `Dropdown` and `Tooltip` #DS-923

---

apps/web-twig-demo/assets/scripts/file-uploader-meta-data.ts
packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/components/FileUploader/__tests__/useFileUploaderStyleProps.test.ts
packages/web-react/src/components/FileUploader/constants.ts
packages/web-react/src/components/FileUploader/demo/FileUploaderMetaData.tsx
packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
packages/web/src/js/FileUploader.ts
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/index.html

* need to use additional dimensions - natural width and height to
calculate dimensions of previewed image
* also need to better calculate the scale of the entire image and also
position when we need to display the possible crop
https://almamedia.slack.com/archives/C050YPZ3YRW/p1698830929192449
https://jira.lmc.cz/browse/DS-1038
---

Fix(web-react): Recalculate FileUploader image preview by crop values

---

packages/web-react/src/components/Dropdown/README.md

- Replaced `renderToggle` with `renderTrigger` as the correct prop
Reported bug was fixed by previous changes and bug reporter confirmed that it is working. 
I just found this typo in README file.
[web-react: Dropdown nejde zavřít s a elementem jak trigger](https://jira.lmc.cz/browse/DS-601)

Docs(web-react): Corrected the example for Dropdown #DS-601

---

packages/web-react/src/components/Header/README.md
packages/web-react/src/components/Header/demo/HeaderInvertedWithActionsAndDialog.tsx
packages/web-twig/src/Resources/components/Header/README.md
packages/web-twig/src/Resources/components/Header/stories/HeaderInvertedWithActionsAndDialog.twig
packages/web/src/scss/components/Header/README.md
packages/web/src/scss/components/Header/_HeaderDialogLink.scss
packages/web/src/scss/components/Header/_HeaderDialogNav.scss
packages/web/src/scss/components/Header/_HeaderLink.scss
packages/web/src/scss/components/Header/_HeaderNav.scss
packages/web/src/scss/components/Header/_HeaderNavItem.scss
packages/web/src/scss/components/Header/_tools.scss
packages/web/src/scss/components/Header/index.html

These are both `HeaderNavItem` components:
Previously, the content of `HeaderNavItem` was always stretched over its height:
https://jira.lmc.cz/browse/DS-1044

Allow combining links and buttons in `HeaderDesktopActions`

---

packages/web-react/package.json
packages/web-react/src/components/Icon/Icon.tsx
packages/web-react/src/components/Icon/README.md
packages/web-react/src/utils/htmlParser.ts
yarn.lock

* `dangerouslySetInnerHtml` does not work while rendering on the server
* this `Warning: Prop `dangerouslySetInnerHTML` did not match.` error was raised
* we can avoid this by wrapping the component with something like `<NoSsr>`
* @see: https://stackoverflow.com/questions/64079321/react-tooltip-and-next-js-ssr-issue
* or by using some library like ReactHtmlParser to render HTML string magically as a component
* @see: https://www.npmjs.com/package/react-html-parser
https://www.npmjs.com/package/react-html-parser
https://github.com/peternewnham/react-html-parser
https://stackoverflow.com/questions/39758136/how-to-render-html-string-as-real-html
https://stackoverflow.com/questions/64079321/react-tooltip-and-next-js-ssr-issue
---

Fix(web-react): Icon component supports SSR

---

packages/web-react/src/components/Tooltip/Tooltip.tsx
packages/web-react/src/components/Tooltip/TooltipCloseButton.tsx
packages/web-react/src/components/Tooltip/TooltipWrapper.tsx
packages/web-react/src/components/Tooltip/UncontrolledTooltip.tsx
packages/web-react/src/components/Tooltip/demo/TooltipOnHover.tsx
packages/web-react/src/components/Tooltip/demo/TooltipPlacements.tsx
packages/web-react/src/components/Tooltip/demo/index.tsx
packages/web-react/src/components/Tooltip/index.ts
packages/web-twig/src/Resources/components/Tooltip/Tooltip.stories.twig
packages/web-twig/src/Resources/components/Tooltip/stories/TooltipOnHover.twig
packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig
packages/web/src/scss/components/Tooltip/index.html

I have tried to showcase the values of the placement dictionary the same way as the Floating UI does on its webpage.
https://jira.lmc.cz/browse/DS-923
---

Docs(web): Showcase placement valuse on Tooltip demo

---

packages/icons/README.md
packages/icons/scripts/buildSvg.js

Feat(icons): Do not remove colors from icons with `-colored` suffix #DS-990

---

packages/web/src/scss/components/Button/_Button.scss
packages/web/src/scss/components/FileUploader/_FileUploaderInput.scss
packages/web/src/scss/foundation/_links.scss
packages/web/src/scss/helpers/links/_links.scss
packages/web/src/scss/helpers/links/index.html
packages/web/src/scss/settings/_cursors.scss
packages/web/src/scss/settings/_links.scss
packages/web/src/scss/tools/_dictionaries.scss
packages/web/src/scss/tools/_links.scss
packages/web/src/scss/tools/_reset.scss

Using `<button>` element for links is now possible:
```html
<button class="link-primary">Link button</button>
```
https://jira.lmc.cz/browse/DS-1060
Also, disabled buttons no longer obtain underline on hover:
https://jira.lmc.cz/browse/DS-1042

Feat(web): Enable `<button>` elements to be styled as links

---

packages/web-react/src/components/Link/Link.tsx
packages/web-react/src/components/Link/README.md
packages/web-react/src/types/link.ts
packages/web-react/src/types/shared/element.ts

Fix(web-react): Polymorph Link component types #DS-1060

---

Makefile

* verify-access --verify-access=false and --no-verify-access are no longer needed
* the legacy preemptive access verification is now disabled by default
* requests will fail with appropriate errors when not authorized correctly
refs #32
---

Chore(repo): Remove lerna option for disabling verification

---

packages/design-tokens/package.json

* affects only Webpack
* when the `exports` field is specified, only these module requests are available
* any other requests will lead to a ModuleNotFound Error
https://webpack.js.org/guides/package-exports/#conditions
---

Fix(design-tokens): Use `sass` condition in `exports` field

---

packages/web-react/src/components/Icon/Icon.tsx

* while building on Next.js the `TypeError: htmlParser is not a function` was raised
---

Fix(web-react): Check `htmlParser` for function type

---

packages/web-react/src/components/Accordion/demo/AccordionBasic.tsx
packages/web-react/src/components/Accordion/demo/AccordionOneItemOpenAtATime.tsx

- Fixed errors about labelledById in console
- Fixed basic accordion demo (all items could be opened, not just one as in other demo)
Removed `id` and `labelledById` because ARIA props are handled by `useAccordionAriaProps` hook. 
These properties were mistakenly copied from the Twig demo.
[web-react: Accordeon chyby v DOM](https://jira.lmc.cz/browse/DS-948)

Fix(web-react): Accordion DOM errors #DS-948

---

packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabContent.tsx
packages/web-react/src/components/Tabs/TabItem.tsx
packages/web-react/src/components/Tabs/TabList.tsx
packages/web-react/src/components/Tabs/TabPane.tsx
packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
packages/web-react/src/components/Tabs/__tests__/TabLink.test.tsx
packages/web-react/src/components/Tabs/__tests__/TabList.test.tsx
packages/web-react/src/components/Tabs/__tests__/TabPane.test.tsx

- Added `styleProps` to **TabsContent**, **TabItem**, **TabList** and **TabPane**
- `UNSAFE_className` and `UNSAFE_style` added to API tables for **TabsContent**, **TabItem**, **TabList** and **TabPane**
[React: Tabs nemají styleProps](https://jira.lmc.cz/browse/DS-977)

Fix(web-react): Tabs styleProps #DS-977

---

packages/web-react/src/components/FileUploader/useFileUploaderInput.ts
packages/web/src/js/FileUploader.ts
packages/web/src/js/__tests__/FileUploader.test.ts

- FileUploader error messages changed to match across all packages
- They are now formated like this: `<filename>: <error message>`
[FileUploader: nekonzistence v error hlášce](https://jira.lmc.cz/browse/DS-1051)

Fix(web, web-react): FileUploader error messages

---

packages/web-react/src/components/Dialog/useDialog.ts
packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
packages/web-react/src/hooks/index.ts
packages/web-react/src/hooks/useScrollControl.ts

Draft till next sprint. 
DS-1052
---

Fix(web-react): Add useScrollControl hook and block scrolling when Dialog open #DS-1052

---

packages/web/src/scss/components/Accordion/_Accordion.scss

* Header background is now always on the same (pseudo) element so nothing gets overlapped when colors change.
* Stacking of header elements has been slightly refactored while retaining the intended behavior.
* Component styles have been thoroughly documented so next time we don't have to spend a day on it.
https://jira.lmc.cz/browse/DS-1074
---
This PR replaces PR #1157.

Fix(web): Refactor `Accordion` styles to fully support theming via design tokens #DS-1074

---

packages/design-tokens/package.json

* missing scss/borders specifier or cannot find stylesheet to import
---

Fix(design-tokens): Exports field blocks build on product applications

---

packages/web-twig/src/Resources/components/Grid/GridItem.twig
packages/web-twig/src/Resources/components/Grid/__tests__/__fixtures__/gridItemDefault.twig
packages/web-twig/src/Resources/components/Grid/__tests__/__snapshots__/gridItemDefault.twig.snap.html
packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html

Small bug fix. Currently it is `class` even passed to the `style` attribute.
❌ Current HTML output:
```
<div class="GridItem d-tablet-none" style="--grid-item-column-start: 1;display-tablet-none">
```
✅ Fixed HTML output:
```
<div class="GridItem d-tablet-none" style="--grid-item-column-start: 1;">
```

Fix(web-twig): Do not render class in the `style` attribute of the `GridItem`

---

packages/web-react/src/components/Dialog/Dialog.tsx
packages/web-react/src/components/Modal/Modal.tsx

- Changed default value of `closeOnBackdropClick` to true on `<Dialog />` component.
- Removed default value of `closeOnBackdropClick` from `<Modal />` (will be default from Dialog)
[HeaderDialog v React se nezavírá při backdrop click](https://jira.lmc.cz/browse/DS-1075)

Fix(web-react): HeaderDialog demo missed closeOnBackdropClick prop #DS-1075

---

packages/web-react/src/components/Header/HeaderDialogLink.tsx
packages/web-react/src/components/Header/HeaderLink.tsx
packages/web-react/src/components/Header/README.md
packages/web-react/src/components/Header/__tests__/HeaderDialogLink.test.tsx
packages/web-react/src/components/Header/__tests__/HeaderLink.test.tsx
packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabLink.tsx
packages/web-react/src/components/Tabs/__tests__/TabLink.test.tsx
packages/web-react/src/components/Tabs/stories/TabLink.stories.tsx
packages/web-react/src/types/header.ts
packages/web-react/src/types/tabs.ts

- `<TabLink />` and `<HeaderLink />` now accept a **NextLink** and have **forwardRef** support
- Added tests for elementTypes
- `<HeaderDialogLink />` now accept a **NextLink** and have **forwardRef** support
- Added tests for elementTypes
[DS-1018 - TabLink komponenty umí akceptovat NextLink komponentu](https://jira.lmc.cz/browse/DS-1018)
[DS-1003 - HeaderDialogLink musí podporovat ref forwarding](https://jira.lmc.cz/browse/DS-1003)

Fix(web-react): TabLink, HeaderLink and HeaderDialogLink now accept a NextLink #DS-1018 #DS-1003

---

packages/web-twig/src/Resources/components/Tooltip/Tooltip.stories.twig
packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltip.twig
packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltip.twig.snap.html
packages/web-twig/src/Resources/components/Tooltip/stories/TooltipFloatingUI.twig
packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig

Switch to data attribute placement instead of modification class based.
DS-1084
---

Feat(web-twig): Introduce Full Floating UI demo to Tooltip, update internal implementation #DS-1084

---

packages/web-twig/src/Twig/SvgExtension.php

* Cannot call method addAttribute() on SimpleXMLElement|null.
---

Style(web-twig): Fix PHPStan issue with adding SimpleXMLElement

---

packages/analytics/src/constants.ts
packages/analytics/src/processors/spiritAdoptionProcessor.ts
packages/analytics/src/scanners/twig-scanner.config.ts

Adding a time mark to the files with scanner results; e. g. `adoption-data-<type>-YYYY-MM-DD.json`
---

Feat(analytics): Add a timestamp to the scanner result files

---

packages/analytics/src/scanners/__tests__/twigScanner.test.ts
packages/analytics/src/scanners/twigScanner.ts

Double-check the component name and assert it for PascalCase, because HTML elements are not PascalCase written.
In our adoption data, we have some components marked as `html_element`.
```
"html_element:ProgressBar": [
{
"path": "templates/front/macros/rating.html.twig:221",
"props": {
"size": "small",
"value": "{{ percentage }}"
}
}
],
```
---

Fix(analytics): HTML element is not the PascalCase component

---

.commitlintrc.js
.eslintrc.js
.github/workflows/e2e.yml
README.md
bin/make/e2e.sh
packages/common/.eslintignore
packages/common/.eslintrc.js
packages/common/.gitignore
packages/common/CHANGELOG.md
packages/common/LICENSE.md
packages/common/README.md
packages/common/config/jest/config.ts
packages/common/constants/__tests__/environments.test.ts
packages/common/constants/__tests__/servers.test.ts
packages/common/constants/environments.ts
packages/common/constants/servers.ts
packages/common/package.json
packages/common/tsconfig.json
packages/form-validations/config/vite/app.ts
packages/form-validations/package.json
packages/web-react/config/vite/app.ts
packages/web-react/package.json
packages/web/package.json
packages/web/vite.config.ts
tests/e2e/demo-homepages.spec.ts

Introducing a new package `spirit-common` where are stored shared features, scripts and code.
E2E test can be now run against production URLs of development ones. Just set env variable `CI` to `true` for production urls.
The visual regression testing will be only run when the `e2e` label is used in PR.
https://jira.lmc.cz/browse/DS-1093
---

Run visual tests also againts local servers

---

packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Modal/_Modal.scss
packages/web/src/scss/components/Modal/_ModalDialog.scss
packages/web/src/scss/components/Modal/_ModalHeader.scss
packages/web/src/scss/components/Modal/_theme.scss
packages/web/src/scss/components/Modal/index.html
packages/web/src/scss/settings/_feature-flags.scss

Add `spirit-feature-modal-enable-uniform-dialog` feature class to enable uniform appearance of `Modal` across all breakpoints.
Current mobile design is then accessible using the `Modal--dockOnMobile` modifier class.
We need to make sure it works in all scenarios:
1. Current behavior must remain intact.
2. New appearance can be turned on via CSS class,
3. … or via Sass feature flag.
https://jira.lmc.cz/browse/DS-1091

Introduce optional uniform appearance of `Modal` #DS-1091

---

packages/web/package.json

`string.split` is in Sass since 1.57.0
https://sass-lang.com/documentation/modules/string/#split
---

Chore(web): Require `sass` from v1.57.0 above due to `string.split`

---

packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalDisabledBackdropClick.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalStacking.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig

Add `spirit-feature-modal-enable-uniform-dialog` feature class to enable uniform appearance of `Modal` across all breakpoints.
Current mobile design is then accessible using the `isDockedOnMobile` property.
We need to make sure it works in all scenarios:
1. Current behavior must remain intact.
2. New appearance can be turned on via CSS class,
3. … or via Sass feature flag.
https://jira.lmc.cz/browse/DS-1091

Twig: Introduce optional uniform appearance of `Modal`

---

packages/web-react/src/hooks/__tests__/styleProps.test.ts
packages/web-react/src/hooks/styleProps.ts

When not using `UNSAFE_style` prop, the default `{}` is rendered into the DOM. Using `undefined` instead.
Every snapshot in product, like KukAD:
```js
<ul
className="Tabs"
role="tablist"
style={{}} // <- here
>
```
---

Fix(web-react): Do not render empty `style` prop

---

packages/common/LICENSE.md
packages/common/constants/__tests__/environments.test.ts
packages/common/constants/environments.ts
packages/common/utilities/__tests__/info.test.ts
packages/common/utilities/__tests__/warning.test.ts
packages/common/utilities/index.ts
packages/common/utilities/info.ts
packages/common/utilities/warning.ts
packages/form-validations/src/FormValidations.ts
packages/web-react/config/webpack.common.js
packages/web-react/src/components/Button/__tests__/useButtonStyleProps.test.ts
packages/web-react/src/components/Button/useButtonStyleProps.ts
packages/web-react/src/components/ButtonLink/__tests__/useButtonLinkStyleProps.test.ts
packages/web-react/src/components/ButtonLink/useButtonLinkStyleProps.ts
packages/web-react/src/components/FileUploader/useFileUploaderInput.ts
packages/web-react/src/components/FileUploader/utils.ts
packages/web-react/src/components/Icon/Icon.tsx
packages/web-react/src/hooks/__tests__/styleProps.test.ts
packages/web-react/src/hooks/styleProps.ts
packages/web-react/src/hooks/useDeprecationMessage.ts
packages/web-react/tests/providerTests/stylePropsTest.tsx
packages/web/src/js/FileUploader.ts
packages/web/src/js/Modal.ts
packages/web/src/js/Offcanvas.ts
packages/web/src/js/utils/Deprecations.ts

Introduce `info` and `warning` common utilities and refactor the usage of the `Console` functions
- https://www.npmjs.com/package/tiny-warning
- https://github.com/zertosh/invariant/tree/master
- https://github.com/alexreardon/tiny-warning/tree/master
https://jira.lmc.cz/browse/DS-767
---

Introduce `info` and `warning` common utilities

---

packages/web-twig/src/Resources/components/Grid/GridItem.twig
packages/web-twig/src/Resources/components/Grid/__tests__/__fixtures__/gridItemDefault.twig
packages/web-twig/src/Resources/components/Grid/__tests__/__snapshots__/gridItemDefault.twig.snap.html

I was going around… Small nitpicking. ✨ ⛏️ 
When we needed to send a `null` value to a prop, the CSS property was generated without an assigned value.
**Source code from Jobs.cz**
```
<GridItem
columnStart="{{ gridItemColumnStart ? gridItemColumnStart[loop.index] : null }}"
columnEnd="{{ gridItemColumnEnd ? gridItemColumnEnd[loop.index] : null }}"
rowStart="{{ gridItemRowStart ? gridItemRowStart[loop.index] : null }}"
rowEnd="{{ gridItemRowEnd ? gridItemRowEnd[loop.index] : null }}"
>
<MedallionGalleryImage image="{{ image }}" />
</GridItem>
```
→ 
😞 **Current output**
```
<div
class="GridItem"
style="--grid-item-column-start: ;--grid-item-column-end: ;--grid-item-row-start: ;--grid-item-row-end: ;"
>...</div>
```
✨ **Upcoming output**
```
<div class="GridItem">...</div>
```

Fix(web-twig): Do not render CSS property in the `GridItem` style attribute if the value is empty

---

packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
packages/web-twig/src/Resources/components/Modal/Modal.twig
packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDisabledBackdropClick.twig.snap.html
packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig

New `alignmentY` option can be set to `top`, `center` (default), or `bottom`.
https://jira.lmc.cz/browse/DS-940

Feat(web-twig): Introduce vertical alignment options for `Modal` #DS-940

---

packages/web-react/src/components/FileUploader/constants.ts
packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
packages/web-react/src/components/ScrollView/useScrollPosition.ts
packages/web-react/src/constants/dictionaries.ts
packages/web-react/src/constants/index.ts
packages/web-react/src/constants/position.ts
packages/web-react/src/types/shared/alignments.ts
packages/web-react/src/types/shared/colors.ts
packages/web-react/src/types/shared/dictionaries.ts
packages/web-react/src/types/shared/index.ts
packages/web-react/src/types/shared/positions.ts

- Keep only our [approved dictionaries](https://github.com/lmc-eu/spirit-design-system/blob/main/docs/DICTIONARIES.md) in `types/shared/dictionaries.ts`.
- Move everything else either to components (`FileUploader`), or to shared constants with a non-confusing name (`ScrollView` positions).
I found out some inconsistencies in our shared types and constants when I started my work on `Modal` alignment.

Refactor(web-react): Clean up shared non-dictionary types and constants

---

.github/workflows/e2e.yml

We have agreed that we will be using the label `run visual tests` for PRs where we want to run visual tests.
The label `e2e` is removed.
---

Chore(ci): Rename label that runs visual tests on PR

---

packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
packages/web-react/src/hooks/useScrollControl.ts

When the use of the Dialog in page is optimized by the conditions like `isOpen && <Dialog />`, the Dialog component will be unmounted sooner than the Dialog is closed correctly and all side effects are fulfilled.
In this case, the class and style attributes added to the body element will not be removed, and the page will be scrolled.
https://jira.lmc.cz/browse/DS-1126
---

Fix(web-react): Cleanup scrolling when Modal is unmounted

---

packages/web-react/README.md
packages/web-react/src/components/Button/demo/ButtonDemoFactory.tsx
packages/web-react/src/components/Button/stories/Button.stories.tsx
packages/web-react/src/components/ButtonLink/demo/ButtonLinkDemoFactory.tsx
packages/web-react/src/components/ButtonLink/stories/ButtonLink.stories.tsx
packages/web-react/src/components/Dropdown/demo/DropdownPlacements.tsx
packages/web-react/src/components/Dropdown/stories/Dropdown.stories.tsx
packages/web-react/src/components/DropdownModern/demo/DropdownModernPlacements.tsx
packages/web-react/src/components/DropdownModern/stories/DropdownModern.stories.tsx
packages/web-react/src/components/DropdownModern/stories/DropdownPopover.stories.tsx
packages/web-react/src/components/DropdownModern/stories/UncontolledDropdown.stories.tsx
packages/web-react/src/components/Header/demo/HeaderSimpleTransparent.tsx
packages/web-react/src/components/Modal/demo/ModalDefault.tsx
packages/web-react/src/components/ScrollView/demo/ScrollViewHorizontalBreakout.tsx
packages/web-react/src/components/ScrollView/demo/ScrollViewOverflowDecorators.tsx
packages/web-react/src/components/Tooltip/demo/TooltipOnHover.tsx
packages/web-react/src/components/Tooltip/demo/TooltipPlacements.tsx
packages/web-react/src/constants/index.ts
packages/web-react/src/constants/style.ts
packages/web-react/src/hooks/__tests__/styleProps.test.ts
packages/web-react/src/hooks/__tests__/useStyleUtilities.test.ts
packages/web-react/src/hooks/styleProps.ts
packages/web-react/src/hooks/useStyleUtilities.ts
packages/web-react/src/icons/demo/icons.tsx
packages/web-react/src/types/shared/style.ts
packages/web-react/src/types/shared/tokens.ts
packages/web-react/src/types/stack.ts
packages/web-react/tests/providerTests/stylePropsTest.tsx

Feat(web-react): Introduce spacing style props to all components #DS-475

---

packages/web/.eslintrc.js
packages/web/package.json
packages/web/src/js/Tooltip.ts
packages/web/src/js/__tests__/Tooltip.test.ts
packages/web/src/scss/components/Tooltip/README.md
packages/web/src/scss/components/Tooltip/floating-ui-example.mjs
packages/web/src/scss/components/Tooltip/index.html

Feat(web): FloatingUI integration to Tooltip #DS-1086

---

packages/web-react/src/components/Modal/ModalDialog.tsx
packages/web-react/src/components/Modal/README.md
packages/web-react/src/components/Modal/__tests__/ModalDialog.test.tsx
packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
packages/web-react/src/components/Modal/demo/ModalUniformModalOnMobile.tsx
packages/web-react/src/components/Modal/stories/ModalDialog.stories.tsx
packages/web-react/src/components/Modal/useModalStyleProps.ts
packages/web-react/src/types/modal.ts
packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig
packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Modal/_Modal.scss
packages/web/src/scss/components/Modal/_ModalDialog.scss
packages/web/src/scss/components/Modal/_theme.scss
packages/web/src/scss/components/Modal/index.html

Scrolling inside `ModalDialog` can now be turned off by adding the `ModalDialog--nonScrolling` modifier class.
https://jira.almacareer.tech/browse/DS-732

Feat(web): Introduce option to disable scrolling inside `Modal` #DS-732

---

packages/web-react/src/components/FieldGroup/README.md
packages/web-twig/src/Resources/components/FieldGroup/FieldGroup.twig
packages/web-twig/src/Resources/components/FieldGroup/README.md
packages/web-twig/src/Resources/components/FieldGroup/__tests__/__fixtures__/fieldGroup.twig
packages/web-twig/src/Resources/components/FieldGroup/__tests__/__snapshots__/fieldGroup.twig.snap.html

- This is hotfix solution to be able render [Symfony Forms fields](https://symfony.com/doc/current/form/form_customization.html#form-rendering-functions)[SFF] inside FieldGroup. There is no problem to render other components such as `Text`, `Radio` or more complex `Accordion`.
- I will explain how I get to the solution below.
- Better solutions and explanations are welcomed. :pray:
--- 
There's something I don't understand.
1. ❌ Current implementation  
```
{% if block('content') is not empty %}
<div class="{{ _fieldsClassName }}">
{% block content %}{% endblock %}
</div>
{% endif %}
```
- Not possible to render SFF (via `form_row` or `form_widget`), but `form_label` is rendered! 🤯
- SFF isn't even in the `dump(block('content'))` log. 
2. ❌ Store `block('content')` into the variable  
``` …
```

Enable rendering Symfony Forms fields in `FieldGroup`

---

packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
packages/web-twig/src/Resources/components/Dropdown/README.md
packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdown.twig
packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdown.twig.snap.html
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownDisabledAutoclose.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFeatureEnhancedShadow.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthAll.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobileOnly.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownLongerContent.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownPlacements.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownVariousItems.twig

Use flow placement values, e.g. `top-left` is now `top-start`.
---

Feat(web-twig): Deprecate Dropdown non flow placements DS-1132

---

packages/web/src/scss/components/Dropdown/README.md
packages/web/src/scss/components/Dropdown/index.html
packages/web/src/scss/components/Item/README.md

Use data attribute to set the placement now.
Use flow placement values, e.g. `top-left` is now `top-start`.
---

Feat(web): Deprecate Dropdown non flow and modifier placement DS-1132

---

packages/web-react/src/components/Dropdown/Dropdown.tsx
packages/web-react/src/components/Dropdown/DropdownContext.ts
packages/web-react/src/components/Dropdown/DropdownPopover.tsx
packages/web-react/src/components/Dropdown/README.md
packages/web-react/src/components/Dropdown/__tests__/useDropdownAriaProps.test.ts
packages/web-react/src/components/Dropdown/__tests__/useDropdownStyleProps.test.ts
packages/web-react/src/components/Dropdown/demo/DropdownEnhancedShadow.tsx
packages/web-react/src/components/Dropdown/demo/DropdownFullwidthAll.tsx
packages/web-react/src/components/Dropdown/demo/DropdownFullwidthMobileOnly.tsx
packages/web-react/src/components/Dropdown/demo/DropdownPlacements.tsx
packages/web-react/src/components/Dropdown/stories/Dropdown.stories.tsx
packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts
packages/web-react/src/components/Dropdown/useDropdownStyleProps.ts
packages/web-twig/src/Resources/components/Dropdown/README.md

Use flow placement values, e.g. `top-left` is now `top-start`.
---

Feat(web-react): Deprecate Dropdown non flow placements DS-1132

---

packages/web-twig/src/Resources/components/Dropdown/stories/DropdownDisabledAutoclose.twig
packages/web-twig/src/Resources/components/Dropdown/stories/DropdownVariousItems.twig
packages/web/src/js/Dropdown.ts
packages/web/src/scss/components/Dropdown/index.html

Set `data-spirit-autoclose` to `false` in the one demo where it should be dissabled.
Strictly check data attribute value in the Dropdown plugin.
https://jira.almacareer.tech/browse/DS-1157

Fix(web): Dropdown autoclose option should be strictly checked

---

apps/web-twig-demo/docker/docker-compose.override.yml

In theory, we still support older Node versions until #DS-466 is fully resolved.

Chore(web-twig): Use Node v18 for development since the Docker image for v16 no longer exists

---

.github/CODEOWNERS
packages/codemods/.eslintignore
packages/codemods/README.md
packages/codemods/config/jest.config.js
packages/codemods/package.json
packages/codemods/scripts/copyTransforms.js
packages/codemods/src/bin/spirit-codemod.js
packages/codemods/src/bin/spirit-codemods.js
packages/codemods/src/cli.ts
packages/codemods/src/helpers/index.ts
packages/codemods/src/helpers/message.ts
packages/codemods/src/helpers/path.ts
packages/codemods/src/index.ts
packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.output.tsx
packages/codemods/src/transforms/v2/web-react/__tests__/button-text.test.ts
packages/codemods/src/transforms/v2/web-react/button-text.ts
packages/codemods/tsconfig.json
yarn.lock

🚀 Introduce a new package called `spirit-codemods` with the **first codemod for React**.
The initial codemod replaces the attribute buttonLabel with buttonText.
This codemod also includes tests.
📜 Instructions on how to run this codemod are provided in the **README.md** file.
[DS-1142 Codemod button label -> button text v codemod balíčku](https://jira.almacareer.tech/browse/DS-1142)

Feat(codmods): Introduce codemods package and first React codemod #DS-1142

---

packages/web-react/src/components/Stack/README.md
packages/web-react/src/components/Stack/__tests__/Stack.test.tsx
packages/web-react/src/components/Stack/demo/StackBlocksWithCustomSpacing.tsx
packages/web-react/src/components/Stack/demo/StackBlocksWithCustomSpacingAndDividers.tsx
packages/web-react/src/components/Stack/demo/StackBlocksWithCustomSpacingForEachBreakpoint.tsx
packages/web-react/src/components/Stack/demo/StackBlocksWithCustomSpacingFromTabletBreakpoint.tsx
packages/web-react/src/components/Stack/useStackStyleProps.ts
packages/web-twig/src/Resources/components/Stack/README.md
packages/web-twig/src/Resources/components/Stack/Stack.twig
packages/web-twig/src/Resources/components/Stack/__tests__/__fixtures__/stackDefault.twig
packages/web-twig/src/Resources/components/Stack/stories/StackBlocksWithCustomSpacing.twig
packages/web-twig/src/Resources/components/Stack/stories/StackBlocksWithCustomSpacingAndDividers.twig
packages/web-twig/src/Resources/components/Stack/stories/StackBlocksWithCustomSpacingForEachBreakpoint.twig
packages/web-twig/src/Resources/components/Stack/stories/StackBlocksWithCustomSpacingFromTabletBreakpoint.twig

For custom spacing, using the `spacing` prop alone is just fine.
The `hasSpacing` prop is still available to quickly apply default spacing.
https://jira.almacareer.tech/browse/DS-1133

`Stack` no longer requires the `hasSpacing` prop to apply custom `spacing` #DS-1133

---

packages/web-react/src/components/TextArea/TextArea.tsx
packages/web-react/src/components/TextArea/__tests__/TextArea.test.tsx
packages/web-react/src/components/TextArea/__tests__/useAdjustHeight.test.ts
packages/web-react/src/components/TextArea/useAdjustHeight.ts

Calling size adjustion when is TextArea mounted.
https://jira.almacareer.tech/browse/DS-1158

Fix(web-react): TextArea should autoresize when mounted

---

packages/codemods/CONTRIBUTING.md
packages/codemods/README.md
packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.output.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/fileuploader-prop-names.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/fileuploader-prop-names.output.tsx
packages/codemods/src/transforms/v2/web-react/__tests__/fileuploader-prop-names.test.ts
packages/codemods/src/transforms/v2/web-react/fileuploader-prop-names.ts

- Renamed `button-text` codemod to `fileuploader-prop-names`
- Updated test fixtures and tests
- Updated `README` and `CONTRIBUTING` files
Fix of https://github.com/lmc-eu/spirit-design-system/pull/1303
[DS-1142 Codemod button label -> button text v codemod balíčku](https://jira.almacareer.tech/browse/DS-1142)

Fix(codemods): FileuploaderAttachment codemods

---

DEPRECATIONS-v2.md
DEPRECATIONS-v3.md
packages/web/DEPRECATIONS-v2.md

Docs(web): List Deprecations in the web package #DS-1043

---

packages/web-react/DEPRECATIONS-v2.md
packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts

Docs(web-react): List Deprecations in the web react package #DS-1147

---

packages/web-react/src/components/Dropdown/README.md
packages/web-react/src/components/DropdownModern/README.md
packages/web-react/src/components/Tooltip/README.md
packages/web-react/src/components/Tooltip/useTooltipStyleProps.ts
packages/web-react/src/types/tooltip.ts

Feat(web-react): Deprecate `off` placement in Tooltip #DS-1078

---

packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isexpandedonmobile-prop.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isexpandedonmobile-prop.output.tsx
packages/codemods/src/transforms/v2/web-react/__tests__/fileuploader-prop-names.test.ts
packages/codemods/src/transforms/v2/web-react/__tests__/modal-isexpandedonmobile-prop.test.ts
packages/codemods/src/transforms/v2/web-react/modal-isexpandedonmobile-prop.ts
packages/codemods/tests/testUtils.ts
packages/web-react/src/components/Modal/ModalDialog.tsx
packages/web-react/src/components/Modal/README.md

React ModalDialog isExpandedOnMobile default value deprecation

---

.github/workflows/e2e.yml

- GitHub action should send message to our slack channel (_#spirit-design-system-notifications_en_)
- Created new app in Slack called `Spirit Design System Notification` - can be renamed, change color, add icon...
- Spirit team added as colaborators, so they can change and set things if needed
Links:
- [slackapi/slack-github-action](https://github.com/slackapi/slack-github-action)
- [slack api](https://api.slack.com/apps)
- [slack message builder](https://app.slack.com/block-kit-builder/)
TODO:
[Když zbuchnout e2e testy, tak nám to napíše do Slacku?](https://jira.almacareer.tech/browse/DS-1130)

Chore(GA): Send slack message on e2e test failure

---

packages/web-react/scripts/entryPoints.js
packages/web-react/src/components/Toast/README.md
packages/web-react/src/components/Toast/Toast.tsx
packages/web-react/src/components/Toast/ToastBar.tsx
packages/web-react/src/components/Toast/ToastCloseButton.tsx
packages/web-react/src/components/Toast/__tests__/Toast.test.tsx
packages/web-react/src/components/Toast/__tests__/ToastBar.test.tsx
packages/web-react/src/components/Toast/__tests__/useToastBarStyleProps.test.ts
packages/web-react/src/components/Toast/__tests__/useToastIcon.test.tsx
packages/web-react/src/components/Toast/__tests__/useToastStyleProps.test.ts
packages/web-react/src/components/Toast/constants.ts
packages/web-react/src/components/Toast/demo/ToastAlignment.tsx
packages/web-react/src/components/Toast/demo/ToastColors.tsx
packages/web-react/src/components/Toast/demo/ToastContentVariations.tsx
packages/web-react/src/components/Toast/demo/index.tsx
packages/web-react/src/components/Toast/index.html
packages/web-react/src/components/Toast/index.ts
packages/web-react/src/components/Toast/stories/Toast.stories.tsx
packages/web-react/src/components/Toast/stories/ToastBar.stories.tsx
packages/web-react/src/components/Toast/useToastBarStyleProps.ts
packages/web-react/src/components/Toast/useToastIcon.tsx
packages/web-react/src/components/Toast/useToastStyleProps.ts
packages/web-react/src/components/index.ts
packages/web-react/src/hooks/useIconName.ts
packages/web-react/src/types/index.ts
packages/web-react/src/types/toast.ts

Feat(web-react): Introduce Toast component #DS-1113

---

packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig

Follows PR #1332 
https://jira.almacareer.tech/browse/DS-939

Fix(web-twig): `Dropdown` can now be placed inside a non-scrollable `Modal` #DS-939

---

packages/web-twig/src/Resources/components/Checkbox/Checkbox.twig
packages/web-twig/src/Resources/components/Checkbox/__tests__/__fixtures__/checkboxDefault.twig
packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefault.twig.snap.html
packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefaultPure.twig.snap.html
packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxItem.twig.snap.html

Causes invalid HTML if not treated:
https://jira.almacareer.tech/browse/DS-1220

Fix(web-twig): Don't render the `name` attribute of `Checkbox` when empty

---

packages/web-react/src/components/Alert/Alert.tsx
packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/web-react/src/components/Breadcrumbs/BreadcrumbsItem.tsx
packages/web-react/src/components/Button/Button.tsx
packages/web-react/src/components/ButtonLink/ButtonLink.tsx
packages/web-react/src/components/Collapse/Collapse.tsx
packages/web-react/src/components/Collapse/UncontrolledCollapse.tsx
packages/web-react/src/components/Collapse/__tests__/UncontrolledCollapse.test.tsx
packages/web-react/src/components/Dropdown/Dropdown.tsx
packages/web-react/src/components/Field/HelperText.tsx
packages/web-react/src/components/Field/ValidationText.tsx
packages/web-react/src/components/Field/types.ts
packages/web-react/src/components/Heading/Heading.tsx
packages/web-react/src/components/Icon/Icon.tsx
packages/web-react/src/components/Link/Link.tsx
packages/web-react/src/components/Pill/Pill.tsx
packages/web-react/src/components/Stack/Stack.tsx
packages/web-react/src/components/Tag/Tag.tsx
packages/web-react/src/components/Text/Text.tsx
packages/web-react/src/components/VisuallyHidden/VisuallyHidden.tsx
packages/web-react/src/types/collapse.ts

* Support for defaultProps will be removed from function components in a future major release.
* Use JavaScript default parameters instead.
---

Refactor(web-react): Move away from the `defaultProps`

---

apps/demo/package.json
package.json
packages/design-tokens/package.json
packages/icons/package.json
yarn.lock

* the original library is unmaintained for more than 5 years
* the `npm-run-all2` is a maintenance fork
https://github.com/bcomnes/npm-run-all2

Deps(repo): Switch from `npm-run-all` to `npm-run-all2` fork

---

packages/web-react/src/utils/htmlReactParser.ts

* there is a problem in both packages with how they expose default export and how the default export is transpiled by the bundler
* so better to check if the function is defined on the `default` or not
https://almamedia.slack.com/archives/C068XPSDWQN/p1710327116206469
https://github.com/remarkablemark/html-react-parser/pull/446/files
https://jira.almacareer.tech/browse/DS-1227

Fix(web-react): Add backward compatibility for CJS when building to it

---

apps/demo/config/vite/app.ts

* there was a missing danger icon in the Alert and Toast component
* icons were resolved from node_modules instead of actual package path
- https://vitejs.dev/config/shared-options#resolve-alias
- Failed End-2-End tests: https://github.com/lmc-eu/spirit-design-system/actions/runs/8782655795/job/24097185986
- Screenshot from production demo:

Chore(demo): Correctly resolve alias to the icons in demos

---

packages/web-twig/DEPRECATIONS-v3.md
packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.twig
packages/web-twig/src/Resources/components/Breadcrumbs/README.md

Docs(web-twig): Document correctly when the goBackTitle prop is required in Breadcrumbs #DS-921

---

packages/web-react/scripts/helpers.ts

* there were a problem with missing `glob` dependency while migrating to Yarn Modern
* so the latest version was added but the require was not supported and glob was added using an import
* but the API was changed a little bit too
* this stay unnoticed because of the script did not fail
* when released, the end user notice that build is not working due to the missing `.js` extensions
* previous version of the `glob` - 8.10 supports the API used
* current helper is refactored to use v10 of the `glob` - Promise to async/await
- https://www.npmjs.com/package/glob
- https://www.npmjs.com/package/glob/v/8.1.0
- https://github.com/apollographql/apollo-client/blob/main/config/helpers.ts

Chore(web-react): Fix missing `.js` extensions in ESM distribution

---

docs/migrations/web-react/MIGRATION-v2.md
packages/web-react/src/components/TextField/README.md
packages/web-react/src/types/textField.ts

[web-react: Povinný label pro TextField](https://jira.almacareer.tech/browse/DS-888)

BREAKING CHANGE(web-react): Label prop is required for `TextField` component

---

packages/web-twig/DEPRECATIONS-v3.md
packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig
packages/web-twig/src/Resources/components/Header/_abstracts/Element.twig
packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig

See the Header: Abstracts Class and Style section in the web-twig package Migration Guide to version 3.

BREAKING CHANGE(web-twig): Remove class and style from abstract Header components #DS-920

---

.github/auto_assign.yml
.github/workflows/pr-meta.yaml

The currently action used action is no longer maintaned.

Chore(repo): Replace the unmaintaned auto-assign GitHub action

---

packages/web-react/src/components/Tabs/Tabs.tsx
packages/web-react/src/components/Tabs/stories/Tabs.stories.tsx
packages/web-react/src/types/tabs.ts

BREAKING CHANGE(web-react): Refactor types in Tabs #DS-935

---

.prettierignore

Because of this change: https://github.com/lmc-eu/spirit-design-system/pull/1396/files#diff-2ce177a30d5ea1036526fbef409dd193272e2da8d11ed52b57aaf42a6d5cdcd1
It look like we are not ignoring lock files 🤷

Style(repo): Ignore `lock` files by Prettier formatter

---

docs/migrations/web-react/MIGRATION-v2.md
docs/migrations/web-twig/MIGRATION-v3.md
packages/web-react/src/components/Alert/Alert.tsx
packages/web-react/src/components/Alert/README.md
packages/web-react/src/components/Alert/__tests__/Alert.test.tsx
packages/web-twig/src/Resources/components/Alert/Alert.twig
packages/web-twig/src/Resources/components/Alert/README.md
packages/web-twig/src/Resources/components/Alert/__tests__/__fixtures__/alertDefault.twig
packages/web-twig/src/Resources/components/Alert/__tests__/__snapshots__/alertDefault.twig.snap.html
packages/web/src/scss/components/Alert/README.md
packages/web/src/scss/components/Alert/index.html

BREAKING CHANGE: The alert role has been removed for Alert component #DS-1175

---

docs/migrations/web-twig/MIGRATION-v3.md
packages/web-twig/src/Resources/components/Tabs/README.md
packages/web-twig/src/Resources/components/Tabs/TabLink.twig
packages/web-twig/src/Resources/components/Tabs/__tests__/__fixtures__/tabsDefault.twig
packages/web-twig/src/Resources/components/Tabs/stories/TabsDefault.twig

See the Tabs: TabLink target prop section in the web-twig package Migration Guide to version 3.

BREAKING CHANGE(web-twig): Rename TabLink target prop to targetPaneId #DS-1096

---

packages/web-react/src/components/Collapse/UncontrolledCollapse.tsx
packages/web-react/src/components/Collapse/__tests__/UncontrolledCollapse.test.tsx
packages/web-react/src/components/Collapse/demo/Collapse.tsx
packages/web-react/src/components/Collapse/demo/CollapseDefault.tsx
packages/web-react/src/components/Collapse/demo/CollapseHelperClass.tsx
packages/web-react/src/components/Collapse/demo/CollapseHideTrigger.tsx
packages/web-react/src/components/Collapse/demo/CollapseMultipleTriggers.tsx
packages/web-react/src/components/Collapse/demo/CollapseOpenOnInit.tsx
packages/web-react/src/components/Collapse/demo/CollapseUncontrolled.tsx
packages/web-react/src/components/Collapse/demo/CollapseVisibilityBreakpointDesktop.tsx
packages/web-react/src/components/Collapse/demo/CollapseVisibilityBreakpointTablet.tsx
packages/web-react/src/types/collapse.ts
packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdown.twig.snap.html

BREAKING CHANGE: Add mandatory id prop for Collapse and Dropdown component #DS-1190

---

docs/migrations/web-react/MIGRATION-v2.md
packages/codemods/src/transforms/v2/web-react/__testfixtures__/tabs-tabitem-tabpane-props.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/tabs-tabitem-tabpane-props.output.tsx
packages/codemods/src/transforms/v2/web-react/__tests__/tabs-tabitem-tabpane-props.test.ts
packages/codemods/src/transforms/v2/web-react/tabs-tabitem-tabpane-props.ts
packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabContent.tsx
packages/web-react/src/components/Tabs/TabContext.tsx
packages/web-react/src/components/Tabs/TabItem.tsx
packages/web-react/src/components/Tabs/TabList.tsx
packages/web-react/src/components/Tabs/TabPane.tsx
packages/web-react/src/components/Tabs/Tabs.tsx
packages/web-react/src/components/Tabs/UncontrolledTabs.tsx
packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
packages/web-react/src/components/Tabs/__tests__/TabPane.test.tsx
packages/web-react/src/components/Tabs/__tests__/UncontrolledTabs.test.tsx
packages/web-react/src/components/Tabs/__tests__/useTab.test.ts
packages/web-react/src/components/Tabs/__tests__/useTabsStyleProps.test.ts
packages/web-react/src/components/Tabs/demo/TabsDefault.tsx
packages/web-react/src/components/Tabs/stories/TabContent.stories.tsx
packages/web-react/src/components/Tabs/stories/TabItem.stories.tsx
packages/web-react/src/components/Tabs/stories/TabLink.stories.tsx
packages/web-react/src/components/Tabs/stories/TabList.stories.tsx
packages/web-react/src/components/Tabs/stories/TabPane.stories.tsx
packages/web-react/src/components/Tabs/stories/Tabs.stories.tsx
packages/web-react/src/components/Tabs/stories/UncontrolledTabs.stories.tsx
packages/web-react/src/components/Tabs/useTabs.ts
packages/web-react/src/components/Tabs/useTabsStyleProps.ts
packages/web-react/src/types/tabs.ts
packages/web-react/tests/testUtils/withTabsContext.tsx

BREAKING CHANGE(web-react): Rename Tabs props and clean up its types #DS-1096

---

packages/web-react/src/hooks/__tests__/useIcon.test.tsx
packages/web-react/src/hooks/useIcon.ts

Raise a warning when there is no icon content to be provided. Also, check more strictly the fallback icon and return only when the fallback is matched. Otherwise, raise a warning and return an empty string.
- https://almamedia.slack.com/archives/C068XPSDWQN/p1715860777231279

Fix(web-react): Warn when icon asset is missing from the map

---

docs/migrations/web/MIGRATION-v2.md
packages/web/DEPRECATIONS-v2.md
packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Modal/_Modal.scss
packages/web/src/scss/components/Modal/_ModalBody.scss
packages/web/src/scss/components/Modal/_ModalDialog.scss
packages/web/src/scss/components/Modal/_theme.scss
packages/web/src/scss/components/Modal/index.html

- Make `ModalDialog` non-scrollable by default, i.e. the whole `Modal` scrolls when larger than viewport.
- Clarify how custom height and max height works, limit this feature only to scrollable `ModalDialog`.
https://jira.almacareer.tech/browse/DS-1184

BREAKING CHANGE(web): Turn off scrolling inside `ModalDialog` by default #DS-1184

---

packages/form-validations/package.json
yarn.lock

The build script was not working due to the missing TypeScript dependency and also due to the single quotes (`'...'`).

Chore(form-validations): Add missing TypeScript dependency

---

packages/web-react/DEPRECATIONS-v2.md

Just removed from deprecation file, couldn't find anything else.
ℹ️ Was removed when TooltipModern was renamed to Tooltip.
[Odstranit off placement v Tooltipu](https://jira.almacareer.tech/browse/DS-1193)

BREAKING CHANGE(web-react): Tooltip remove off placement #DS-1193 

---

.husky/pre-commit
.lintstagedrc.mjs
package.json
yarn.lock

* the `pretty-quick` is unmaintained for a while and it blocks the
upgrade to Prettier v3
* update: the `pretty-quick` is maintained again and the version 4 with the support of the Prettier v3 has been released
I have considered both libraries and I think that the `lint-staged` will be more usefull since the `pretty-quick` only runs the Prettier formatter. The `lint-staged` can be used to not only run the Prettier formatter but also other tools that can be run on staged files like ESLint or some other lints. It can be also more easier in the future to configure those tools or change Prettier for something else.
I have also considered a preformace of both libraries and it seems working pretty fast both on my machine, so this is not an issue.
- …

Style: Switch from `pretty-quick` to `lint-staged`

---

.github/workflows/test-web-twig.yaml
apps/web-twig-demo/yarn.lock
docs/migrations/web-twig/MIGRATION-v3.md
packages/web-twig/README.md
packages/web-twig/composer.json

Drop support for PHP 7.4 in web-twig bundle
https://jira.almacareer.tech/browse/DS-1212

BREAKING CHANGE(web-twig): Drop support for PHP 7.4

---

package.json
yarn.lock

* it has been replaced by the `lint-staged`

Deps: Remove `pretty-quick` from dependencies

---

packages/web-react/src/components/Tabs/demo/TabsDefault.tsx

Fix(web-react): Remove accidental Tabs demo marginTop

---

apps/web-twig-demo/assets/scripts/toast-dynamic.ts
apps/web-twig-demo/yarn.lock
packages/web-react/src/components/Toast/README.md
packages/web-react/src/components/Toast/ToastContext.tsx
packages/web-react/src/components/Toast/UncontrolledToast.tsx
packages/web-react/src/components/Toast/constants.ts
packages/web-react/src/components/Toast/demo/ToastDynamicToastQueue.tsx
packages/web-react/src/components/Toast/demo/UncontrolledToastDemo.tsx
packages/web-react/src/components/Toast/stories/ToastBar.stories.tsx
packages/web-react/src/components/Toast/stories/UncontrolledToast.stories.tsx
packages/web-react/src/utils/__tests__/delayedCallback.test.ts
packages/web-react/src/utils/delayedCallback.ts
packages/web-react/src/utils/index.ts
packages/web-twig/src/Resources/components/Toast/README.md
packages/web-twig/src/Resources/components/Toast/stories/ToastDynamicToastQueue.twig
packages/web/src/js/Toast.ts
packages/web/src/js/constants.ts
packages/web/src/scss/components/Toast/README.md
packages/web/src/scss/components/Toast/dynamic-toast.mjs
packages/web/src/scss/components/Toast/index.html

...
[Toast | automatické zavírání Toastu](https://jira.almacareer.tech/browse/DS-1251)

Feat(web, web-twig, web-react) Toast AutoClose #DS-1251

---

packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltip.twig.snap.html
packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
packages/web/src/scss/tools/_dictionaries.scss

BREAKING CHANGE: Remove placement classes #DS-1183

---

packages/web-react/src/components/Tooltip/Tooltip.tsx
packages/web-react/src/components/Tooltip/__tests__/useFloatingUI.test.ts
packages/web-react/src/components/Tooltip/useFloating.ts

In the web-react package the Tooltip is not closed by outside click when the `isDismissible` prop is set.
https://jira.almacareer.tech/browse/DS-1259

Fix(web-react): Tooltip closing by outside click when `isDismissible` prop set

---

docs/migrations/web/MIGRATION-v2.md
packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Modal/_ModalDialog.scss
packages/web/src/scss/components/Modal/_theme.scss
packages/web/src/scss/components/Modal/index.html

1. Custom height and custom max height can be set individually on all breakpoints now.
2. The `--modal-preferred-height-mobile` and `--modal-preferred-height-tablet` custom properties were renamed.
https://jira.almacareer.tech/browse/DS-1134

BREAKING CHANGE(web): Enhance custom height and max height options of `ModalDialog` #DS-1134

---

docs/migrations/web-twig/MIGRATION-v3.md
packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
packages/web-twig/src/Resources/components/Modal/README.md
packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig

BREAKING CHANGE(web-twig): Rename height and maxHeight ModalDialog props and enhance them #DS-1134

---

.prettierignore
packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
packages/web-react/src/components/FileUploader/README.md
packages/web-twig/src/Resources/components/FileUploader/FileUploaderInput.twig
packages/web-twig/src/Resources/components/FileUploader/README.md
packages/web-twig/src/Resources/components/FileUploader/__tests__/__snapshots__/fileUploaderInput.twig.snap.html
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/index.html

* the FileUploaderInput input element should never have the `required` attribute
cause it is use only for calling the dialog window
* the files are then stored in the queue
* for required validation is responsible the developer who is using this component
Ignore Twig files from formatting by Prettier.
https://jira.almacareer.tech/browse/DS-1288

Fix: FileUploader `isRequired` prop only marks label

---

docs/migrations/web-react/MIGRATION-v2.md
packages/codemods/src/transforms/v2/web-react/README.md
packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-custom-height.input.tsx
packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-custom-height.output.tsx
packages/codemods/src/transforms/v2/web-react/__tests__/modal-custom-height.test.ts
packages/codemods/src/transforms/v2/web-react/modal-custom-height.ts
packages/web-react/src/components/Modal/ModalDialog.tsx
packages/web-react/src/components/Modal/README.md
packages/web-react/src/components/Modal/__tests__/ModalDialog.test.tsx
packages/web-react/src/components/Modal/__tests__/useModalDialogStyleProps.test.ts
packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
packages/web-react/src/components/Modal/stories/ModalDialog.stories.tsx
packages/web-react/src/components/Modal/useModalDialogStyleProps.ts
packages/web-react/src/types/modal.ts

BREAKING CHANGE(web-react): Rename height and maxHeight ModalDialog props and enhance them #DS-1134

---

packages/web-react/src/hooks/__tests__/styleProps.test.ts
packages/web-react/src/hooks/styleProps.ts

While adding `styleUtilities` the second line of modification to the transfer props must be done. However the second level prop modification was pass to return but they do not conent the removal of unsupported style props.
This was fixed by using correct variable.
https://github.com/lmc-eu/spirit-design-system/commit/867ba37103c0ebed2d3d51671b2d612fa2a2dd81
https://jira.almacareer.tech/browse/DS-1339

Fix(web-react): Remove unsupported style props from modified props in style hook

---

docs/decisions/007-release-names.md

https://jira.almacareer.tech/browse/DS-1320

Docs: Introduce decision about release names

---

packages/web-twig/src/Resources/components/Checkbox/Checkbox.stories.twig
packages/web/src/scss/components/Checkbox/index.html

- In the demo, there were incorrect IDs in the JavaScript to target the checkboxes

Fix(web, web-twig): Demo - Checkbox indeterminate

---

apps/web-twig-demo/webpack.config.js

Chore(demo): Add path alias to web-twig-demo to fix missing module

---

apps/storybook/preview.ts
docs/contributtion/experimental-code.md
docs/contributtion/feature-flags.md
docs/decisions/006-experimental-code.md
docs/decisions/007-release-names.md
packages/web-react/docs/stories/feature-flags/Overview.stories.mdx
packages/web-react/src/components/UNSTABLE_Divider/stories/UNSTABLE_Divider.stories.tsx
packages/web/README.md

I have tried to document the usage of the `unstable_` prefix and made a decision for it.
It has been heavily inspired by the https://github.com/carbon-design-system/carbon/blob/5f79664cde29039ca272a4847a5b3c98c97d3e64/docs/experimental-code.md and it is like a rabbit hole. So I have tried to document also the usage of the feature flags and maybe a definition of what is the API and what not.
There may be some consideration  for the future, for instance, if we need to have some better logic around feature flags in SASS like this one https://github.com/carbon-design-system/carbon/blob/5f79664cde29039ca272a4847a5b3c98c97d3e64/packages/feature-flags/index.scss or have some kind of the FeatureFlags provider in the React like this: https://github.com/carbon-design-system/carbon/tree/5f79664cde290 …

Decision about the experimental code

---

tests/e2e/demo-components-compare.spec.ts

* when an unstable component fails due to a missing technology the test will fail but the suite will pass
I have added the `try ... catch` block and rethrow the error in case of the stable components.

Test(ci): Allow unstable components safely fail E2E tests

---

CONTRIBUTING.md
DEPRECATIONS-v3.md
MIGRATION.md
README.md
configs/jest-config-spirit/README.md
configs/prettier-config-spirit/README.md
configs/stylelint-config-spirit/README.md
docs/decisions/README.md
docs/postmortems/README.md
packages/codemods/README.md
packages/codemods/src/transforms/v2/web-react/README.md
packages/web-twig/CONTRIBUTING.md
packages/web-twig/README.md
packages/web/README.md

Docs: Change relative path to absolute path in md #DS-1364

---

packages/web-react/src/components/Tooltip/UncontrolledTooltip.tsx
packages/web-react/src/components/Tooltip/useTooltip.ts
packages/web-twig/src/Resources/components/Tooltip/README.md

- Fixed `isOpen` prop for `UncontrolledTooltip`
- Fixed missing '#' in the `data-spirit-target` in the Twig documentation examples.
[Slack message](https://almamedia.slack.com/archives/C068XPSDWQN/p1720775684492969)

Fix(web-react): Tooltip - fix reported bugs

---

packages/web-react/src/components/Tooltip/Tooltip.tsx
packages/web-react/src/components/Tooltip/TooltipContext.ts
packages/web-react/src/components/Tooltip/TooltipPopover.tsx
packages/web-react/src/components/Tooltip/__tests__/useFloatingUI.test.ts
packages/web-react/src/components/Tooltip/stories/Tooltip.stories.tsx
packages/web-react/src/components/Tooltip/useFloating.ts

Fix(web-react): Make Tooltip positionStrategy actually work

---

packages/web-twig/Makefile

The `docker-compose` from Compose v1 is now removed and `docker compose` should be used instead.
https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose
`docker-compose` doesn't work on Docker for Mac from version 4.32.0.
https://github.com/docker/for-mac/issues/7345

Fix(web-twig): Use `docker compose` instead of removed `docker-compose`

---

packages/web-react/src/components/Collapse/demo/CollapseDefault.tsx
packages/web-react/src/components/Collapse/demo/CollapseHelperClass.tsx
packages/web-react/src/components/Collapse/demo/CollapseMultipleTriggers.tsx
packages/web-react/src/components/Collapse/demo/CollapseOpenOnInit.tsx
packages/web-react/src/components/Collapse/demo/CollapseVisibilityBreakpointDesktop.tsx
packages/web-react/src/components/Collapse/demo/CollapseVisibilityBreakpointTablet.tsx
packages/web-react/src/components/Tag/demo/TagDefault.tsx
packages/web-react/src/components/UNSTABLE_PartnerLogo/__tests__/usePartnerLogoStyleProps.test.ts
packages/web-react/src/components/UNSTABLE_PartnerLogo/usePartnerLogoStyleProps.ts
packages/web-react/src/components/UNSTABLE_ProductLogo/__tests__/useProductLogoStyleProps.test.ts
packages/web-react/src/components/UNSTABLE_ProductLogo/useProductLogoStyleProps.ts

Quick fix of the props falling down to the DOM on ProductLogo and PartnerLogo components.
https://jira.almacareer.tech/browse/DS-1440

Fix(web-react): Filter out props falling into DOM in *Logo components

---

packages/web/src/scss/components/Dropdown/_DropdownPopover.scss
packages/web/src/scss/components/Dropdown/_theme.scss
packages/web/src/scss/components/index.scss

Feat(web): Switch Dropdown component to v3 design tokens #DS-1450

---

packages/web-react/src/components/index.ts

Add the missing export of the new `Flex` component in the components index file, so it can be imported directly from `@lmc-eu/spirit-web-react`.
Requested by @dlouhak

Fix(web-react): Export `Flex` component in components index file

---

.github/workflows/build.yaml
.github/workflows/commitlint.yaml
.github/workflows/component-analysis.yaml
.github/workflows/e2e.yml
.github/workflows/publish.yaml
.github/workflows/test-web-twig.yaml
.github/workflows/test.yaml
Makefile

Enabling cache while setting up Node environment. The setup-node action added new feature with Yarn caching.
Bahmutovs/npm-install still lacks the support for Yarn Modern.
https://jira.almacareer.tech/browse/DS-1402

Chore(repo): Cachable Yarn installs

---

.eslintrc.js
.prettierignore
.prettierrc.js
package.json
yarn.lock

* prefer ESM code over CJS, so async import in CJS ESLint must be used

Chore(repo): Remove duplicated Prettier config

---

packages/web-react/package.json
packages/web-react/src/components/Collapse/__tests__/useResizeHeight.test.tsx
packages/web-react/src/components/Collapse/useResizeHeight.ts
yarn.lock

Switch from the `@react-hooks/resize-observer` to `usehooks-ts`. First one is directly using `window.ResizeObserver` without any condition and this fails on Next.js SSR. The second one has a better usage behind the `isMounted` condition.
https://jira.almacareer.tech/browse/DS-1465

Feat(web-react): Use different resize observer hook

---

packages/web-react/src/components/Link/Link.tsx

The prop is called `underlined`. This typo caused `underline="hover"` attribute in the HTML.

Fix(web-react): Fix `underlined` prop default value name in Link

---

packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
packages/web-react/src/components/TextFieldBase/TextFieldBasePasswordToggle.tsx
packages/web-react/src/components/TextFieldBase/withPasswordToggle.tsx
packages/web-react/src/types/textFieldBase.ts
packages/web-twig/src/Resources/components/TextField/__tests__/__fixtures__/textFieldDefault.twig
packages/web-twig/src/Resources/components/TextField/__tests__/__fixtures__/textFieldPasswordToggle.twig
packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldDefault.twig.snap.html
packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldPasswordToggle.twig.snap.html
packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig

[Password Toggle button should be disabled if the TextField is disabled](https://jira.almacareer.tech/browse/DS-1478)

Fix(web-react, web-twig): PasswordToggle disabled #DS-1478

---

.github/actions/setup-install/action.yaml
.github/actions/setup-node/action.yaml
.github/workflows/build.yaml
.github/workflows/commitlint.yaml
.github/workflows/component-analysis.yaml
.github/workflows/docs-review.yaml
.github/workflows/e2e.yml
.github/workflows/git.yaml
.github/workflows/markdown-link-check.yaml
.github/workflows/publish.yaml
.github/workflows/supernova.yaml
.github/workflows/test-web-twig.yaml
.github/workflows/test.yaml
package.json

* it also includes a better caching of node_modules
* all jobs are now done in under 4 minutes
* emojis are used for better readability
* some jobs were separated to run in parallel
> [!IMPORTANT]
> Please, check the job names to see if they make sense to you.
- https://www.linkedin.com/pulse/continuous-integration-pipelines-frontend-monorepos-opi-danihelka-svbke/?trackingId=Z91USzlXTDCEpbI0LAVZ1A%3D%3D
- https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action

Refactor(ci): Speed up pipeline and make them more readable using emojis

---

.github/workflows/publish.yaml
CONTRIBUTING.md
Makefile

The publishing workflow was not working correctly due to the fact that the workflow was run on every push. Not even to branch, but the tag as well. This causes running multiple actions at once, because Lerna pushes multiple tags, one for each package.
So I have prepared a condition for checking push to a branch with the tags on it. So only when there is a push to the main branch and the latest commit has tags the workflow will be run.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
https://jira.almacareer.tech/browse/DS-1434

Make publishing packages on GitHub working

---

.github/workflows/test.yaml

When previous job fails, the clean up is not run. But we need to clean up cache after every run. So the cache storage is not full.

Fix(ci): Ensure running cleanup even previous job fails

---

apps/web-twig-demo/templates/partials/cover.html.twig
docs/migrations/web-react/MIGRATION-v3.md
packages/web-react/DEPRECATIONS.md
packages/web-react/src/components/Breadcrumbs/BreadcrumbsItem.tsx
packages/web-react/src/components/Breadcrumbs/README.md
packages/web-react/src/components/Breadcrumbs/demo/BreadcrumbsCustom.tsx
packages/web-react/src/components/Link/Link.tsx
packages/web-react/src/components/Link/README.md
packages/web-react/src/components/Link/__tests__/Link.test.tsx
packages/web-react/src/components/Link/__tests__/linkPropsDataProvider.ts
packages/web-react/src/components/Link/__tests__/useLinkStyleProps.test.ts
packages/web-react/src/components/Link/stories/Link.stories.tsx
packages/web-react/src/components/Link/useLinkStyleProps.ts
packages/web-react/src/types/link.ts
packages/web-twig/src/Resources/components/Breadcrumbs/BreadcrumbsItem.twig
packages/web-twig/src/Resources/components/Breadcrumbs/README.md
packages/web-twig/src/Resources/components/Breadcrumbs/__tests__/__fixtures__/breadcrumbsCustom.twig
packages/web-twig/src/Resources/components/Breadcrumbs/stories/BreadcrumbsCustom.twig
packages/web-twig/src/Resources/components/Link/Link.twig
packages/web-twig/src/Resources/components/Link/README.md
packages/web-twig/src/Resources/components/Link/__tests__/__fixtures__/linkDefault.twig

Some changes were also needed in the Breadcrumbs component, which was using the Link component.
[Remove `isUnderlined` prop from Link](https://jira.almacareer.tech/browse/DS-1509)

BC(web-react, web-twig): Remove isUnderlined from Link #DS-1509

---

docs/migrations/web-twig/MIGRATION-v4.md
packages/web-twig/DEPRECATIONS.md
packages/web-twig/src/Resources/components/Toast/README.md
packages/web-twig/src/Resources/components/Toast/__tests__/__fixtures__/toastBarLink.twig
packages/web/src/js/Toast.ts
packages/web/src/js/constants.ts
packages/web/src/scss/components/Toast/README.md

Update of `Toast` JS plugin where you can set **underline** of link inside of a `Toast` component
- default is `always`, as it was `isUnderlined={true}` before
Moved forgotten deprecations about underline to migration guide in twig
[Remove `isUnderlined` prop from Link](https://jira.almacareer.tech/browse/DS-1509)

BC(web): Toast JS plugin `isUnderlined` changed to `underlined`

---

docs/migrations/web/MIGRATION-v3.md

Docs(web): Introduce General Changes into the Migration Guide #DS-1489

---

docs/migrations/web/MIGRATION-v3.md

Docs(web): Document component changes into the Migration Guide #DS-1489

---

configs/jest-config-spirit/jsdom/setup/setupAfterEnv.js
packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
packages/web-react/src/components/FileUploader/__tests__/FileUploaderInput.test.tsx

Fix(web-react): FileUploaderInput className  #DS-1508

---

packages/web-react/src/components/FileUploader/FileUploaderInput.tsx

Remove the deprecation message from the FileUploaderInput component
[FileUploaderInput - forgotten deprecation message](https://jira.almacareer.tech/browse/DS-1525)

Refactor(web-react): Remove forgotten deprecation message

---

apps/demo/config/vite/app.ts
apps/demo/package.json
apps/storybook/main.ts
apps/web-twig-demo/package.json
apps/web-twig-demo/webpack.config.js
packages/design-tokens/README.md
packages/form-validations/package.json
packages/web-react/package.json
packages/web/package.json
yarn.lock

`sass` has been replaced with `sass-embedded` for improved performance and modern features.
More info:
https://sass-lang.com/documentation/breaking-changes/legacy-js-api/#bundlers
https://webpack.js.org/loaders/sass-loader/#api
https://vite.dev/config/shared-options.html#css-preprocessoroptions
> [!NOTE]
> DS-1499 and DS-1498 solved together
<details>
<summary>Example Build Times</summary>
| sass   																							  |
| --------------------------------------------------------------- |
| make build  133.53s user 15.91s system 277% cpu 53.807 total |
| make build  132.87s user 15.88s system 277% cpu 53.598 total |
| make build  135.18s user 17.26s system 274% cpu 55.499 total |
| make build  133.16s user 16.08s system 276% cpu 53.998 total |
| make build  132.05s user 15.87s system …

Deps(web, web-react, web-twig): Implement sass-embedded library

---

docs/migrations/web-react/MIGRATION-v3.md
packages/codemods/README.md
packages/codemods/src/transforms/v3/web-react/README.md
packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.output.tsx
packages/codemods/src/transforms/v3/web-react/__tests__/toastbar-inverted-neutral.test.ts
packages/codemods/src/transforms/v3/web-react/toastbar-inverted-neutral.ts

https://jira.almacareer.tech/browse/DS-1492

Docs(web-react): Introduce Migration Guide to version 3

---

packages/web/src/scss/components/Flex/_Flex.scss
packages/web/src/scss/components/Grid/_Grid.scss
packages/web/src/scss/components/Grid/_theme.scss
packages/web/src/scss/components/Grid/_tools.scss
packages/web/src/scss/components/Stack/_Stack.scss
packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
packages/web/src/scss/tools/__tests__/_spacing.test.scss
packages/web/src/scss/tools/_dictionaries.scss
packages/web/src/scss/tools/_spacing.scss

In `Flex`, `Grid`, and `Stack` components:
- responsive spacing is now generated exclusively with the spacing tools,
- responsive alignment is now generated exclusively with the dictionary tools.
We want to approach all layout components the same way so they are easily extensible.
https://jira.almacareer.tech/browse/DS-1423

Refactor(web): Unify generation of responsive spacing and alignment in layout components #DS-1423

---

packages/design-tokens/src/scss/themes/_color-tokens.scss

Feat(design-tokens): Add maps of tokens to color-tokens

---

docs/migrations/web-twig/MIGRATION-v4.md

Docs(web-twig): Introduce Migration Guide to version 4

---

packages/design-tokens/src/scss/themes/theme-light-default/_colors.scss
packages/design-tokens/src/scss/themes/theme-light-on-brand/_colors.scss
packages/web/src/scss/tools/_themes.scss

Feat: Add color prefix to css-variables mixin

---

examples/next-with-app-router/src/app/page.tsx
examples/next-with-pages-router/src/pages/index.tsx
packages/icons/README.md

I've tried both App Router and Pages Router. In the App router, transpilePackages does not need to be in the configuration, in the Pages Router it is necessary.
Additionaly I fixed missing mandatory elementType in Heading component for both next examples demo pages.

Docs(icons): Transpile icons #DS-987

---

packages/web-react/src/components/ButtonLink/ButtonLink.tsx
packages/web-react/src/components/ButtonLink/__tests__/ButtonLink.test.tsx
packages/web-react/src/components/ButtonLink/__tests__/useButtonLinkAriaProps.test.ts

The `elementType` prop was not passed to the `useButtonLinkAriaProps` hook and this attributes like `rel` and `target` were overridden by `undefined` value. So those could never reach the DOM element.

Fix(web-react): Pass aria props rel and target based on element type to the dom element

---

apps/demo/partials/layout/base.hbs

Chore(demo): Hide elements in Supernova component preview

---

packages/codemods/src/helpers/index.ts
packages/codemods/src/helpers/removeParentheses.ts
packages/codemods/src/transforms/v3/web-react/__testfixtures__/button-isSquare-prop-name.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/button-isSquare-prop-name.output.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/buttonLink-isSquare-prop-name.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/buttonLink-isSquare-prop-name.output.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/heading-elementType-prop.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/heading-elementType-prop.output.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/link-underlined-prop.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/link-underlined-prop.output.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.input.tsx
packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.output.tsx
packages/codemods/src/transforms/v3/web-react/button-isSquare-prop-name.ts
packages/codemods/src/transforms/v3/web-react/buttonLink-isSquare-prop-name.ts
packages/codemods/src/transforms/v3/web-react/heading-elementType-prop.ts
packages/codemods/src/transforms/v3/web-react/link-hasVisitedStyleAllowed-prop.ts
packages/codemods/src/transforms/v3/web-react/link-underlined-prop.ts
packages/codemods/src/transforms/v3/web-react/toastbar-inverted-neutral.ts
packages/codemods/tsconfig.json

Sometimges codemods are adding extra parentheses around component and it should not.
There is a bug in `recast` library used by `jscodeshift`(codemod library) casing this behaviour.
It will happen when there is `return` statement in the component.
More info can be found here:
https://github.com/facebook/jscodeshift/issues/534
https://github.com/benjamn/recast/pull/1406
[Codemods are adding extra parentheses](https://jira.almacareer.tech/browse/DS-1529)

fix(codemods): Codemods create extra parentheses 

---

docs/decisions/009-tokens-structure.md

Docs: Introduce Tokens Structure Decision

---

packages/codemods/src/transforms/v4/web-react/README.md
packages/codemods/src/transforms/v4/web-react/__testfixtures__/collapse-isDisposable-prop.input.tsx
packages/codemods/src/transforms/v4/web-react/__testfixtures__/collapse-isDisposable-prop.output.tsx
packages/codemods/src/transforms/v4/web-react/__tests__/collapse-isDisposable-prop.test.ts
packages/codemods/src/transforms/v4/web-react/collapse-isDisposable-prop.ts
packages/codemods/tsconfig.json
packages/web-react/DEPRECATIONS.md
packages/web-react/src/components/Collapse/README.md
packages/web-react/src/components/Collapse/UncontrolledCollapse.tsx
packages/web-react/src/components/Collapse/__tests__/Collapse.test.tsx
packages/web-react/src/components/Collapse/__tests__/UncontrolledCollapse.test.tsx
packages/web-react/src/components/Collapse/demo/CollapseUncontrolled.tsx
packages/web-react/src/components/Collapse/stories/UncontrolledCollapse.stories.tsx
packages/web-react/src/types/collapse.ts
packages/web-twig/DEPRECATIONS.md
packages/web-twig/src/Resources/components/Collapse/README.md
packages/web-twig/src/Resources/components/Collapse/stories/CollapseHideTrigger.twig
packages/web/DEPRECATIONS.md
packages/web/src/js/Collapse.ts
packages/web/src/js/__tests__/Collapse.test.ts
packages/web/src/scss/components/Collapse/README.md
packages/web/src/scss/components/Collapse/index.html

- Attribute `data-spirit-more` was changed to `data-spirit-is-disposable`
- Updated tests
- Updated demos
- Added deprecation messages and updated `DEPRECATIONS.md` file
- Prop `hideOnCollapse` was changed to `isDisposable`
- Updated tests
- Updated stories in storybook
- Updated demos
- Added missing test for `Collapse` component
- Created codemod for the prop change
- Added deprecation messages and updated `DEPRECATIONS.md` file
[Collapse: lepší API rozbalování](https://jira.almacareer.tech/browse/DS-832)

Refactor: Collapse API - `isDisposable`

---

.remarkrc.mjs
packages/web/src/scss/components/Accordion/README.md
packages/web/src/scss/components/FileUploader/README.md
packages/web/src/scss/components/Header/README.md
packages/web/src/scss/components/Modal/README.md
packages/web/src/scss/components/Toast/README.md

This is a little bit explosive topic, but I believe the new setup is valid and correct, no matter the linking consequences.

Chore(web): Allow duplicate headings in docs

---

.remarkignore
.remarkrc.mjs
configs/jest-config-spirit/README.md
configs/prettier-config-spirit/README.md
configs/stylelint-config-spirit/README.md
docs/postmortems/0000-00-00-template.md
docs/postmortems/2024-02-05-deprecated-icon-rendering.md
examples/next-with-app-router/README.md
examples/next-with-pages-router/README.md
exporters/assets/README.md
exporters/js/README.md
exporters/scss/README.md
exporters/tokens/README.md
package.json
packages/analytics/README.md
packages/codemods/CONTRIBUTING.md
packages/demo/README.md
packages/design-tokens/README.md
packages/icons/README.md
packages/web/DEPRECATIONS.md
packages/web/README.md
yarn.lock

https://jira.almacareer.tech/browse/DS-1100

Style(common, codemods, analytics, design-tokens): Fix docs by markdown linter

---

packages/web-react/src/components/Accordion/README.md
packages/web-react/src/components/Alert/README.md
packages/web-react/src/components/Breadcrumbs/README.md
packages/web-react/src/components/Button/README.md
packages/web-react/src/components/ButtonLink/README.md
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/components/Header/README.md
packages/web-react/src/components/Icon/README.md
packages/web-react/src/components/Item/README.md
packages/web-react/src/components/Modal/README.md
packages/web-react/src/components/Pagination/README.md
packages/web-react/src/components/Select/README.md
packages/web-react/src/components/Spinner/README.md
packages/web-react/src/components/Toast/README.md
packages/web-react/src/components/Tooltip/README.md
packages/web-react/src/components/UNSTABLE_Avatar/README.md

Docs(web-react): Add IconsProvider documentation #DS-815

---

.remarkignore
docs/contribution/experimental-code.md
docs/decisions/002-node-version.md
docs/decisions/007-release-names.md
docs/decisions/009-tokens-structure.md
docs/decisions/010-deprecations.md
docs/decisions/README.md
docs/migrations/web-react/MIGRATION-v1.md
docs/migrations/web-react/MIGRATION-v2.md
docs/migrations/web-react/MIGRATION-v3.md
docs/migrations/web-twig/MIGRATION-v2.md
docs/migrations/web-twig/MIGRATION-v3.md
docs/migrations/web-twig/MIGRATION-v4.md
docs/migrations/web/MIGRATION-v1.md
docs/migrations/web/MIGRATION-v2.md
docs/migrations/web/MIGRATION-v3.md

https://jira.almacareer.tech/browse/DS-1100

Style(docs): Fix docs using markdown linter

---

.renovaterc.json

* current state of non-major dependency updates is not managgable
* there is a lot of different package changes
* in the case when CI fails it take a lot of time to resolve where is the root
of the problem and which package update is responsible
* thus groupping the dependency updates into some smaller contexts will help us
with dependency management to be more faster and reliable
* and if something fails we should be able to recover fast
- https://github.com/lmc-eu/spirit-design-system/issues/1769
- https://jira.almacareer.tech/browse/DS-1591

Chore(deps): Group dependency updates into smaller PRs

---

.github/workflows/build.yaml

* we sometimes forget to built and commit an exporter build
* this stops the publishing of the packages because of a dirty working directory

Chore(ci): Check for the clean working directory after the build

---

packages/web-react/package.json
yarn.lock

* we cannot use web-react without web and icons package
* it also tells lerna how to manage builds and in what order
---

Chore(web-react): Web package is optional peer dependency

---

packages/web-react/src/components/FileUploader/README.md
packages/web-twig/src/Resources/components/FileUploader/README.md
packages/web/src/scss/components/FileUploader/README.md

The primary update is in the **React README**, which is now referenced by other packages.
- Added an example demonstrating how to calculate file size.
- Clarified the distinction between the `base-10` and `base-2` systems.
- Included examples for `PHP` and `Next.js` configurations, along with their shorthands.
[FileUploader: file size limit dokumentace](https://jira.almacareer.tech/browse/DS-993)

Docs: Add Info about file size in `FileUploader` #DS-993

---

packages/web-react/src/components/Box/Box.tsx
packages/web-react/src/components/Box/__tests__/useBoxStyleProps.test.ts
packages/web-react/src/components/Box/useBoxStyleProps.ts
packages/web-react/src/components/Footer/Footer.tsx
packages/web-react/src/components/Footer/__tests__/useFooterStyleProps.test.ts
packages/web-react/src/components/Footer/useFooterStyleProps.ts
packages/web-react/src/constants/style.ts
packages/web-react/src/hooks/__tests__/styleProps.test.ts
packages/web-react/src/hooks/__tests__/useStyleUtilities.test.ts
packages/web-react/src/hooks/styleProps.ts
packages/web-react/src/hooks/useStyleUtilities.ts

Feat(web-react): Additional parameter for styleProps and Box refactor

---

.remarkrc.mjs
configs/typescript-config-spirit/README.md
package.json
packages/web-react/src/components/FileUploader/README.md
packages/web-react/src/components/Grid/README.md
packages/web-twig/src/Resources/components/Dropdown/README.md
packages/web-twig/src/Resources/components/Grid/README.md
packages/web/src/scss/components/Dropdown/README.md
packages/web/src/scss/components/Grid/README.md
yarn.lock

Switch back to heading capitalization official package

---

packages/web-react/src/components/Card/__tests__/CardBody.test.tsx

Test(web-react): Fix typo in data-testid attribute

---

packages/web-react/src/components/Box/__tests__/Box.test.tsx
packages/web-react/src/components/Box/useBoxStyleProps.ts
packages/web-react/src/components/Footer/__tests__/Footer.test.tsx
packages/web-react/src/components/Footer/useFooterStyleProps.ts
packages/web-react/src/components/Item/__tests__/Item.test.tsx
packages/web-react/src/components/TextFieldBase/__tests__/TextFieldBase.test.tsx
packages/web-react/src/components/Tooltip/__tests__/Tooltip.test.tsx
packages/web-react/src/components/UNSTABLE_Slider/__tests__/UNSTABLE_Slider.test.tsx
packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
packages/web-react/src/components/UNSTABLE_Truncate/useTruncateStyleProps.ts

Feat(web-react): Add prefixed utility class #DS-1618

---

packages/web-react/src/components/Tabs/TabItem.tsx
packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
packages/web-twig/src/Resources/components/Tabs/TabItem.twig
packages/web-twig/src/Resources/components/Tabs/TabLink.twig
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsDefault.twig.snap.html
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacing.twig.snap.html
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacingForEachBreakpoint.twig.snap.html
packages/web/src/scss/components/Tabs/README.md
packages/web/src/scss/components/Tabs/index.html

Fix: Add missing presentation role to Tabs Item #DS-1653 in 2.x version

---

packages/web-react/src/components/index.ts

There were missing exports for `ActionGroup` and `Box` in the components index file.

Fix(web-react): `ActionGroup` and `Box` exports

---

exporters/tokens/README.md

Docs(exporter-tokens): Update tokens exporter documentation #DS-1544

---

packages/web-react/src/components/Dropdown/DropdownTrigger.tsx

Removing `id` attribute from DropdownTrigger
https://github.com/lmc-eu/spirit-design-system/issues/1892

Fix(web-react): Remove duplicated `id` on the `DropdownTrigger` component

---

packages/web-react/src/components/Navigation/NavigationAction.tsx
packages/web-react/src/components/Navigation/README.md
packages/web-react/src/components/Navigation/__tests__/NavigationAction.test.tsx
packages/web-react/src/components/Navigation/__tests__/useNavigationStyleProps.test.ts
packages/web-react/src/components/Navigation/constants.ts
packages/web-react/src/components/Navigation/demo/NavigationHorizontalWithBoxAction.tsx
packages/web-react/src/components/Navigation/demo/NavigationHorizontalWithPillAction.tsx
packages/web-react/src/components/Navigation/demo/NavigationVerticalWithBoxAction.tsx
packages/web-react/src/components/Navigation/demo/NavigationVerticalWithPillAction.tsx
packages/web-react/src/components/Navigation/demo/index.tsx
packages/web-react/src/components/Navigation/stories/NavigationAction.stories.tsx
packages/web-react/src/components/Navigation/useNavigationStyleProps.ts
packages/web-react/src/components/UNSTABLE_Header/demo/HeaderWithNavigation/MainNavigation.tsx
packages/web-react/src/components/UNSTABLE_Header/demo/HeaderWithPillNavigation.tsx
packages/web-react/src/components/UNSTABLE_Header/demo/index.tsx
packages/web-react/src/types/navigation.ts

Feat(web-react): Introduce variants to NavigationAction #DS-1672

---

packages/web-react/src/components/Checkbox/Checkbox.tsx
packages/web-react/src/components/Field/Label.tsx
packages/web-react/src/components/Field/README.md
packages/web-react/src/components/Field/__tests__/Label.test.tsx
packages/web-react/src/components/Field/index.ts
packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
packages/web-react/src/components/Radio/Radio.tsx
packages/web-react/src/components/Select/Select.tsx
packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
packages/web-react/src/components/UNSTABLE_Slider/UNSTABLE_Slider.tsx
packages/web-react/src/components/UNSTABLE_Toggle/UNSTABLE_Toggle.tsx
packages/web-react/src/types/label.ts

[Separate Label field subcomponent | Web React](https://jira.almacareer.tech/browse/DS-1566)

Feat(web-react): Introduce `Label` component #DS-1566

---

packages/web-react/src/components/TextFieldBase/__tests__/useTextFieldBaseStyleProps.test.ts
packages/web-react/src/components/TextFieldBase/useTextFieldBaseStyleProps.ts

* Warning: React does not recognize the `validationState` prop on a DOM element.

Fix(web-react): Remove `validationState` from passed props of the TextFieldBase style hook

---

packages/web-react/src/components/Dropdown/DropdownTrigger.tsx
packages/web-react/src/components/Dropdown/__tests__/Dropdown.test.tsx
packages/web-react/src/components/Dropdown/__tests__/useDropdownAriaProps.test.ts
packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts

**Fixed duplicate `Dropdown` `id` on both `DropdownTrigger` and `DropdownPopover`**  
1. Removed `id` from `DropdownTrigger` props.  
2. Removed `id` from the `useDropdownAriaProps` hook, which was sending it again via `triggerProps`.  
3. Updated tests accordingly.  
Slack support ticket
https://almamedia.slack.com/archives/C068XPSDWQN/p1739283201863299?thread_ts=1738072882.361189&cid=C068XPSDWQN
- https://github.com/lmc-eu/spirit-design-system/issues/1892
- https://github.com/lmc-eu/spirit-design-system/commit/f418ef66f709376bfd7adfb099edbb1917a8ac48

Fix(web-react): Remove duplicated id on the DropdownTrigger component

---

packages/web-react/src/components/SplitButton/README.md
packages/web-react/src/components/SplitButton/UncontrolledSplitButton.tsx
packages/web-react/src/components/SplitButton/__tests__/UncontrolledSplitButton.test.tsx
packages/web-react/src/components/SplitButton/demo/UncontrolledSplitButton.tsx
packages/web-react/src/components/SplitButton/index.ts
packages/web-react/src/components/SplitButton/stories/UncontrolledSplitButton.stories.tsx
packages/web-react/src/types/splitButton.ts

Uncontrolled demo will be removed before merge
[Component UncontrolledSplitButton | React](https://jira.almacareer.tech/browse/DS-1671)

Feat(web-react): Introduce `UncontrolledSplitButton` #DS-1656

---

.github/workflows/test-web-twig.yaml
packages/web-twig/composer.json
packages/web-twig/ecs.php
packages/web-twig/src/Twig/PropsExtension.php
packages/web-twig/src/Twig/SvgExtension.php
packages/web-twig/tests/ComponentTest.php

Replace deprecated lmc/coding-standard with [almacareer/coding-standard](https://github.com/alma-oss/php-coding-standard).
Also run PHP tests & codestyle on PHP 8.4. This leads to update in easy-coding-standard and detecting some previously undetected codestyle violations.

Chore(web-twig): Replace lmc/coding-standard with almacareer/coding-standard

---

packages/web-react/src/components/Checkbox/Checkbox.tsx
packages/web-react/src/components/Field/HelperText.tsx
packages/web-react/src/components/Field/README.md
packages/web-react/src/components/Field/ValidationText.tsx
packages/web-react/src/components/Field/__tests__/HelperText.test.tsx
packages/web-react/src/components/Field/__tests__/ValidationText.test.tsx
packages/web-react/src/components/Field/types.ts
packages/web-react/src/components/FieldGroup/FieldGroup.tsx
packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
packages/web-react/src/components/Item/Item.tsx
packages/web-react/src/components/Radio/Radio.tsx
packages/web-react/src/components/Select/Select.tsx
packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
packages/web-react/src/components/UNSTABLE_Slider/UNSTABLE_Slider.tsx
packages/web-react/src/components/UNSTABLE_Toggle/UNSTABLE_Toggle.tsx

Adding the `useStyleProps` hook to `ValidationText` and `HelperText`, so they accept `UNSAFE_className` instead of `className`, like the rest of our components.  
These components are used only internally, so this is not a breaking change.  
[Unify UNSAFE_className/className in HelperText and ValidationText](https://jira.almacareer.tech/browse/DS-1679)

Feat(web-react): HelperText and ValidationText use UNSAFE_className

---

packages/web-react/src/components/Checkbox/Checkbox.tsx
packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
packages/web-react/src/components/UNSTABLE_Slider/UNSTABLE_Slider.tsx

`hasValidationIcon` prop was forwarded to DOM element

Fix(web-react): Forgotten hasValidationIcon prop on DOM element

---

packages/web/DEPRECATIONS.md
packages/web/src/scss/components/Skeleton/README.md
packages/web/src/scss/components/Skeleton/_Skeleton.scss
packages/web/src/scss/components/Skeleton/_theme.scss
packages/web/src/scss/tools/_tokens.scss

https://jira.almacareer.tech/browse/DS-1692

Fix(web): Prevent Skeleton SCSS from failing if tokens are not found #DS-1692

---

packages/web-react/src/components/Accordion/Accordion.tsx
packages/web-react/src/components/Collapse/Collapse.tsx
packages/web-react/src/components/Stack/Stack.tsx
packages/web-react/src/components/Tabs/TabLink.tsx
packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
packages/web-react/src/components/VisuallyHidden/VisuallyHidden.tsx

- element tag was forwarded to dom element

Fix(web-react): Forgotten elementType in useStyleProps hook

---

apps/demo/partials/web-react/tabs.hbs
packages/web-react/src/icons/demo/icons.tsx

We were missing a Container in React in Icons, and also, some other spacing was not unified with the web.

Docs(web-react): Unify Icons demo style

---

packages/web-twig/src/Resources/components/Container/stories/ContainerTextAlignment.twig

It was not failing in CI because we do not test Twig e2e in CI 🙃 But locally it failed.
@curdaj 🔫

Fix(web-twig): Remove additional Container demo causing failing Twig e2e tests

---

configs/eslint-config-spirit/index.js
packages/web-react/.eslintrc.js
packages/web-react/config/rollup.config.js
packages/web-react/scripts/helpers.ts
packages/web-react/src/components/Text/__tests__/Text.test.tsx
packages/web-react/src/components/Text/demo/index.tsx
packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
packages/web-react/src/components/VisuallyHidden/__tests__/VisuallyHidden.test.tsx
packages/web-react/src/hooks/__tests__/useStyleUtilities.test.ts

Import order ruleset is now applied back to the web-react package with  some additional setting of ordering `@local/` scope to appropriate location between imports.

Style(web-react): Correcting the import order

---

apps/web-twig-demo/assets/app.ts
apps/web-twig-demo/assets/scripts/file-uploader-image-preview.ts
apps/web-twig-demo/assets/scripts/file-uploader-meta-data.ts
apps/web-twig-demo/assets/scripts/form-validations.ts
apps/web-twig-demo/assets/scripts/toast-dynamic.ts
apps/web-twig-demo/tsconfig.json
packages/web/src/js/AutoResize.ts
packages/web/src/js/BaseComponent.ts
packages/web/src/js/Collapse.ts
packages/web/src/js/Dropdown.ts
packages/web/src/js/FileUploader.ts
packages/web/src/js/Modal.ts
packages/web/src/js/Offcanvas.ts
packages/web/src/js/Password.ts
packages/web/src/js/ScrollView.ts
packages/web/src/js/Tabs.ts
packages/web/src/js/Toast.ts
packages/web/src/js/Tooltip.ts
packages/web/src/js/dom/InstanceMap.ts
packages/web/src/js/dom/Manipulator.ts
packages/web/src/js/dom/SelectorEngine.ts
packages/web/src/js/types.ts
packages/web/src/js/utils/Config.ts
packages/web/src/js/utils/Elements.ts
packages/web/src/js/utils/Transitions.ts

Fixing type errors which are blocking web-twig demo builds.

Fix(demo): Type errors

---

packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabContext.tsx
packages/web-react/src/components/Tabs/TabItem.tsx
packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
packages/web-react/src/types/tabs.ts

[Support: Tabs - extends `onSelectionChange` with optional currentId](https://jira.almacareer.tech/browse/DS-1785)

Feat(web-react): Add currentId to `Tab` onSelectionChange callback

---

packages/web-react/src/components/Tooltip/TooltipPopover.tsx

[DS-1790](https://jira.almacareer.tech/browse/DS-1790)

Fix(web-react): Do not pass the `placement` prop to the DOM of the TooltipPopover #DS-1790

---

packages/web-react/src/hooks/__tests__/useStyleUtilities.test.ts
packages/web-react/src/hooks/useStyleUtilities.ts
packages/web-react/src/utils/__tests__/assert.test.ts
packages/web-react/src/utils/assert.ts

Check the value of the style props and do not process the one without value or nullable one.
Example of the condition that causes this.
```diff
---	  marginBottom={!showTogglerAfterCollapse ? 'space-300' : undefined}
+++   {...(!showTogglerAfterCollapse && { marginBottom: 'space-300' })}
```
I have not changed the types, because I think that the `undefined` or `null` value should not be passed. However I do not want to our code fail, if `marginBottom: undefined` will be used. This value will only not be passed as a final utility class.
Somehow, on the application side, the TypeScript types did not help here.
I have also added some JSDoc comments for better Intelisense in our code.
https://jira.almacareer.tech/browse/DS-1715

Fix(web-react): Do not process style props with `null` or `undefined` values

---

examples/next-with-app-router/README.md
examples/next-with-app-router/postcss.config.json

This PR introduces a new rule to enforce the use of flex-start instead of start for the justify-content property in the codebase.
Due to a limitation in Next.js, the correct browserslist configuration wasn't being respected, leading to a misleading build-time warning when using start as a value for justify-content. As a workaround, this rule has been added to prevent the use of start and to ensure that flex-start is used instead.
Additionally, all occurrences of start for the justify-content property have been manually updated to flex-start to resolve this issue across the codebase.
EDIT: 
I managed to solve it using configuration in nextjs. The original solution has been removed.

Fix(examples): Add postcss configuration to suppress flexbox warning #DS-1778

---

.github/actions/has-tags/action.yaml
.github/workflows/publish.yaml
.github/workflows/supernova.yaml

Second run, double fun. I have tried and failed. The repository must be cloned first, so the composite action is accessible.
Tested using custom action:
```yaml
name: Test Has Tags Action
on:
push:
branches:
- main
jobs:
test-has-tags:
runs-on: ubuntu-latest
steps:
- name: Clone repository
uses: actions/checkout@v4
with:
fetch-tags: true
fetch-depth: 0
- name: Run Has Tags Action
uses: ./.github/actions/has-tags
```
https://github.com/nektos/act
`act push -W .github/workflows/test-has-tags.yaml --verbose`
https://jira.almacareer.tech/browse/DS-1801

Chore(ci): Repository must be cloned first to access the composite action

---

packages/web-react/src/components/Item/Item.tsx
packages/web-twig/src/Resources/components/Item/Item.twig
packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemDefault.twig.snap.html
packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemDisabled.twig.snap.html
packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemHelperText.twig.snap.html
packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemIcon.twig.snap.html
packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemSelected.twig.snap.html

Aria Selected attribute is only for tabs, options and some table elements.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-selected

Feat(web-react,web-twig): Remove aria-selected from Item #DS-1851

---

packages/web-react/src/components/Tabs/README.md
packages/web-react/src/components/Tabs/TabLink.tsx
packages/web-twig/src/Resources/components/Tabs/README.md
packages/web-twig/src/Resources/components/Tabs/TabLink.twig
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsDefault.twig.snap.html
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacing.twig.snap.html
packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacingForEachBreakpoint.twig.snap.html
packages/web/src/scss/components/Tabs/README.md

When the item in Tab is a link, it should not have aria-selected attribute.

Fix(web,web-react,web-twig): Remove aria-selected and role from TabLink #DS-1851

---

exporters/tokens/README.md
packages/design-tokens/src/js/devices/index.ts
packages/design-tokens/src/js/global-tokens/other.ts
packages/design-tokens/src/js/index.ts
packages/design-tokens/src/scss/@tokens.scss
packages/design-tokens/src/scss/devices/index.scss
packages/design-tokens/src/scss/global-tokens/_other.scss

[Form | Radius | New design-tokens structure](https://jira.almacareer.tech/browse/DS-1872)

Feat(exporter): Add new files for device tokens

---

packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
packages/web/src/scss/components/SegmentedControl/_theme.scss

When you click on some item, the active background that slides into position is below the hover background, so the hover background for a moment, overlaps the active background.

Refactor(web): Hover background for a moment overlaps the active bg #DS-1902

---

packages/web/src/scss/settings/_utilities.scss

`$border-focus` token is for private usage only and should only be used within the focus state

Fix(web): Do not export `border-focus` as utility class

---

packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
packages/web/src/scss/tools/_dictionaries.scss

Dictionary configs (used for generating component variants) are now more reliably validated against provided dictionary values. Now we check not only the presence of every config key in dictionary values, but we also check the length of both lists so we can be more sure they actually match.
Since the `generate-sizes()` mixin generates the same output as the `generate-variants()` mixin, it has been refactored to call the `generate-variants()` mixin.

Refactor(web): Improve validation of dictionary configs

---

packages/web/src/scss/tools/__tests__/_utilities.test.scss
packages/web/src/scss/tools/_utilities.scss

It was failing when adopters didn't have the new gradient tokens.

Fix(web): Check if utility values list is not empty before generating

---

packages/web/src/scss/helpers/text/_text.scss
packages/web/src/scss/helpers/text/index.html

Adding the helper class name to experience dotted underlined text.
\-
🔗 [DS-1949](https://jira.almacareer.tech/browse/DS-1949)

Feat(web): Introduce text helper for underlined dotted texts #DS-1949

---

packages/web-react/src/components/ScrollView/useScrollPosition.ts
packages/web-react/src/hooks/index.ts

fixes an undefined `window` error in cyborg
```
Import trace for requested module:
../../libs/design-system/index.ts
⨯ ReferenceError: window is not defined
at useScrollPosition (../../../src/components/ScrollView/useScrollPosition.ts:69:2)
at ScrollView (../../../src/components/ScrollView/ScrollView.tsx:23:77) {
digest: '1603275361'
}
```
https://jira.almacareer.tech/browse/DS-2029

Fix(web-react): Fix undefined `window` reference in server-side call #DS-2029

---

packages/web-react/src/components/PricingPlan/README.md
packages/web-react/src/components/PricingPlan/stories/PricingPlanBody.stories.tsx
packages/web-react/src/types/pricingPlan.ts

Add ReactNode type to PricingPlanFeature description

Feat(web-react): Add ReactNode type to PricingPlanFeature description

---

packages/web-react/src/components/Matrix/README.md
packages/web/src/scss/components/Matrix/README.md
packages/web/src/scss/components/Matrix/_Matrix.scss

We found out the root of the issue was in the top margin of `Matrix` items.
Forcing the repaint actually did not fix the issue for us, so we can remove it.
Additionally, expand `Matrix` width to 100% of its container to match the behavior of `Grid`.
This change reverts the "fix" originally introduced in https://github.com/lmc-eu/spirit-design-system/pull/2134.
https://jira.almacareer.tech/browse/DS-2051

Refactor(web): Remove a recent "fix" of `Matrix` rendering in Safari #DS-2051

---

packages/web-react/src/components/Collapse/useResizeHeight.ts

- Content is now not rendered under the Collapse on initial load
- Undefined height prevents the content below the opened Collapse from being pushed down when the height is calculated
Fix for Cyborg/Prace.cz (localhost:3000/nabidky)
[Collapse has 0px height on page load](https://jira.almacareer.tech/browse/DS-2048)

Fix(web-react): Set default height of opened Collapse to undefined #DS-2048

---

packages/web-react/src/components/Pagination/PaginationLink.tsx
packages/web/src/scss/settings/_utilities.scss

- `PaginationLink` was not accepting any `elementType` other than 'a'
- Found typo in utility class name
- When consulting some stuff with Search team, found this bug in types and typo.

Fix(web-react): Fixed type in `PaginationLink` component

---

.github/actions/setup-node/action.yaml
.github/workflows/publish.yaml

NPM has introduced Trusted Publishing using OICD, so there will be no need for a long-term token on the GitHub Actions side. The manual publishing using the tokens should still work; however, this should be a safer way.
https://docs.npmjs.com/trusted-publishers

Chore(ci): Enable trusted publishing using GitHub Actions and npm

---

.github/workflows/publish.yaml

The `npm` environment has been set up to add an additional layer of protection for publishing our packages to npm repository. It means that every run of the `publish.yaml` action that will publish a package to npm must be authorized/approved by a second person (this setting can be discussed). 
- https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments
- https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments

Chore(ci): Set GitHub Actions environment for npm publishing

---

.github/actions/setup-install/action.yaml

Chore(ci): Reuse setup-node action in setup-install so the registry is correctly set
